// ══════════════════════════════════════════════════════════════════
// FOOD DATABASE — ~500 foods with verified USDA-based nutrition data
// All values are per serving as indicated
// Sources: USDA FoodData Central, verified nutrition labels
// ══════════════════════════════════════════════════════════════════

export interface FoodItem {
  name: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
  serving: string;
  category: string;
  emoji: string;
}

import { extraFoods } from "./food-db-extra";

const baseFoods: Record<string, FoodItem> = {

  // ─────────────────── FRUITS ───────────────────
  apple: { name: "Apple", calories: 95, protein: 0.5, carbs: 25, fat: 0.3, fiber: 4.4, serving: "1 medium (182g)", category: "fruits", emoji: "🍎" },
  green_apple: { name: "Green Apple", calories: 97, protein: 0.5, carbs: 25.6, fat: 0.3, fiber: 4.4, serving: "1 medium (182g)", category: "fruits", emoji: "🍏" },
  banana: { name: "Banana", calories: 105, protein: 1.3, carbs: 27, fat: 0.4, fiber: 3.1, serving: "1 medium (118g)", category: "fruits", emoji: "🍌" },
  orange: { name: "Orange", calories: 62, protein: 1.2, carbs: 15, fat: 0.2, fiber: 3.1, serving: "1 medium (131g)", category: "fruits", emoji: "🍊" },
  mandarin: { name: "Mandarin / Clementine", calories: 47, protein: 0.7, carbs: 12, fat: 0.2, fiber: 1.8, serving: "1 medium (74g)", category: "fruits", emoji: "🍊" },
  grapefruit: { name: "Grapefruit", calories: 52, protein: 1, carbs: 13, fat: 0.2, fiber: 2, serving: "1/2 fruit (123g)", category: "fruits", emoji: "🍊" },
  lemon: { name: "Lemon", calories: 17, protein: 0.6, carbs: 5.4, fat: 0.2, fiber: 1.6, serving: "1 medium (58g)", category: "fruits", emoji: "🍋" },
  lime: { name: "Lime", calories: 20, protein: 0.5, carbs: 7, fat: 0.1, fiber: 1.9, serving: "1 medium (67g)", category: "fruits", emoji: "🍋" },
  strawberry: { name: "Strawberries", calories: 49, protein: 1, carbs: 12, fat: 0.5, fiber: 3, serving: "1 cup (152g)", category: "fruits", emoji: "🍓" },
  blueberries: { name: "Blueberries", calories: 84, protein: 1.1, carbs: 21, fat: 0.5, fiber: 3.6, serving: "1 cup (148g)", category: "fruits", emoji: "🫐" },
  raspberries: { name: "Raspberries", calories: 64, protein: 1.5, carbs: 15, fat: 0.8, fiber: 8, serving: "1 cup (123g)", category: "fruits", emoji: "🫐" },
  blackberries: { name: "Blackberries", calories: 62, protein: 2, carbs: 14, fat: 0.7, fiber: 7.6, serving: "1 cup (144g)", category: "fruits", emoji: "🫐" },
  grapes: { name: "Grapes", calories: 104, protein: 1.1, carbs: 27, fat: 0.2, fiber: 1.4, serving: "1 cup (151g)", category: "fruits", emoji: "🍇" },
  mango: { name: "Mango", calories: 99, protein: 1.4, carbs: 25, fat: 0.6, fiber: 2.6, serving: "1 cup (165g)", category: "fruits", emoji: "🥭" },
  pineapple: { name: "Pineapple", calories: 82, protein: 0.9, carbs: 22, fat: 0.2, fiber: 2.3, serving: "1 cup (165g)", category: "fruits", emoji: "🍍" },
  watermelon: { name: "Watermelon", calories: 46, protein: 0.9, carbs: 12, fat: 0.2, fiber: 0.6, serving: "1 cup diced (152g)", category: "fruits", emoji: "🍉" },
  cantaloupe: { name: "Cantaloupe", calories: 54, protein: 1.3, carbs: 13, fat: 0.3, fiber: 1.4, serving: "1 cup diced (160g)", category: "fruits", emoji: "🍈" },
  honeydew: { name: "Honeydew Melon", calories: 64, protein: 1, carbs: 16, fat: 0.2, fiber: 1.4, serving: "1 cup diced (170g)", category: "fruits", emoji: "🍈" },
  peach: { name: "Peach", calories: 59, protein: 1.4, carbs: 14, fat: 0.4, fiber: 2.3, serving: "1 medium (150g)", category: "fruits", emoji: "🍑" },
  nectarine: { name: "Nectarine", calories: 63, protein: 1.5, carbs: 15, fat: 0.5, fiber: 2.4, serving: "1 medium (142g)", category: "fruits", emoji: "🍑" },
  pear: { name: "Pear", calories: 102, protein: 0.6, carbs: 27, fat: 0.2, fiber: 5.5, serving: "1 medium (178g)", category: "fruits", emoji: "🍐" },
  plum: { name: "Plum", calories: 30, protein: 0.5, carbs: 8, fat: 0.2, fiber: 0.9, serving: "1 medium (66g)", category: "fruits", emoji: "🍑" },
  apricot: { name: "Apricot", calories: 17, protein: 0.5, carbs: 4, fat: 0.1, fiber: 0.7, serving: "1 medium (35g)", category: "fruits", emoji: "🍑" },
  cherry: { name: "Cherries", calories: 87, protein: 1.5, carbs: 22, fat: 0.3, fiber: 2.9, serving: "1 cup (138g)", category: "fruits", emoji: "🍒" },
  kiwi: { name: "Kiwi", calories: 42, protein: 0.8, carbs: 10, fat: 0.4, fiber: 2.1, serving: "1 medium (69g)", category: "fruits", emoji: "🥝" },
  pomegranate: { name: "Pomegranate Seeds", calories: 144, protein: 2.9, carbs: 33, fat: 2, fiber: 7, serving: "1 cup (174g)", category: "fruits", emoji: "🍎" },
  passion_fruit: { name: "Passion Fruit", calories: 17, protein: 0.4, carbs: 4, fat: 0.1, fiber: 1.9, serving: "1 fruit (18g)", category: "fruits", emoji: "🍈" },
  fig: { name: "Fig (fresh)", calories: 37, protein: 0.4, carbs: 10, fat: 0.2, fiber: 1.4, serving: "1 medium (50g)", category: "fruits", emoji: "🍇" },
  dried_fig: { name: "Dried Figs", calories: 186, protein: 2.5, carbs: 48, fat: 0.9, fiber: 7.3, serving: "1/4 cup (40g)", category: "fruits", emoji: "🍇" },
  dates: { name: "Dates (Medjool)", calories: 66, protein: 0.4, carbs: 18, fat: 0, fiber: 1.6, serving: "1 date (24g)", category: "fruits", emoji: "🍇" },
  avocado: { name: "Avocado", calories: 240, protein: 3, carbs: 12, fat: 22, fiber: 10, serving: "1 medium (150g)", category: "fruits", emoji: "🥑" },
  coconut: { name: "Coconut (shredded)", calories: 283, protein: 2.7, carbs: 12, fat: 27, fiber: 7.2, serving: "1 cup (80g)", category: "fruits", emoji: "🥥" },
  lychee: { name: "Lychee", calories: 63, protein: 0.8, carbs: 16, fat: 0.4, fiber: 1.3, serving: "1 cup (95g)", category: "fruits", emoji: "🍈" },
  papaya: { name: "Papaya", calories: 62, protein: 0.7, carbs: 16, fat: 0.4, fiber: 2.5, serving: "1 cup (145g)", category: "fruits", emoji: "🍈" },
  guava: { name: "Guava", calories: 37, protein: 1.4, carbs: 8, fat: 0.5, fiber: 3, serving: "1 fruit (55g)", category: "fruits", emoji: "🍈" },
  dragon_fruit: { name: "Dragon Fruit", calories: 102, protein: 2, carbs: 22, fat: 0.4, fiber: 5, serving: "1 fruit (200g)", category: "fruits", emoji: "🍈" },
  cranberries: { name: "Cranberries (fresh)", calories: 46, protein: 0.4, carbs: 12, fat: 0.1, fiber: 4.6, serving: "1 cup (100g)", category: "fruits", emoji: "🫐" },
  dried_cranberries: { name: "Dried Cranberries", calories: 123, protein: 0, carbs: 33, fat: 0.5, fiber: 2, serving: "1/4 cup (40g)", category: "fruits", emoji: "🫐" },
  raisins: { name: "Raisins", calories: 129, protein: 1.4, carbs: 34, fat: 0.2, fiber: 1.6, serving: "1/4 cup (40g)", category: "fruits", emoji: "🍇" },

  // ─────────────────── VEGETABLES ───────────────────
  broccoli: { name: "Broccoli", calories: 55, protein: 3.7, carbs: 11, fat: 0.6, fiber: 5.1, serving: "1 cup (156g)", category: "vegetables", emoji: "🥦" },
  cauliflower: { name: "Cauliflower", calories: 25, protein: 2, carbs: 5, fat: 0.1, fiber: 2, serving: "1 cup (100g)", category: "vegetables", emoji: "🥦" },
  carrot: { name: "Carrot", calories: 25, protein: 0.6, carbs: 6, fat: 0.1, fiber: 1.7, serving: "1 medium (61g)", category: "vegetables", emoji: "🥕" },
  spinach: { name: "Spinach (raw)", calories: 7, protein: 0.9, carbs: 1.1, fat: 0.1, fiber: 0.7, serving: "1 cup (30g)", category: "vegetables", emoji: "🥬" },
  cooked_spinach: { name: "Spinach (cooked)", calories: 41, protein: 5.3, carbs: 6.8, fat: 0.5, fiber: 4.3, serving: "1 cup (180g)", category: "vegetables", emoji: "🥬" },
  kale: { name: "Kale", calories: 33, protein: 2.9, carbs: 6, fat: 0.6, fiber: 1.3, serving: "1 cup (67g)", category: "vegetables", emoji: "🥬" },
  lettuce: { name: "Lettuce (romaine)", calories: 8, protein: 0.6, carbs: 1.5, fat: 0.1, fiber: 1, serving: "1 cup (47g)", category: "vegetables", emoji: "🥬" },
  arugula: { name: "Arugula", calories: 5, protein: 0.5, carbs: 0.7, fat: 0.1, fiber: 0.3, serving: "1 cup (20g)", category: "vegetables", emoji: "🥬" },
  tomato: { name: "Tomato", calories: 22, protein: 1.1, carbs: 4.8, fat: 0.2, fiber: 1.5, serving: "1 medium (123g)", category: "vegetables", emoji: "🍅" },
  cherry_tomato: { name: "Cherry Tomatoes", calories: 27, protein: 1.3, carbs: 5.8, fat: 0.3, fiber: 1.8, serving: "1 cup (149g)", category: "vegetables", emoji: "🍅" },
  cucumber: { name: "Cucumber", calories: 16, protein: 0.7, carbs: 3.8, fat: 0.1, fiber: 0.5, serving: "1 cup sliced (104g)", category: "vegetables", emoji: "🥒" },
  zucchini: { name: "Zucchini", calories: 21, protein: 1.5, carbs: 3.9, fat: 0.4, fiber: 1.2, serving: "1 medium (196g)", category: "vegetables", emoji: "🥒" },
  eggplant: { name: "Eggplant", calories: 35, protein: 0.8, carbs: 8.6, fat: 0.2, fiber: 2.5, serving: "1 cup (82g)", category: "vegetables", emoji: "🍆" },
  bell_pepper: { name: "Bell Pepper", calories: 31, protein: 1, carbs: 6, fat: 0.3, fiber: 2.1, serving: "1 medium (119g)", category: "vegetables", emoji: "🫑" },
  jalapeno: { name: "Jalapeño", calories: 4, protein: 0.1, carbs: 0.9, fat: 0.1, fiber: 0.4, serving: "1 pepper (14g)", category: "vegetables", emoji: "🌶️" },
  chili_pepper: { name: "Chili Pepper", calories: 18, protein: 0.9, carbs: 4, fat: 0.2, fiber: 0.7, serving: "1 pepper (45g)", category: "vegetables", emoji: "🌶️" },
  onion: { name: "Onion", calories: 44, protein: 1.2, carbs: 10, fat: 0.1, fiber: 1.9, serving: "1 medium (110g)", category: "vegetables", emoji: "🧅" },
  green_onion: { name: "Green Onion / Scallion", calories: 5, protein: 0.3, carbs: 1.1, fat: 0, fiber: 0.4, serving: "1 stalk (15g)", category: "vegetables", emoji: "🧅" },
  shallot: { name: "Shallot", calories: 29, protein: 1, carbs: 7, fat: 0, fiber: 0, serving: "1 medium (40g)", category: "vegetables", emoji: "🧅" },
  leek: { name: "Leek", calories: 54, protein: 1.3, carbs: 13, fat: 0.3, fiber: 1.6, serving: "1 medium (89g)", category: "vegetables", emoji: "🧅" },
  garlic: { name: "Garlic", calories: 4, protein: 0.2, carbs: 1, fat: 0, fiber: 0.1, serving: "1 clove (3g)", category: "vegetables", emoji: "🧄" },
  ginger: { name: "Ginger (fresh)", calories: 2, protein: 0, carbs: 0.4, fat: 0, fiber: 0, serving: "1 tsp grated (2g)", category: "vegetables", emoji: "🧄" },
  potato: { name: "Potato (baked)", calories: 161, protein: 4.3, carbs: 37, fat: 0.2, fiber: 3.8, serving: "1 medium (173g)", category: "vegetables", emoji: "🥔" },
  boiled_potato: { name: "Potato (boiled)", calories: 134, protein: 2.9, carbs: 31, fat: 0.1, fiber: 2.4, serving: "1 medium (167g)", category: "vegetables", emoji: "🥔" },
  mashed_potato: { name: "Mashed Potatoes", calories: 174, protein: 3.5, carbs: 24, fat: 7, fiber: 2, serving: "1 cup (210g)", category: "vegetables", emoji: "🥔" },
  sweet_potato: { name: "Sweet Potato", calories: 103, protein: 2.3, carbs: 24, fat: 0.1, fiber: 3.8, serving: "1 medium (130g)", category: "vegetables", emoji: "🍠" },
  corn: { name: "Corn on the Cob", calories: 96, protein: 3.4, carbs: 21, fat: 1.5, fiber: 2.4, serving: "1 medium ear (90g)", category: "vegetables", emoji: "🌽" },
  canned_corn: { name: "Canned Corn", calories: 132, protein: 4, carbs: 30, fat: 1.6, fiber: 3.3, serving: "1 cup (164g)", category: "vegetables", emoji: "🌽" },
  mushroom: { name: "Mushrooms (white)", calories: 21, protein: 3, carbs: 3.3, fat: 0.3, fiber: 1, serving: "1 cup sliced (70g)", category: "vegetables", emoji: "🍄" },
  shiitake: { name: "Shiitake Mushrooms", calories: 34, protein: 2.2, carbs: 7, fat: 0.5, fiber: 2.5, serving: "1 cup (97g)", category: "vegetables", emoji: "🍄" },
  portobello: { name: "Portobello Mushroom", calories: 22, protein: 2.1, carbs: 3.3, fat: 0.4, fiber: 1.3, serving: "1 cap (86g)", category: "vegetables", emoji: "🍄" },
  asparagus: { name: "Asparagus", calories: 27, protein: 3, carbs: 5, fat: 0.2, fiber: 2.8, serving: "1 cup (134g)", category: "vegetables", emoji: "🥦" },
  green_beans: { name: "Green Beans", calories: 31, protein: 1.8, carbs: 7, fat: 0.1, fiber: 2.7, serving: "1 cup (100g)", category: "vegetables", emoji: "🫛" },
  peas: { name: "Green Peas", calories: 118, protein: 8, carbs: 21, fat: 0.6, fiber: 8.3, serving: "1 cup (145g)", category: "vegetables", emoji: "🫛" },
  snap_peas: { name: "Sugar Snap Peas", calories: 26, protein: 1.8, carbs: 4.8, fat: 0.1, fiber: 1.6, serving: "1 cup (63g)", category: "vegetables", emoji: "🫛" },
  cabbage: { name: "Cabbage", calories: 22, protein: 1.3, carbs: 5.2, fat: 0.1, fiber: 2.2, serving: "1 cup shredded (89g)", category: "vegetables", emoji: "🥬" },
  red_cabbage: { name: "Red Cabbage", calories: 28, protein: 1.3, carbs: 6.6, fat: 0.2, fiber: 1.9, serving: "1 cup shredded (89g)", category: "vegetables", emoji: "🥬" },
  brussels_sprouts: { name: "Brussels Sprouts", calories: 56, protein: 4, carbs: 11, fat: 0.8, fiber: 4.1, serving: "1 cup (156g)", category: "vegetables", emoji: "🥬" },
  celery: { name: "Celery", calories: 6, protein: 0.3, carbs: 1.2, fat: 0.1, fiber: 0.6, serving: "1 stalk (40g)", category: "vegetables", emoji: "🥬" },
  artichoke: { name: "Artichoke", calories: 60, protein: 4.2, carbs: 13, fat: 0.2, fiber: 6.9, serving: "1 medium (128g)", category: "vegetables", emoji: "🥬" },
  beet: { name: "Beet", calories: 35, protein: 1.3, carbs: 8, fat: 0.1, fiber: 2.3, serving: "1 medium (82g)", category: "vegetables", emoji: "🥬" },
  radish: { name: "Radishes", calories: 19, protein: 0.8, carbs: 4, fat: 0.1, fiber: 1.9, serving: "1 cup sliced (116g)", category: "vegetables", emoji: "🥬" },
  turnip: { name: "Turnip", calories: 36, protein: 1.2, carbs: 8, fat: 0.1, fiber: 2.3, serving: "1 medium (122g)", category: "vegetables", emoji: "🥬" },
  butternut_squash: { name: "Butternut Squash", calories: 63, protein: 1.4, carbs: 16, fat: 0.1, fiber: 2.8, serving: "1 cup cubed (140g)", category: "vegetables", emoji: "🎃" },
  acorn_squash: { name: "Acorn Squash", calories: 56, protein: 1.1, carbs: 15, fat: 0.1, fiber: 2.1, serving: "1 cup cubed (140g)", category: "vegetables", emoji: "🎃" },
  pumpkin: { name: "Pumpkin", calories: 30, protein: 1.2, carbs: 7.5, fat: 0.1, fiber: 0.6, serving: "1 cup cubed (116g)", category: "vegetables", emoji: "🎃" },
  okra: { name: "Okra", calories: 33, protein: 1.9, carbs: 7, fat: 0.2, fiber: 3.2, serving: "1 cup (100g)", category: "vegetables", emoji: "🥬" },
  watercress: { name: "Watercress", calories: 4, protein: 0.8, carbs: 0.4, fat: 0, fiber: 0.2, serving: "1 cup (34g)", category: "vegetables", emoji: "🥬" },
  bok_choy: { name: "Bok Choy", calories: 9, protein: 1.1, carbs: 1.5, fat: 0.1, fiber: 0.7, serving: "1 cup (70g)", category: "vegetables", emoji: "🥬" },
  seaweed: { name: "Nori Seaweed", calories: 5, protein: 0.5, carbs: 1, fat: 0, fiber: 0.3, serving: "1 sheet (2.5g)", category: "vegetables", emoji: "🥬" },

  // ─────────────────── PROTEINS — POULTRY ───────────────────
  chicken_breast: { name: "Chicken Breast (skinless)", calories: 165, protein: 31, carbs: 0, fat: 3.6, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🍗" },
  chicken_thigh: { name: "Chicken Thigh (skin-on)", calories: 209, protein: 26, carbs: 0, fat: 10.9, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🍗" },
  chicken_wing: { name: "Chicken Wings", calories: 203, protein: 30, carbs: 0, fat: 8.1, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🍗" },
  chicken_drumstick: { name: "Chicken Drumstick", calories: 172, protein: 28, carbs: 0, fat: 5.7, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🍗" },
  chicken_nuggets: { name: "Chicken Nuggets", calories: 296, protein: 15, carbs: 18, fat: 18, fiber: 1, serving: "6 pieces (100g)", category: "protein", emoji: "🍗" },
  rotisserie_chicken: { name: "Rotisserie Chicken", calories: 190, protein: 27, carbs: 0, fat: 8.5, fiber: 0, serving: "100g", category: "protein", emoji: "🍗" },
  turkey_breast: { name: "Turkey Breast", calories: 135, protein: 30, carbs: 0, fat: 0.7, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🦃" },
  ground_turkey: { name: "Ground Turkey (93% lean)", calories: 170, protein: 21, carbs: 0, fat: 9, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🦃" },
  duck: { name: "Duck Breast", calories: 201, protein: 23.5, carbs: 0, fat: 11.2, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🦆" },

  // ─────────────────── PROTEINS — BEEF ───────────────────
  beef_steak: { name: "Beef Sirloin Steak", calories: 207, protein: 26, carbs: 0, fat: 11, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🥩" },
  ribeye: { name: "Ribeye Steak", calories: 291, protein: 24, carbs: 0, fat: 21, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🥩" },
  filet_mignon: { name: "Filet Mignon", calories: 227, protein: 26, carbs: 0, fat: 13, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🥩" },
  ground_beef_90: { name: "Ground Beef (90% lean)", calories: 196, protein: 27, carbs: 0, fat: 10, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🥩" },
  ground_beef_80: { name: "Ground Beef (80% lean)", calories: 254, protein: 26, carbs: 0, fat: 17, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🥩" },
  beef_jerky: { name: "Beef Jerky", calories: 116, protein: 9.4, carbs: 3.1, fat: 7.3, fiber: 0.5, serving: "1 oz (28g)", category: "protein", emoji: "🥩" },
  stew_beef: { name: "Beef Stew Meat", calories: 210, protein: 28, carbs: 0, fat: 10, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🥩" },
  roast_beef: { name: "Roast Beef (deli)", calories: 70, protein: 12, carbs: 0.5, fat: 2, fiber: 0, serving: "2 slices (56g)", category: "protein", emoji: "🥩" },
  corned_beef: { name: "Corned Beef", calories: 251, protein: 18, carbs: 0.5, fat: 19, fiber: 0, serving: "100g", category: "protein", emoji: "🥩" },

  // ─────────────────── PROTEINS — PORK ───────────────────
  pork_chop: { name: "Pork Chop (bone-in)", calories: 231, protein: 27, carbs: 0, fat: 13, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🥓" },
  pork_tenderloin: { name: "Pork Tenderloin", calories: 143, protein: 26, carbs: 0, fat: 3.5, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🥓" },
  pork_belly: { name: "Pork Belly", calories: 518, protein: 9.3, carbs: 0, fat: 53, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🥓" },
  bacon: { name: "Bacon", calories: 43, protein: 3, carbs: 0.1, fat: 3.3, fiber: 0, serving: "1 slice cooked (8g)", category: "protein", emoji: "🥓" },
  turkey_bacon: { name: "Turkey Bacon", calories: 30, protein: 2, carbs: 0, fat: 2.5, fiber: 0, serving: "1 slice (8g)", category: "protein", emoji: "🥓" },
  ham: { name: "Ham (sliced)", calories: 145, protein: 21, carbs: 1.5, fat: 6, fiber: 0, serving: "100g", category: "protein", emoji: "🍖" },
  prosciutto: { name: "Prosciutto", calories: 76, protein: 7.6, carbs: 0.3, fat: 5, fiber: 0, serving: "2 slices (30g)", category: "protein", emoji: "🍖" },
  sausage: { name: "Pork Sausage", calories: 301, protein: 19, carbs: 0, fat: 24, fiber: 0, serving: "1 link (100g)", category: "protein", emoji: "🌭" },
  italian_sausage: { name: "Italian Sausage", calories: 346, protein: 16, carbs: 1, fat: 31, fiber: 0, serving: "1 link (100g)", category: "protein", emoji: "🌭" },
  bratwurst: { name: "Bratwurst", calories: 283, protein: 12, carbs: 2, fat: 25, fiber: 0, serving: "1 link (85g)", category: "protein", emoji: "🌭" },
  chorizo: { name: "Chorizo", calories: 455, protein: 24, carbs: 2, fat: 38, fiber: 0, serving: "100g", category: "protein", emoji: "🌭" },
  hot_dog: { name: "Hot Dog (beef)", calories: 189, protein: 7, carbs: 2, fat: 17, fiber: 0, serving: "1 frank (57g)", category: "protein", emoji: "🌭" },
  lamb: { name: "Lamb Chop", calories: 294, protein: 25, carbs: 0, fat: 21, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🍖" },
  lamb_ground: { name: "Ground Lamb", calories: 283, protein: 24, carbs: 0, fat: 20, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🍖" },
  veal: { name: "Veal Cutlet", calories: 172, protein: 31, carbs: 0, fat: 4.8, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🍖" },
  venison: { name: "Venison", calories: 158, protein: 30, carbs: 0, fat: 3.2, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🍖" },
  bison: { name: "Bison / Buffalo", calories: 143, protein: 28, carbs: 0, fat: 2.4, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🍖" },

  // ─────────────────── PROTEINS — SEAFOOD ───────────────────
  salmon: { name: "Salmon (Atlantic)", calories: 208, protein: 20, carbs: 0, fat: 13, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🐟" },
  smoked_salmon: { name: "Smoked Salmon", calories: 117, protein: 18, carbs: 0, fat: 4.3, fiber: 0, serving: "100g", category: "protein", emoji: "🐟" },
  tuna: { name: "Tuna (canned, in water)", calories: 116, protein: 26, carbs: 0, fat: 0.8, fiber: 0, serving: "1 can drained (100g)", category: "protein", emoji: "🐟" },
  tuna_steak: { name: "Tuna Steak", calories: 132, protein: 29, carbs: 0, fat: 1, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🐟" },
  cod: { name: "Cod", calories: 82, protein: 18, carbs: 0, fat: 0.7, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🐟" },
  tilapia: { name: "Tilapia", calories: 128, protein: 26, carbs: 0, fat: 2.7, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🐟" },
  halibut: { name: "Halibut", calories: 111, protein: 23, carbs: 0, fat: 1.6, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🐟" },
  trout: { name: "Rainbow Trout", calories: 190, protein: 27, carbs: 0, fat: 8.5, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🐟" },
  sardines: { name: "Sardines (canned, oil)", calories: 208, protein: 25, carbs: 0, fat: 11, fiber: 0, serving: "1 can (92g)", category: "protein", emoji: "🐟" },
  mackerel: { name: "Mackerel", calories: 262, protein: 24, carbs: 0, fat: 18, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🐟" },
  shrimp: { name: "Shrimp", calories: 99, protein: 24, carbs: 0.2, fat: 0.3, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🦐" },
  crab: { name: "Crab Meat", calories: 97, protein: 19, carbs: 0, fat: 1.5, fiber: 0, serving: "100g", category: "protein", emoji: "🦀" },
  lobster: { name: "Lobster", calories: 89, protein: 19, carbs: 0, fat: 0.9, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🦞" },
  scallops: { name: "Scallops", calories: 111, protein: 21, carbs: 3, fat: 1, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🦐" },
  mussels: { name: "Mussels", calories: 172, protein: 24, carbs: 7, fat: 4.5, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🦐" },
  oysters: { name: "Oysters", calories: 81, protein: 9.5, carbs: 5, fat: 2.5, fiber: 0, serving: "6 medium (84g)", category: "protein", emoji: "🦪" },
  calamari: { name: "Calamari (fried)", calories: 175, protein: 18, carbs: 7.8, fat: 7.5, fiber: 0, serving: "100g", category: "protein", emoji: "🦑" },
  fish_sticks: { name: "Fish Sticks (frozen)", calories: 224, protein: 12, carbs: 20, fat: 11, fiber: 0.5, serving: "4 sticks (112g)", category: "protein", emoji: "🐟" },
  surimi: { name: "Crab Stick / Surimi", calories: 95, protein: 7, carbs: 15, fat: 0.4, fiber: 0, serving: "100g", category: "protein", emoji: "🦀" },

  // ─────────────────── PROTEINS — EGGS ───────────────────
  egg: { name: "Whole Egg", calories: 78, protein: 6, carbs: 0.6, fat: 5, fiber: 0, serving: "1 large (50g)", category: "protein", emoji: "🥚" },
  egg_white: { name: "Egg White", calories: 17, protein: 3.6, carbs: 0.2, fat: 0.1, fiber: 0, serving: "1 large", category: "protein", emoji: "🥚" },
  egg_yolk: { name: "Egg Yolk", calories: 55, protein: 2.7, carbs: 0.6, fat: 4.5, fiber: 0, serving: "1 large", category: "protein", emoji: "🥚" },
  boiled_egg: { name: "Hard-Boiled Egg", calories: 78, protein: 6.3, carbs: 0.6, fat: 5.3, fiber: 0, serving: "1 large (50g)", category: "protein", emoji: "🥚" },
  scrambled_eggs: { name: "Scrambled Eggs", calories: 147, protein: 10, carbs: 1.6, fat: 11, fiber: 0, serving: "2 eggs (122g)", category: "protein", emoji: "🥚" },
  fried_egg: { name: "Fried Egg", calories: 90, protein: 6.3, carbs: 0.4, fat: 7, fiber: 0, serving: "1 large", category: "protein", emoji: "🍳" },
  omelette: { name: "Cheese Omelette", calories: 252, protein: 16, carbs: 1.5, fat: 20, fiber: 0, serving: "2-egg omelette", category: "protein", emoji: "🍳" },
  quail_egg: { name: "Quail Egg", calories: 14, protein: 1, carbs: 0, fat: 1, fiber: 0, serving: "1 egg (9g)", category: "protein", emoji: "🥚" },

  // ─────────────────── PROTEINS — PLANT-BASED ───────────────────
  tofu: { name: "Tofu (firm)", calories: 144, protein: 17, carbs: 3.5, fat: 8.7, fiber: 2.3, serving: "1/2 block (126g)", category: "protein", emoji: "🧈" },
  silken_tofu: { name: "Tofu (silken)", calories: 55, protein: 5, carbs: 2.2, fat: 2.7, fiber: 0, serving: "100g", category: "protein", emoji: "🧈" },
  tempeh: { name: "Tempeh", calories: 193, protein: 19, carbs: 9.4, fat: 11, fiber: 0, serving: "100g", category: "protein", emoji: "🧈" },
  seitan: { name: "Seitan", calories: 126, protein: 21, carbs: 5, fat: 1.9, fiber: 0.6, serving: "100g", category: "protein", emoji: "🧈" },
  beyond_burger: { name: "Beyond Burger (plant)", calories: 230, protein: 20, carbs: 5, fat: 14, fiber: 2, serving: "1 patty (113g)", category: "protein", emoji: "🍔" },
  protein_powder_whey: { name: "Whey Protein Powder", calories: 120, protein: 24, carbs: 3, fat: 1, fiber: 0, serving: "1 scoop (30g)", category: "protein", emoji: "🥤" },
  protein_powder_plant: { name: "Plant Protein Powder", calories: 110, protein: 21, carbs: 5, fat: 1.5, fiber: 2, serving: "1 scoop (33g)", category: "protein", emoji: "🥤" },

  // ─────────────────── GRAINS & CARBS ───────────────────
  rice: { name: "White Rice", calories: 206, protein: 4.3, carbs: 45, fat: 0.4, fiber: 0.6, serving: "1 cup cooked (158g)", category: "grains", emoji: "🍚" },
  brown_rice: { name: "Brown Rice", calories: 216, protein: 5, carbs: 45, fat: 1.8, fiber: 3.5, serving: "1 cup cooked (195g)", category: "grains", emoji: "🍚" },
  basmati_rice: { name: "Basmati Rice", calories: 210, protein: 4.4, carbs: 46, fat: 0.5, fiber: 0.7, serving: "1 cup cooked (163g)", category: "grains", emoji: "🍚" },
  wild_rice: { name: "Wild Rice", calories: 166, protein: 6.5, carbs: 35, fat: 0.6, fiber: 3, serving: "1 cup cooked (164g)", category: "grains", emoji: "🍚" },
  sushi_rice: { name: "Sushi Rice (seasoned)", calories: 240, protein: 4, carbs: 53, fat: 0.4, fiber: 0.5, serving: "1 cup (186g)", category: "grains", emoji: "🍚" },
  quinoa: { name: "Quinoa", calories: 222, protein: 8, carbs: 39, fat: 3.6, fiber: 5.2, serving: "1 cup cooked (185g)", category: "grains", emoji: "🌾" },
  oatmeal: { name: "Oatmeal (cooked)", calories: 154, protein: 5, carbs: 27, fat: 2.6, fiber: 4, serving: "1 cup (234g)", category: "grains", emoji: "🥣" },
  overnight_oats: { name: "Overnight Oats", calories: 210, protein: 7, carbs: 35, fat: 5, fiber: 4.5, serving: "1 cup", category: "grains", emoji: "🥣" },
  granola: { name: "Granola", calories: 212, protein: 5, carbs: 34, fat: 7, fiber: 3, serving: "1/2 cup (55g)", category: "grains", emoji: "🥣" },
  muesli: { name: "Muesli", calories: 289, protein: 8, carbs: 56, fat: 5, fiber: 6, serving: "3/4 cup (80g)", category: "grains", emoji: "🥣" },
  pasta: { name: "Pasta (spaghetti)", calories: 220, protein: 8, carbs: 43, fat: 1.3, fiber: 2.5, serving: "1 cup cooked (140g)", category: "grains", emoji: "🍝" },
  whole_wheat_pasta: { name: "Whole Wheat Pasta", calories: 174, protein: 7.5, carbs: 37, fat: 0.8, fiber: 6.3, serving: "1 cup cooked (140g)", category: "grains", emoji: "🍝" },
  penne: { name: "Penne Pasta", calories: 220, protein: 8, carbs: 43, fat: 1.3, fiber: 2.5, serving: "1 cup cooked (140g)", category: "grains", emoji: "🍝" },
  ramen_noodles: { name: "Ramen Noodles (instant)", calories: 188, protein: 5, carbs: 27, fat: 7, fiber: 1, serving: "1/2 block (43g)", category: "grains", emoji: "🍜" },
  rice_noodles: { name: "Rice Noodles", calories: 192, protein: 1.6, carbs: 44, fat: 0.4, fiber: 1.8, serving: "1 cup cooked (176g)", category: "grains", emoji: "🍜" },
  egg_noodles: { name: "Egg Noodles", calories: 221, protein: 7, carbs: 40, fat: 3.3, fiber: 1.8, serving: "1 cup cooked (160g)", category: "grains", emoji: "🍜" },
  couscous: { name: "Couscous", calories: 176, protein: 6, carbs: 36, fat: 0.3, fiber: 2.2, serving: "1 cup cooked (157g)", category: "grains", emoji: "🌾" },
  bulgur: { name: "Bulgur Wheat", calories: 151, protein: 5.6, carbs: 34, fat: 0.4, fiber: 8.2, serving: "1 cup cooked (182g)", category: "grains", emoji: "🌾" },
  barley: { name: "Barley (pearled)", calories: 193, protein: 3.5, carbs: 44, fat: 0.7, fiber: 6, serving: "1 cup cooked (157g)", category: "grains", emoji: "🌾" },
  polenta: { name: "Polenta / Grits", calories: 143, protein: 3.4, carbs: 31, fat: 0.5, fiber: 1.6, serving: "1 cup cooked (233g)", category: "grains", emoji: "🌾" },
  bread: { name: "Whole Wheat Bread", calories: 69, protein: 3.6, carbs: 12, fat: 1, fiber: 1.9, serving: "1 slice (28g)", category: "grains", emoji: "🍞" },
  white_bread: { name: "White Bread", calories: 67, protein: 2.3, carbs: 13, fat: 0.9, fiber: 0.6, serving: "1 slice (25g)", category: "grains", emoji: "🍞" },
  sourdough: { name: "Sourdough Bread", calories: 93, protein: 3.8, carbs: 18, fat: 0.6, fiber: 0.9, serving: "1 slice (36g)", category: "grains", emoji: "🍞" },
  rye_bread: { name: "Rye Bread", calories: 83, protein: 2.7, carbs: 16, fat: 1, fiber: 1.9, serving: "1 slice (32g)", category: "grains", emoji: "🍞" },
  baguette: { name: "Baguette", calories: 132, protein: 4, carbs: 26, fat: 1.6, fiber: 1.2, serving: "1 piece (50g)", category: "grains", emoji: "🥖" },
  bagel: { name: "Bagel (plain)", calories: 245, protein: 10, carbs: 48, fat: 1.5, fiber: 2.1, serving: "1 medium (98g)", category: "grains", emoji: "🥯" },
  croissant: { name: "Croissant", calories: 231, protein: 4.7, carbs: 26, fat: 12, fiber: 1.5, serving: "1 medium (57g)", category: "grains", emoji: "🥐" },
  english_muffin: { name: "English Muffin", calories: 132, protein: 4.4, carbs: 26, fat: 1, fiber: 1.5, serving: "1 muffin (57g)", category: "grains", emoji: "🍞" },
  pita: { name: "Pita Bread", calories: 165, protein: 5.5, carbs: 33, fat: 0.7, fiber: 1.3, serving: "1 large (60g)", category: "grains", emoji: "🫓" },
  naan: { name: "Naan Bread", calories: 262, protein: 9, carbs: 45, fat: 5, fiber: 2, serving: "1 piece (90g)", category: "grains", emoji: "🫓" },
  tortilla_flour: { name: "Flour Tortilla", calories: 144, protein: 4, carbs: 24, fat: 3.7, fiber: 1.6, serving: "1 medium (45g)", category: "grains", emoji: "🫓" },
  tortilla_corn: { name: "Corn Tortilla", calories: 52, protein: 1.4, carbs: 11, fat: 0.7, fiber: 1.5, serving: "1 small (26g)", category: "grains", emoji: "🫓" },
  wrap: { name: "Wrap / Flatbread", calories: 190, protein: 5, carbs: 33, fat: 4.5, fiber: 2, serving: "1 large (64g)", category: "grains", emoji: "🫓" },
  pancake: { name: "Pancake", calories: 86, protein: 2.5, carbs: 11, fat: 3.7, fiber: 0.3, serving: "1 medium (38g)", category: "grains", emoji: "🥞" },
  waffle: { name: "Waffle (frozen)", calories: 95, protein: 2, carbs: 15, fat: 3, fiber: 0.5, serving: "1 waffle (35g)", category: "grains", emoji: "🧇" },
  french_toast: { name: "French Toast", calories: 149, protein: 5, carbs: 16, fat: 7, fiber: 0.6, serving: "1 slice (65g)", category: "grains", emoji: "🍞" },
  corn_flakes: { name: "Corn Flakes", calories: 100, protein: 2, carbs: 24, fat: 0, fiber: 0.3, serving: "1 cup (28g)", category: "grains", emoji: "🥣" },
  cheerios: { name: "Cheerios (whole grain)", calories: 100, protein: 3, carbs: 20, fat: 2, fiber: 3, serving: "1 cup (28g)", category: "grains", emoji: "🥣" },
  rice_cake: { name: "Rice Cake", calories: 35, protein: 0.7, carbs: 7.3, fat: 0.3, fiber: 0.4, serving: "1 cake (9g)", category: "grains", emoji: "🍘" },
  cracker: { name: "Whole Wheat Crackers", calories: 62, protein: 1, carbs: 10, fat: 2.2, fiber: 0.5, serving: "4 crackers (16g)", category: "grains", emoji: "🍘" },

  // ─────────────────── DAIRY ───────────────────
  milk: { name: "Whole Milk", calories: 149, protein: 8, carbs: 12, fat: 8, fiber: 0, serving: "1 cup (244ml)", category: "dairy", emoji: "🥛" },
  milk_2: { name: "2% Milk", calories: 122, protein: 8, carbs: 12, fat: 4.8, fiber: 0, serving: "1 cup (244ml)", category: "dairy", emoji: "🥛" },
  skim_milk: { name: "Skim Milk", calories: 83, protein: 8.3, carbs: 12, fat: 0.2, fiber: 0, serving: "1 cup (245ml)", category: "dairy", emoji: "🥛" },
  almond_milk: { name: "Almond Milk (unsweetened)", calories: 30, protein: 1, carbs: 1, fat: 2.5, fiber: 0.5, serving: "1 cup (240ml)", category: "dairy", emoji: "🥛" },
  oat_milk: { name: "Oat Milk", calories: 120, protein: 3, carbs: 16, fat: 5, fiber: 2, serving: "1 cup (240ml)", category: "dairy", emoji: "🥛" },
  soy_milk: { name: "Soy Milk", calories: 80, protein: 7, carbs: 4, fat: 4, fiber: 1, serving: "1 cup (240ml)", category: "dairy", emoji: "🥛" },
  coconut_milk: { name: "Coconut Milk (carton)", calories: 45, protein: 0, carbs: 1, fat: 4.5, fiber: 0, serving: "1 cup (240ml)", category: "dairy", emoji: "🥥" },
  coconut_milk_can: { name: "Coconut Milk (canned)", calories: 445, protein: 4.6, carbs: 6, fat: 48, fiber: 0, serving: "1 cup (240ml)", category: "dairy", emoji: "🥥" },
  heavy_cream: { name: "Heavy Cream", calories: 51, protein: 0.4, carbs: 0.4, fat: 5.4, fiber: 0, serving: "1 tbsp (15ml)", category: "dairy", emoji: "🥛" },
  whipped_cream: { name: "Whipped Cream", calories: 15, protein: 0.2, carbs: 0.6, fat: 1.3, fiber: 0, serving: "1 tbsp (4g)", category: "dairy", emoji: "🥛" },
  greek_yogurt: { name: "Greek Yogurt (plain, 0%)", calories: 100, protein: 17, carbs: 6, fat: 0.7, fiber: 0, serving: "170g container", category: "dairy", emoji: "🥛" },
  yogurt: { name: "Plain Yogurt", calories: 149, protein: 8.5, carbs: 11, fat: 8, fiber: 0, serving: "1 cup (245g)", category: "dairy", emoji: "🥛" },
  yogurt_fruit: { name: "Fruit Yogurt", calories: 170, protein: 5, carbs: 33, fat: 1.5, fiber: 0, serving: "170g container", category: "dairy", emoji: "🥛" },
  skyr: { name: "Skyr (Icelandic)", calories: 110, protein: 19, carbs: 7, fat: 0.5, fiber: 0, serving: "170g", category: "dairy", emoji: "🥛" },
  kefir: { name: "Kefir", calories: 104, protein: 9, carbs: 12, fat: 2.5, fiber: 0, serving: "1 cup (240ml)", category: "dairy", emoji: "🥛" },
  cheddar: { name: "Cheddar Cheese", calories: 113, protein: 7, carbs: 0.4, fat: 9.3, fiber: 0, serving: "1 oz (28g)", category: "dairy", emoji: "🧀" },
  mozzarella: { name: "Mozzarella", calories: 85, protein: 6.3, carbs: 0.6, fat: 6.3, fiber: 0, serving: "1 oz (28g)", category: "dairy", emoji: "🧀" },
  mozzarella_fresh: { name: "Fresh Mozzarella", calories: 70, protein: 5, carbs: 1, fat: 5, fiber: 0, serving: "1 oz (28g)", category: "dairy", emoji: "🧀" },
  parmesan: { name: "Parmesan", calories: 110, protein: 10, carbs: 0.9, fat: 7.3, fiber: 0, serving: "1 oz (28g)", category: "dairy", emoji: "🧀" },
  swiss: { name: "Swiss Cheese", calories: 106, protein: 7.5, carbs: 1.5, fat: 7.8, fiber: 0, serving: "1 oz (28g)", category: "dairy", emoji: "🧀" },
  brie: { name: "Brie", calories: 95, protein: 6, carbs: 0.1, fat: 8, fiber: 0, serving: "1 oz (28g)", category: "dairy", emoji: "🧀" },
  gouda: { name: "Gouda", calories: 101, protein: 7, carbs: 0.6, fat: 7.8, fiber: 0, serving: "1 oz (28g)", category: "dairy", emoji: "🧀" },
  feta: { name: "Feta Cheese", calories: 75, protein: 4, carbs: 1.2, fat: 6, fiber: 0, serving: "1 oz (28g)", category: "dairy", emoji: "🧀" },
  goat_cheese: { name: "Goat Cheese", calories: 75, protein: 5, carbs: 0, fat: 6, fiber: 0, serving: "1 oz (28g)", category: "dairy", emoji: "🧀" },
  cream_cheese: { name: "Cream Cheese", calories: 99, protein: 1.7, carbs: 1.6, fat: 9.9, fiber: 0, serving: "1 oz (28g)", category: "dairy", emoji: "🧀" },
  cottage_cheese: { name: "Cottage Cheese (2%)", calories: 92, protein: 12, carbs: 5, fat: 2.6, fiber: 0, serving: "1/2 cup (113g)", category: "dairy", emoji: "🧀" },
  ricotta: { name: "Ricotta Cheese", calories: 171, protein: 14, carbs: 6, fat: 10, fiber: 0, serving: "1/2 cup (124g)", category: "dairy", emoji: "🧀" },
  string_cheese: { name: "String Cheese", calories: 80, protein: 7, carbs: 1, fat: 5, fiber: 0, serving: "1 stick (28g)", category: "dairy", emoji: "🧀" },
  butter: { name: "Butter", calories: 102, protein: 0.1, carbs: 0, fat: 11.5, fiber: 0, serving: "1 tbsp (14g)", category: "dairy", emoji: "🧈" },
  ghee: { name: "Ghee (clarified butter)", calories: 112, protein: 0, carbs: 0, fat: 12.7, fiber: 0, serving: "1 tbsp (13g)", category: "dairy", emoji: "🧈" },
  sour_cream: { name: "Sour Cream", calories: 23, protein: 0.3, carbs: 0.5, fat: 2.4, fiber: 0, serving: "1 tbsp (12g)", category: "dairy", emoji: "🥛" },
  ice_cream: { name: "Vanilla Ice Cream", calories: 207, protein: 3.5, carbs: 24, fat: 11, fiber: 0.5, serving: "1/2 cup (66g)", category: "dairy", emoji: "🍨" },
  chocolate_ice_cream: { name: "Chocolate Ice Cream", calories: 216, protein: 3.8, carbs: 28, fat: 11, fiber: 1.2, serving: "1/2 cup (66g)", category: "dairy", emoji: "🍨" },
  frozen_yogurt: { name: "Frozen Yogurt", calories: 114, protein: 3, carbs: 22, fat: 1.5, fiber: 0, serving: "1/2 cup (72g)", category: "dairy", emoji: "🍨" },

  // ─────────────────── NUTS & SEEDS ───────────────────
  almonds: { name: "Almonds", calories: 164, protein: 6, carbs: 6, fat: 14, fiber: 3.5, serving: "1 oz (28g, ~23 nuts)", category: "nuts", emoji: "🥜" },
  walnuts: { name: "Walnuts", calories: 185, protein: 4.3, carbs: 3.9, fat: 18.5, fiber: 1.9, serving: "1 oz (28g)", category: "nuts", emoji: "🥜" },
  cashews: { name: "Cashews", calories: 157, protein: 5.2, carbs: 8.6, fat: 12.4, fiber: 0.9, serving: "1 oz (28g)", category: "nuts", emoji: "🥜" },
  pecans: { name: "Pecans", calories: 196, protein: 2.6, carbs: 3.9, fat: 20, fiber: 2.7, serving: "1 oz (28g)", category: "nuts", emoji: "🥜" },
  pistachios: { name: "Pistachios", calories: 159, protein: 5.7, carbs: 7.7, fat: 12.9, fiber: 3, serving: "1 oz (28g)", category: "nuts", emoji: "🥜" },
  macadamia: { name: "Macadamia Nuts", calories: 204, protein: 2.2, carbs: 3.9, fat: 21.5, fiber: 2.4, serving: "1 oz (28g)", category: "nuts", emoji: "🥜" },
  brazil_nuts: { name: "Brazil Nuts", calories: 187, protein: 4, carbs: 3.3, fat: 19, fiber: 2.1, serving: "1 oz (28g)", category: "nuts", emoji: "🥜" },
  hazelnuts: { name: "Hazelnuts", calories: 178, protein: 4.2, carbs: 4.7, fat: 17, fiber: 2.7, serving: "1 oz (28g)", category: "nuts", emoji: "🥜" },
  peanuts: { name: "Peanuts (roasted)", calories: 161, protein: 7.3, carbs: 4.6, fat: 14, fiber: 2.4, serving: "1 oz (28g)", category: "nuts", emoji: "🥜" },
  peanut_butter: { name: "Peanut Butter", calories: 188, protein: 7, carbs: 6, fat: 16, fiber: 2, serving: "2 tbsp (32g)", category: "nuts", emoji: "🥜" },
  almond_butter: { name: "Almond Butter", calories: 196, protein: 6.8, carbs: 6, fat: 18, fiber: 3.3, serving: "2 tbsp (32g)", category: "nuts", emoji: "🥜" },
  tahini: { name: "Tahini (sesame paste)", calories: 89, protein: 2.6, carbs: 3.2, fat: 8, fiber: 0.7, serving: "1 tbsp (15g)", category: "nuts", emoji: "🥜" },
  chia_seeds: { name: "Chia Seeds", calories: 138, protein: 4.7, carbs: 12, fat: 8.7, fiber: 9.8, serving: "1 oz (28g)", category: "nuts", emoji: "🌱" },
  flax_seeds: { name: "Flax Seeds (ground)", calories: 37, protein: 1.3, carbs: 2, fat: 3, fiber: 1.9, serving: "1 tbsp (7g)", category: "nuts", emoji: "🌱" },
  sunflower_seeds: { name: "Sunflower Seeds", calories: 165, protein: 5.5, carbs: 6.8, fat: 14.1, fiber: 2.4, serving: "1 oz (28g)", category: "nuts", emoji: "🌻" },
  pumpkin_seeds: { name: "Pumpkin Seeds", calories: 151, protein: 7, carbs: 5, fat: 13, fiber: 1.1, serving: "1 oz (28g)", category: "nuts", emoji: "🎃" },
  hemp_seeds: { name: "Hemp Seeds", calories: 166, protein: 9.5, carbs: 2.6, fat: 14.6, fiber: 1.2, serving: "3 tbsp (30g)", category: "nuts", emoji: "🌱" },
  sesame_seeds: { name: "Sesame Seeds", calories: 52, protein: 1.6, carbs: 2.1, fat: 4.5, fiber: 1.1, serving: "1 tbsp (9g)", category: "nuts", emoji: "🌱" },
  mixed_nuts: { name: "Mixed Nuts", calories: 172, protein: 5, carbs: 7, fat: 15, fiber: 2, serving: "1 oz (28g)", category: "nuts", emoji: "🥜" },
  trail_mix: { name: "Trail Mix", calories: 137, protein: 3.5, carbs: 13, fat: 9, fiber: 1.5, serving: "1 oz (28g)", category: "nuts", emoji: "🥜" },

  // ─────────────────── LEGUMES ───────────────────
  black_beans: { name: "Black Beans (cooked)", calories: 227, protein: 15, carbs: 41, fat: 0.9, fiber: 15, serving: "1 cup (172g)", category: "legumes", emoji: "🫘" },
  kidney_beans: { name: "Kidney Beans", calories: 225, protein: 15, carbs: 40, fat: 0.9, fiber: 11, serving: "1 cup (177g)", category: "legumes", emoji: "🫘" },
  pinto_beans: { name: "Pinto Beans", calories: 245, protein: 15, carbs: 45, fat: 1.1, fiber: 15, serving: "1 cup (171g)", category: "legumes", emoji: "🫘" },
  white_beans: { name: "White / Cannellini Beans", calories: 225, protein: 16, carbs: 40, fat: 0.6, fiber: 11, serving: "1 cup (179g)", category: "legumes", emoji: "🫘" },
  navy_beans: { name: "Navy Beans", calories: 255, protein: 15, carbs: 47, fat: 1, fiber: 19, serving: "1 cup (182g)", category: "legumes", emoji: "🫘" },
  chickpeas: { name: "Chickpeas / Garbanzo", calories: 269, protein: 14.5, carbs: 45, fat: 4.2, fiber: 12.5, serving: "1 cup (164g)", category: "legumes", emoji: "🫘" },
  lentils: { name: "Lentils (cooked)", calories: 230, protein: 18, carbs: 40, fat: 0.8, fiber: 16, serving: "1 cup (198g)", category: "legumes", emoji: "🫘" },
  red_lentils: { name: "Red Lentils (cooked)", calories: 230, protein: 18, carbs: 40, fat: 0.8, fiber: 16, serving: "1 cup (198g)", category: "legumes", emoji: "🫘" },
  split_peas: { name: "Split Peas (cooked)", calories: 231, protein: 16, carbs: 41, fat: 0.8, fiber: 16, serving: "1 cup (196g)", category: "legumes", emoji: "🫛" },
  hummus: { name: "Hummus", calories: 166, protein: 8, carbs: 14, fat: 10, fiber: 6, serving: "1/3 cup (80g)", category: "legumes", emoji: "🫘" },
  edamame: { name: "Edamame", calories: 188, protein: 18.5, carbs: 14, fat: 8, fiber: 8, serving: "1 cup shelled (155g)", category: "legumes", emoji: "🫛" },
  baked_beans: { name: "Baked Beans (canned)", calories: 239, protein: 12, carbs: 54, fat: 1.1, fiber: 10, serving: "1 cup (254g)", category: "legumes", emoji: "🫘" },
  refried_beans: { name: "Refried Beans", calories: 201, protein: 12, carbs: 33, fat: 3.5, fiber: 10, serving: "1 cup (252g)", category: "legumes", emoji: "🫘" },
  falafel: { name: "Falafel", calories: 57, protein: 2.3, carbs: 5, fat: 3, fiber: 1, serving: "1 patty (17g)", category: "legumes", emoji: "🧆" },

  // ─────────────────── PREPARED / FAST FOOD ───────────────────
  pizza_cheese: { name: "Cheese Pizza", calories: 272, protein: 12, carbs: 34, fat: 10, fiber: 2.3, serving: "1 slice (107g)", category: "prepared", emoji: "🍕" },
  pizza_pepperoni: { name: "Pepperoni Pizza", calories: 298, protein: 13, carbs: 33, fat: 13, fiber: 2.3, serving: "1 slice (113g)", category: "prepared", emoji: "🍕" },
  pizza_margherita: { name: "Margherita Pizza", calories: 250, protein: 11, carbs: 32, fat: 9, fiber: 1.8, serving: "1 slice (107g)", category: "prepared", emoji: "🍕" },
  burger: { name: "Hamburger (single)", calories: 354, protein: 20, carbs: 29, fat: 17, fiber: 1.3, serving: "1 burger (110g)", category: "prepared", emoji: "🍔" },
  cheeseburger: { name: "Cheeseburger", calories: 410, protein: 23, carbs: 30, fat: 22, fiber: 1.5, serving: "1 burger (130g)", category: "prepared", emoji: "🍔" },
  sandwich: { name: "Turkey Sandwich", calories: 346, protein: 24, carbs: 35, fat: 13, fiber: 3, serving: "1 sandwich", category: "prepared", emoji: "🥪" },
  grilled_cheese: { name: "Grilled Cheese", calories: 366, protein: 14, carbs: 28, fat: 23, fiber: 1, serving: "1 sandwich", category: "prepared", emoji: "🥪" },
  club_sandwich: { name: "Club Sandwich", calories: 462, protein: 30, carbs: 36, fat: 22, fiber: 2, serving: "1 sandwich", category: "prepared", emoji: "🥪" },
  blt: { name: "BLT Sandwich", calories: 344, protein: 12, carbs: 29, fat: 20, fiber: 2, serving: "1 sandwich", category: "prepared", emoji: "🥪" },
  burrito: { name: "Chicken Burrito", calories: 440, protein: 28, carbs: 50, fat: 14, fiber: 6, serving: "1 medium", category: "prepared", emoji: "🌯" },
  burrito_bowl: { name: "Burrito Bowl", calories: 510, protein: 32, carbs: 55, fat: 18, fiber: 10, serving: "1 bowl", category: "prepared", emoji: "🌯" },
  taco: { name: "Beef Taco", calories: 156, protein: 8, carbs: 14, fat: 7, fiber: 2, serving: "1 taco", category: "prepared", emoji: "🌮" },
  fish_taco: { name: "Fish Taco", calories: 180, protein: 12, carbs: 16, fat: 8, fiber: 1, serving: "1 taco", category: "prepared", emoji: "🌮" },
  quesadilla: { name: "Cheese Quesadilla", calories: 349, protein: 14, carbs: 33, fat: 18, fiber: 2, serving: "1 medium", category: "prepared", emoji: "🫓" },
  nachos: { name: "Nachos with Cheese", calories: 346, protein: 9, carbs: 36, fat: 19, fiber: 3, serving: "1 serving (100g)", category: "prepared", emoji: "🧀" },
  sushi_roll: { name: "California Roll", calories: 255, protein: 9, carbs: 38, fat: 7, fiber: 3.6, serving: "6 pieces", category: "prepared", emoji: "🍣" },
  salmon_sushi: { name: "Salmon Nigiri", calories: 48, protein: 3, carbs: 6, fat: 1, fiber: 0, serving: "1 piece", category: "prepared", emoji: "🍣" },
  miso_soup: { name: "Miso Soup", calories: 40, protein: 3, carbs: 5, fat: 1, fiber: 0.5, serving: "1 cup (240ml)", category: "prepared", emoji: "🍜" },
  ramen: { name: "Ramen (pork broth)", calories: 436, protein: 18, carbs: 60, fat: 14, fiber: 2, serving: "1 bowl (500ml)", category: "prepared", emoji: "🍜" },
  pho: { name: "Pho (beef)", calories: 350, protein: 24, carbs: 40, fat: 8, fiber: 1, serving: "1 bowl (500ml)", category: "prepared", emoji: "🍜" },
  fried_rice: { name: "Fried Rice", calories: 238, protein: 5.5, carbs: 35, fat: 8.5, fiber: 1.5, serving: "1 cup (198g)", category: "prepared", emoji: "🍚" },
  pad_thai: { name: "Pad Thai", calories: 380, protein: 14, carbs: 50, fat: 14, fiber: 2, serving: "1 cup (200g)", category: "prepared", emoji: "🍜" },
  chicken_tikka: { name: "Chicken Tikka Masala", calories: 240, protein: 18, carbs: 12, fat: 14, fiber: 2, serving: "1 cup (200g)", category: "prepared", emoji: "🍛" },
  dal: { name: "Dal (lentil curry)", calories: 180, protein: 9, carbs: 28, fat: 4, fiber: 8, serving: "1 cup (200g)", category: "prepared", emoji: "🍛" },
  soup_chicken_noodle: { name: "Chicken Noodle Soup", calories: 62, protein: 4, carbs: 7, fat: 2.4, fiber: 0.7, serving: "1 cup (241g)", category: "prepared", emoji: "🍲" },
  soup_tomato: { name: "Tomato Soup", calories: 74, protein: 1.3, carbs: 16, fat: 0.5, fiber: 1.5, serving: "1 cup (248g)", category: "prepared", emoji: "🍲" },
  soup_minestrone: { name: "Minestrone", calories: 82, protein: 4, carbs: 11, fat: 2.8, fiber: 4.5, serving: "1 cup (241g)", category: "prepared", emoji: "🍲" },
  chili_con_carne: { name: "Chili con Carne", calories: 264, protein: 20, carbs: 22, fat: 11, fiber: 6, serving: "1 cup (253g)", category: "prepared", emoji: "🍲" },
  mac_and_cheese: { name: "Mac & Cheese", calories: 310, protein: 11, carbs: 38, fat: 13, fiber: 1.5, serving: "1 cup (200g)", category: "prepared", emoji: "🧀" },
  lasagna: { name: "Lasagna (meat)", calories: 284, protein: 16, carbs: 22, fat: 14, fiber: 1.8, serving: "1 piece (200g)", category: "prepared", emoji: "🍝" },
  chicken_fried_rice: { name: "Chicken Fried Rice", calories: 310, protein: 14, carbs: 40, fat: 10, fiber: 1.5, serving: "1 cup (200g)", category: "prepared", emoji: "🍚" },
  steak_frites: { name: "Steak Frites", calories: 580, protein: 32, carbs: 45, fat: 28, fiber: 4, serving: "1 plate", category: "prepared", emoji: "🥩" },
  fish_and_chips: { name: "Fish & Chips", calories: 585, protein: 22, carbs: 52, fat: 32, fiber: 4, serving: "1 plate", category: "prepared", emoji: "🐟" },
  salad: { name: "Garden Salad (no dressing)", calories: 35, protein: 2, carbs: 7, fat: 0.3, fiber: 2.5, serving: "2 cups (104g)", category: "prepared", emoji: "🥗" },
  caesar_salad: { name: "Caesar Salad (with dressing)", calories: 184, protein: 8, carbs: 9, fat: 13, fiber: 2, serving: "1.5 cups", category: "prepared", emoji: "🥗" },
  greek_salad: { name: "Greek Salad", calories: 153, protein: 5, carbs: 8, fat: 12, fiber: 2.5, serving: "1.5 cups", category: "prepared", emoji: "🥗" },
  cobb_salad: { name: "Cobb Salad", calories: 350, protein: 26, carbs: 10, fat: 24, fiber: 3, serving: "1 plate", category: "prepared", emoji: "🥗" },
  french_fries: { name: "French Fries", calories: 312, protein: 3.4, carbs: 41, fat: 15, fiber: 3.8, serving: "medium (117g)", category: "prepared", emoji: "🍟" },
  sweet_potato_fries: { name: "Sweet Potato Fries", calories: 260, protein: 2, carbs: 38, fat: 12, fiber: 3, serving: "medium (100g)", category: "prepared", emoji: "🍟" },
  onion_rings: { name: "Onion Rings", calories: 276, protein: 4, carbs: 31, fat: 16, fiber: 1, serving: "6 rings (90g)", category: "prepared", emoji: "🍟" },
  mozzarella_sticks: { name: "Mozzarella Sticks", calories: 268, protein: 12, carbs: 20, fat: 16, fiber: 1, serving: "3 sticks (84g)", category: "prepared", emoji: "🧀" },
  spring_roll: { name: "Spring Roll (fried)", calories: 100, protein: 3, carbs: 13, fat: 4, fiber: 1, serving: "1 roll (64g)", category: "prepared", emoji: "🥟" },
  dumpling: { name: "Dumpling / Gyoza (pork)", calories: 41, protein: 1.9, carbs: 4.3, fat: 1.8, fiber: 0.2, serving: "1 piece (16g)", category: "prepared", emoji: "🥟" },
  empanada: { name: "Empanada (beef)", calories: 280, protein: 10, carbs: 24, fat: 16, fiber: 1, serving: "1 piece (100g)", category: "prepared", emoji: "🥟" },
  samosa: { name: "Samosa (vegetable)", calories: 130, protein: 3, carbs: 16, fat: 6, fiber: 2, serving: "1 piece (70g)", category: "prepared", emoji: "🥟" },
  kebab: { name: "Chicken Kebab", calories: 220, protein: 28, carbs: 5, fat: 10, fiber: 1, serving: "1 skewer (150g)", category: "prepared", emoji: "🍢" },
  shawarma: { name: "Chicken Shawarma", calories: 420, protein: 30, carbs: 40, fat: 16, fiber: 3, serving: "1 wrap", category: "prepared", emoji: "🌯" },

  // ─────────────────── SNACKS & SWEETS ───────────────────
  dark_chocolate: { name: "Dark Chocolate (70%)", calories: 170, protein: 2.2, carbs: 13, fat: 12, fiber: 3.1, serving: "1 oz (28g)", category: "snacks", emoji: "🍫" },
  milk_chocolate: { name: "Milk Chocolate", calories: 153, protein: 2.2, carbs: 17, fat: 8.4, fiber: 0.6, serving: "1 oz (28g)", category: "snacks", emoji: "🍫" },
  white_chocolate: { name: "White Chocolate", calories: 153, protein: 1.5, carbs: 17, fat: 9, fiber: 0, serving: "1 oz (28g)", category: "snacks", emoji: "🍫" },
  cookie: { name: "Chocolate Chip Cookie", calories: 78, protein: 0.9, carbs: 9.3, fat: 4.5, fiber: 0.3, serving: "1 medium (16g)", category: "snacks", emoji: "🍪" },
  brownie: { name: "Brownie", calories: 227, protein: 2.7, carbs: 36, fat: 9, fiber: 1.2, serving: "1 piece (56g)", category: "snacks", emoji: "🍫" },
  muffin_blueberry: { name: "Blueberry Muffin", calories: 426, protein: 6, carbs: 62, fat: 18, fiber: 2, serving: "1 large (128g)", category: "snacks", emoji: "🧁" },
  donut: { name: "Glazed Donut", calories: 269, protein: 4, carbs: 31, fat: 14, fiber: 0.7, serving: "1 medium (60g)", category: "snacks", emoji: "🍩" },
  cinnamon_roll: { name: "Cinnamon Roll", calories: 309, protein: 5, carbs: 42, fat: 14, fiber: 1, serving: "1 roll (80g)", category: "snacks", emoji: "🍩" },
  chips: { name: "Potato Chips", calories: 152, protein: 2, carbs: 15, fat: 10, fiber: 1.2, serving: "1 oz (28g)", category: "snacks", emoji: "🥔" },
  tortilla_chips: { name: "Tortilla Chips", calories: 140, protein: 2, carbs: 18, fat: 7, fiber: 1, serving: "1 oz (28g)", category: "snacks", emoji: "🥔" },
  popcorn: { name: "Popcorn (air-popped)", calories: 31, protein: 1, carbs: 6.2, fat: 0.4, fiber: 1.2, serving: "1 cup (8g)", category: "snacks", emoji: "🍿" },
  popcorn_butter: { name: "Popcorn (buttered)", calories: 60, protein: 0.8, carbs: 6.3, fat: 3.6, fiber: 1, serving: "1 cup (11g)", category: "snacks", emoji: "🍿" },
  pretzel: { name: "Pretzels", calories: 108, protein: 2.6, carbs: 23, fat: 0.7, fiber: 0.9, serving: "1 oz (28g)", category: "snacks", emoji: "🥨" },
  granola_bar: { name: "Granola Bar", calories: 117, protein: 2.5, carbs: 19, fat: 4.4, fiber: 1.5, serving: "1 bar (28g)", category: "snacks", emoji: "🥜" },
  protein_bar: { name: "Protein Bar", calories: 220, protein: 20, carbs: 24, fat: 8, fiber: 3, serving: "1 bar (60g)", category: "snacks", emoji: "🥜" },
  energy_bar: { name: "Energy Bar (Clif)", calories: 250, protein: 10, carbs: 45, fat: 5, fiber: 4, serving: "1 bar (68g)", category: "snacks", emoji: "🥜" },
  cake: { name: "Chocolate Cake", calories: 352, protein: 5, carbs: 51, fat: 15, fiber: 2, serving: "1 slice (100g)", category: "snacks", emoji: "🍰" },
  cheesecake: { name: "Cheesecake", calories: 321, protein: 5.5, carbs: 26, fat: 23, fiber: 0.3, serving: "1 slice (100g)", category: "snacks", emoji: "🍰" },
  pie_apple: { name: "Apple Pie", calories: 296, protein: 2.4, carbs: 43, fat: 14, fiber: 2, serving: "1 slice (125g)", category: "snacks", emoji: "🥧" },
  candy_bar: { name: "Snickers Bar", calories: 250, protein: 4, carbs: 33, fat: 12, fiber: 1, serving: "1 bar (52g)", category: "snacks", emoji: "🍫" },
  gummy_bears: { name: "Gummy Bears", calories: 87, protein: 1.7, carbs: 20, fat: 0, fiber: 0, serving: "10 pieces (22g)", category: "snacks", emoji: "🍬" },
  marshmallow: { name: "Marshmallows", calories: 23, protein: 0.1, carbs: 5.9, fat: 0, fiber: 0, serving: "1 large (7g)", category: "snacks", emoji: "🍬" },
  jello: { name: "Jello / Gelatin", calories: 80, protein: 1, carbs: 19, fat: 0, fiber: 0, serving: "1/2 cup (140g)", category: "snacks", emoji: "🍮" },
  pudding: { name: "Chocolate Pudding", calories: 150, protein: 3, carbs: 25, fat: 4.5, fiber: 0.5, serving: "1 cup (113g)", category: "snacks", emoji: "🍮" },
  crepe: { name: "Crêpe (plain)", calories: 112, protein: 3.5, carbs: 14, fat: 4.5, fiber: 0.3, serving: "1 crepe (55g)", category: "snacks", emoji: "🥞" },
  nutella: { name: "Nutella", calories: 200, protein: 2, carbs: 23, fat: 11, fiber: 1, serving: "2 tbsp (37g)", category: "snacks", emoji: "🍫" },

  // ─────────────────── BEVERAGES ───────────────────
  coffee: { name: "Black Coffee", calories: 2, protein: 0.3, carbs: 0, fat: 0, fiber: 0, serving: "1 cup (240ml)", category: "beverages", emoji: "☕" },
  latte: { name: "Café Latte (whole milk)", calories: 190, protein: 10, carbs: 18, fat: 7, fiber: 0, serving: "16 oz (473ml)", category: "beverages", emoji: "☕" },
  cappuccino: { name: "Cappuccino", calories: 120, protein: 8, carbs: 10, fat: 6, fiber: 0, serving: "12 oz (355ml)", category: "beverages", emoji: "☕" },
  espresso: { name: "Espresso", calories: 3, protein: 0, carbs: 0.5, fat: 0, fiber: 0, serving: "1 shot (30ml)", category: "beverages", emoji: "☕" },
  mocha: { name: "Caffè Mocha", calories: 290, protein: 10, carbs: 42, fat: 10, fiber: 1, serving: "16 oz (473ml)", category: "beverages", emoji: "☕" },
  green_tea: { name: "Green Tea", calories: 2, protein: 0, carbs: 0, fat: 0, fiber: 0, serving: "1 cup (240ml)", category: "beverages", emoji: "🍵" },
  black_tea: { name: "Black Tea", calories: 2, protein: 0, carbs: 0.5, fat: 0, fiber: 0, serving: "1 cup (240ml)", category: "beverages", emoji: "🍵" },
  matcha_latte: { name: "Matcha Latte", calories: 190, protein: 6, carbs: 28, fat: 7, fiber: 1, serving: "16 oz (473ml)", category: "beverages", emoji: "🍵" },
  hot_chocolate: { name: "Hot Chocolate", calories: 190, protein: 3, carbs: 27, fat: 8, fiber: 1, serving: "1 cup (240ml)", category: "beverages", emoji: "☕" },
  orange_juice: { name: "Orange Juice", calories: 112, protein: 1.7, carbs: 26, fat: 0.5, fiber: 0.5, serving: "1 cup (248ml)", category: "beverages", emoji: "🧃" },
  apple_juice: { name: "Apple Juice", calories: 114, protein: 0.3, carbs: 28, fat: 0.3, fiber: 0.5, serving: "1 cup (248ml)", category: "beverages", emoji: "🧃" },
  cranberry_juice: { name: "Cranberry Juice", calories: 116, protein: 0, carbs: 31, fat: 0, fiber: 0, serving: "1 cup (253ml)", category: "beverages", emoji: "🧃" },
  grape_juice: { name: "Grape Juice", calories: 152, protein: 1, carbs: 37, fat: 0.2, fiber: 0.2, serving: "1 cup (253ml)", category: "beverages", emoji: "🧃" },
  coconut_water: { name: "Coconut Water", calories: 46, protein: 1.7, carbs: 9, fat: 0.5, fiber: 2.6, serving: "1 cup (240ml)", category: "beverages", emoji: "🥥" },
  lemonade: { name: "Lemonade", calories: 99, protein: 0.2, carbs: 26, fat: 0.1, fiber: 0.2, serving: "1 cup (240ml)", category: "beverages", emoji: "🍋" },
  soda: { name: "Cola", calories: 140, protein: 0, carbs: 39, fat: 0, fiber: 0, serving: "1 can (355ml)", category: "beverages", emoji: "🥤" },
  diet_soda: { name: "Diet Cola", calories: 0, protein: 0, carbs: 0, fat: 0, fiber: 0, serving: "1 can (355ml)", category: "beverages", emoji: "🥤" },
  sports_drink: { name: "Gatorade", calories: 80, protein: 0, carbs: 21, fat: 0, fiber: 0, serving: "12 oz (355ml)", category: "beverages", emoji: "🥤" },
  energy_drink: { name: "Red Bull", calories: 110, protein: 0, carbs: 28, fat: 0, fiber: 0, serving: "1 can (250ml)", category: "beverages", emoji: "⚡" },
  beer: { name: "Beer (regular)", calories: 153, protein: 1.6, carbs: 13, fat: 0, fiber: 0, serving: "12 oz (355ml)", category: "beverages", emoji: "🍺" },
  light_beer: { name: "Light Beer", calories: 103, protein: 0.9, carbs: 6, fat: 0, fiber: 0, serving: "12 oz (355ml)", category: "beverages", emoji: "🍺" },
  red_wine: { name: "Red Wine", calories: 125, protein: 0.1, carbs: 4, fat: 0, fiber: 0, serving: "5 oz (148ml)", category: "beverages", emoji: "🍷" },
  white_wine: { name: "White Wine", calories: 121, protein: 0.1, carbs: 3.8, fat: 0, fiber: 0, serving: "5 oz (148ml)", category: "beverages", emoji: "🍷" },
  champagne: { name: "Champagne / Prosecco", calories: 85, protein: 0.1, carbs: 1.3, fat: 0, fiber: 0, serving: "4 oz (120ml)", category: "beverages", emoji: "🥂" },
  vodka: { name: "Vodka", calories: 97, protein: 0, carbs: 0, fat: 0, fiber: 0, serving: "1.5 oz (44ml)", category: "beverages", emoji: "🥃" },
  whiskey: { name: "Whiskey", calories: 105, protein: 0, carbs: 0, fat: 0, fiber: 0, serving: "1.5 oz (44ml)", category: "beverages", emoji: "🥃" },
  margarita: { name: "Margarita", calories: 274, protein: 0.1, carbs: 36, fat: 0, fiber: 0, serving: "8 oz (240ml)", category: "beverages", emoji: "🍸" },
  smoothie: { name: "Fruit Smoothie", calories: 180, protein: 3, carbs: 40, fat: 1, fiber: 3, serving: "12 oz (355ml)", category: "beverages", emoji: "🥤" },
  protein_shake: { name: "Protein Shake (whey + milk)", calories: 250, protein: 30, carbs: 20, fat: 5, fiber: 1, serving: "1 shake (350ml)", category: "beverages", emoji: "🥤" },

  // ─────────────────── OILS & CONDIMENTS ───────────────────
  olive_oil: { name: "Olive Oil", calories: 119, protein: 0, carbs: 0, fat: 14, fiber: 0, serving: "1 tbsp (14g)", category: "oils", emoji: "🫒" },
  coconut_oil: { name: "Coconut Oil", calories: 121, protein: 0, carbs: 0, fat: 13.5, fiber: 0, serving: "1 tbsp (14g)", category: "oils", emoji: "🥥" },
  vegetable_oil: { name: "Vegetable / Canola Oil", calories: 120, protein: 0, carbs: 0, fat: 14, fiber: 0, serving: "1 tbsp (14g)", category: "oils", emoji: "🫒" },
  sesame_oil: { name: "Sesame Oil", calories: 120, protein: 0, carbs: 0, fat: 14, fiber: 0, serving: "1 tbsp (14g)", category: "oils", emoji: "🫒" },
  honey: { name: "Honey", calories: 64, protein: 0.1, carbs: 17, fat: 0, fiber: 0, serving: "1 tbsp (21g)", category: "condiments", emoji: "🍯" },
  maple_syrup: { name: "Maple Syrup", calories: 52, protein: 0, carbs: 13, fat: 0, fiber: 0, serving: "1 tbsp (20g)", category: "condiments", emoji: "🍁" },
  sugar: { name: "White Sugar", calories: 49, protein: 0, carbs: 12.6, fat: 0, fiber: 0, serving: "1 tbsp (12.6g)", category: "condiments", emoji: "🍬" },
  brown_sugar: { name: "Brown Sugar", calories: 52, protein: 0, carbs: 13.5, fat: 0, fiber: 0, serving: "1 tbsp (14g)", category: "condiments", emoji: "🍬" },
  ketchup: { name: "Ketchup", calories: 19, protein: 0.2, carbs: 5, fat: 0, fiber: 0.1, serving: "1 tbsp (17g)", category: "condiments", emoji: "🍅" },
  mustard: { name: "Yellow Mustard", calories: 3, protein: 0.2, carbs: 0.3, fat: 0.2, fiber: 0.1, serving: "1 tsp (5g)", category: "condiments", emoji: "🟡" },
  dijon_mustard: { name: "Dijon Mustard", calories: 5, protein: 0.3, carbs: 0.5, fat: 0.3, fiber: 0, serving: "1 tsp (5g)", category: "condiments", emoji: "🟡" },
  mayonnaise: { name: "Mayonnaise", calories: 94, protein: 0.1, carbs: 0.1, fat: 10, fiber: 0, serving: "1 tbsp (14g)", category: "condiments", emoji: "🥚" },
  light_mayo: { name: "Light Mayonnaise", calories: 35, protein: 0, carbs: 1, fat: 3.5, fiber: 0, serving: "1 tbsp (15g)", category: "condiments", emoji: "🥚" },
  soy_sauce: { name: "Soy Sauce", calories: 9, protein: 1.3, carbs: 0.8, fat: 0, fiber: 0.1, serving: "1 tbsp (16g)", category: "condiments", emoji: "🫗" },
  hot_sauce: { name: "Hot Sauce (Tabasco)", calories: 0, protein: 0, carbs: 0, fat: 0, fiber: 0, serving: "1 tsp (5ml)", category: "condiments", emoji: "🌶️" },
  sriracha: { name: "Sriracha", calories: 5, protein: 0, carbs: 1, fat: 0, fiber: 0, serving: "1 tsp (5g)", category: "condiments", emoji: "🌶️" },
  bbq_sauce: { name: "BBQ Sauce", calories: 29, protein: 0, carbs: 7, fat: 0, fiber: 0, serving: "1 tbsp (17g)", category: "condiments", emoji: "🍖" },
  ranch_dressing: { name: "Ranch Dressing", calories: 73, protein: 0.4, carbs: 1, fat: 7.7, fiber: 0, serving: "1 tbsp (15g)", category: "condiments", emoji: "🥗" },
  italian_dressing: { name: "Italian Dressing", calories: 43, protein: 0, carbs: 2.4, fat: 3.8, fiber: 0, serving: "1 tbsp (15g)", category: "condiments", emoji: "🥗" },
  balsamic_vinegar: { name: "Balsamic Vinegar", calories: 14, protein: 0, carbs: 2.7, fat: 0, fiber: 0, serving: "1 tbsp (15ml)", category: "condiments", emoji: "🫒" },
  apple_cider_vinegar: { name: "Apple Cider Vinegar", calories: 3, protein: 0, carbs: 0.1, fat: 0, fiber: 0, serving: "1 tbsp (15ml)", category: "condiments", emoji: "🍎" },
  salsa: { name: "Salsa", calories: 10, protein: 0.5, carbs: 2, fat: 0, fiber: 0.5, serving: "2 tbsp (30g)", category: "condiments", emoji: "🍅" },
  guacamole: { name: "Guacamole", calories: 50, protein: 0.6, carbs: 3, fat: 4.5, fiber: 2, serving: "2 tbsp (30g)", category: "condiments", emoji: "🥑" },
  pesto: { name: "Basil Pesto", calories: 80, protein: 2, carbs: 1, fat: 8, fiber: 0.3, serving: "1 tbsp (15g)", category: "condiments", emoji: "🌿" },
  marinara: { name: "Marinara Sauce", calories: 66, protein: 2, carbs: 10, fat: 2, fiber: 2, serving: "1/2 cup (125g)", category: "condiments", emoji: "🍅" },
  alfredo_sauce: { name: "Alfredo Sauce", calories: 100, protein: 2, carbs: 3, fat: 9, fiber: 0, serving: "1/4 cup (62g)", category: "condiments", emoji: "🧀" },
  teriyaki: { name: "Teriyaki Sauce", calories: 16, protein: 1, carbs: 3, fat: 0, fiber: 0, serving: "1 tbsp (18g)", category: "condiments", emoji: "🫗" },
  fish_sauce: { name: "Fish Sauce", calories: 6, protein: 0.9, carbs: 0.7, fat: 0, fiber: 0, serving: "1 tsp (5ml)", category: "condiments", emoji: "🫗" },
  worcestershire: { name: "Worcestershire Sauce", calories: 4, protein: 0, carbs: 1, fat: 0, fiber: 0, serving: "1 tsp (5ml)", category: "condiments", emoji: "🫗" },
  jam: { name: "Strawberry Jam", calories: 56, protein: 0.1, carbs: 14, fat: 0, fiber: 0.2, serving: "1 tbsp (20g)", category: "condiments", emoji: "🍓" },
};

// Merge base + extra into one exported database
export const foodDatabase: Record<string, FoodItem> = { ...baseFoods, ...extraFoods };
