// ══════════════════════════════════════════════════════════════════
// EXTENDED FOOD DATABASE — Hundreds of additional items
// Raw products, processed foods, fast food, world cuisine, etc.
// All values USDA-based per serving
// ══════════════════════════════════════════════════════════════════

// FoodItem type defined inline to avoid circular import
interface FoodItem {
  name: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
  serving: string;
  category: string;
  emoji: string;
}

export const extraFoods: Record<string, FoodItem> = {

  // ─────────────────── RAW MEATS (additional cuts) ───────────────────
  beef_brisket: { name: "Beef Brisket", calories: 246, protein: 26, carbs: 0, fat: 15, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🥩" },
  beef_short_ribs: { name: "Beef Short Ribs", calories: 295, protein: 22, carbs: 0, fat: 23, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🥩" },
  flank_steak: { name: "Flank Steak", calories: 192, protein: 29, carbs: 0, fat: 8, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🥩" },
  skirt_steak: { name: "Skirt Steak", calories: 210, protein: 27, carbs: 0, fat: 11, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🥩" },
  t_bone: { name: "T-Bone Steak", calories: 247, protein: 24, carbs: 0, fat: 16, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🥩" },
  beef_tongue: { name: "Beef Tongue", calories: 284, protein: 22, carbs: 0, fat: 22, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🥩" },
  beef_liver: { name: "Beef Liver", calories: 175, protein: 27, carbs: 5, fat: 5, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🥩" },
  oxtail: { name: "Oxtail", calories: 262, protein: 30, carbs: 0, fat: 15, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🥩" },
  pork_ribs: { name: "Pork Spare Ribs", calories: 277, protein: 21, carbs: 0, fat: 21, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🍖" },
  pork_shoulder: { name: "Pork Shoulder / Pulled Pork", calories: 269, protein: 26, carbs: 0, fat: 18, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🍖" },
  pork_loin: { name: "Pork Loin", calories: 182, protein: 27, carbs: 0, fat: 8, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🍖" },
  pork_sausage_link: { name: "Breakfast Sausage Link", calories: 82, protein: 4, carbs: 0.5, fat: 7, fiber: 0, serving: "1 link (25g)", category: "protein", emoji: "🌭" },
  kielbasa: { name: "Kielbasa / Polish Sausage", calories: 297, protein: 12, carbs: 3, fat: 26, fiber: 0, serving: "100g", category: "protein", emoji: "🌭" },
  andouille: { name: "Andouille Sausage", calories: 229, protein: 17, carbs: 2, fat: 17, fiber: 0, serving: "1 link (100g)", category: "protein", emoji: "🌭" },
  merguez: { name: "Merguez Sausage", calories: 280, protein: 14, carbs: 2, fat: 24, fiber: 0, serving: "1 link (80g)", category: "protein", emoji: "🌭" },
  mortadella: { name: "Mortadella", calories: 311, protein: 16, carbs: 3, fat: 26, fiber: 0, serving: "100g", category: "protein", emoji: "🍖" },
  salami: { name: "Salami", calories: 119, protein: 6.5, carbs: 0.5, fat: 10, fiber: 0, serving: "3 slices (30g)", category: "protein", emoji: "🍖" },
  pepperoni: { name: "Pepperoni", calories: 138, protein: 6, carbs: 1, fat: 12, fiber: 0, serving: "15 slices (28g)", category: "protein", emoji: "🍕" },
  bologna: { name: "Bologna", calories: 87, protein: 3.3, carbs: 1, fat: 8, fiber: 0, serving: "1 slice (28g)", category: "protein", emoji: "🍖" },
  pate: { name: "Pâté (liver)", calories: 319, protein: 11, carbs: 4, fat: 28, fiber: 0, serving: "100g", category: "protein", emoji: "🍖" },
  foie_gras: { name: "Foie Gras", calories: 462, protein: 11, carbs: 4.7, fat: 44, fiber: 0, serving: "100g", category: "protein", emoji: "🍖" },
  rabbit: { name: "Rabbit", calories: 173, protein: 33, carbs: 0, fat: 3.5, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🍖" },
  goat: { name: "Goat Meat", calories: 143, protein: 27, carbs: 0, fat: 3, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🍖" },

  // ─────────────────── SEAFOOD (extra) ───────────────────
  sea_bass: { name: "Sea Bass", calories: 124, protein: 24, carbs: 0, fat: 2.6, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🐟" },
  swordfish: { name: "Swordfish", calories: 172, protein: 28, carbs: 0, fat: 5.7, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🐟" },
  red_snapper: { name: "Red Snapper", calories: 128, protein: 26, carbs: 0, fat: 1.7, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🐟" },
  catfish: { name: "Catfish", calories: 144, protein: 18, carbs: 0, fat: 8, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🐟" },
  perch: { name: "Perch", calories: 117, protein: 25, carbs: 0, fat: 1.2, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🐟" },
  anchovies: { name: "Anchovies (canned)", calories: 210, protein: 29, carbs: 0, fat: 10, fiber: 0, serving: "100g", category: "protein", emoji: "🐟" },
  herring: { name: "Herring (pickled)", calories: 262, protein: 14, carbs: 10, fat: 18, fiber: 0, serving: "100g", category: "protein", emoji: "🐟" },
  smelt: { name: "Smelt (fried)", calories: 229, protein: 21, carbs: 6, fat: 14, fiber: 0, serving: "100g", category: "protein", emoji: "🐟" },
  octopus: { name: "Octopus", calories: 164, protein: 30, carbs: 4.4, fat: 2.1, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🐙" },
  clams: { name: "Clams", calories: 148, protein: 26, carbs: 5, fat: 2, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🦪" },
  crawfish: { name: "Crawfish / Crayfish", calories: 82, protein: 17, carbs: 0, fat: 1.2, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🦐" },
  eel: { name: "Eel (unagi)", calories: 236, protein: 24, carbs: 0, fat: 15, fiber: 0, serving: "100g cooked", category: "protein", emoji: "🐟" },
  caviar: { name: "Caviar", calories: 42, protein: 4, carbs: 0.6, fat: 2.9, fiber: 0, serving: "1 tbsp (16g)", category: "protein", emoji: "🐟" },

  // ─────────────────── CHEESE (world varieties) ───────────────────
  blue_cheese: { name: "Blue Cheese", calories: 100, protein: 6, carbs: 0.7, fat: 8, fiber: 0, serving: "1 oz (28g)", category: "dairy", emoji: "🧀" },
  camembert: { name: "Camembert", calories: 85, protein: 5.6, carbs: 0.1, fat: 7, fiber: 0, serving: "1 oz (28g)", category: "dairy", emoji: "🧀" },
  gruyere: { name: "Gruyère", calories: 117, protein: 8, carbs: 0.1, fat: 9.2, fiber: 0, serving: "1 oz (28g)", category: "dairy", emoji: "🧀" },
  emmental: { name: "Emmental", calories: 111, protein: 8, carbs: 0.4, fat: 8.8, fiber: 0, serving: "1 oz (28g)", category: "dairy", emoji: "🧀" },
  manchego: { name: "Manchego", calories: 107, protein: 7.5, carbs: 0.1, fat: 8.5, fiber: 0, serving: "1 oz (28g)", category: "dairy", emoji: "🧀" },
  provolone: { name: "Provolone", calories: 98, protein: 7.3, carbs: 0.6, fat: 7.6, fiber: 0, serving: "1 oz (28g)", category: "dairy", emoji: "🧀" },
  american_cheese: { name: "American Cheese", calories: 94, protein: 5, carbs: 2.4, fat: 7.4, fiber: 0, serving: "1 slice (21g)", category: "dairy", emoji: "🧀" },
  halloumi: { name: "Halloumi", calories: 90, protein: 7, carbs: 0.5, fat: 7, fiber: 0, serving: "1 oz (28g)", category: "dairy", emoji: "🧀" },
  mascarpone: { name: "Mascarpone", calories: 120, protein: 1.6, carbs: 0.5, fat: 13, fiber: 0, serving: "1 oz (28g)", category: "dairy", emoji: "🧀" },
  raclette: { name: "Raclette Cheese", calories: 110, protein: 7, carbs: 0, fat: 9, fiber: 0, serving: "1 oz (28g)", category: "dairy", emoji: "🧀" },
  burrata: { name: "Burrata", calories: 80, protein: 5, carbs: 1, fat: 6, fiber: 0, serving: "1 oz (28g)", category: "dairy", emoji: "🧀" },
  cheese_spread: { name: "Cheese Spread (Laughing Cow)", calories: 35, protein: 2, carbs: 1, fat: 2.5, fiber: 0, serving: "1 wedge (21g)", category: "dairy", emoji: "🧀" },
  velveeta: { name: "Velveeta Cheese", calories: 80, protein: 5, carbs: 3, fat: 6, fiber: 0, serving: "1 oz (28g)", category: "dairy", emoji: "🧀" },
  queso_fresco: { name: "Queso Fresco", calories: 83, protein: 5, carbs: 1, fat: 6, fiber: 0, serving: "1 oz (28g)", category: "dairy", emoji: "🧀" },

  // ─────────────────── WORLD CUISINE ───────────────────
  coq_au_vin: { name: "Coq au Vin", calories: 280, protein: 25, carbs: 8, fat: 15, fiber: 1, serving: "1 serving (250g)", category: "prepared", emoji: "🍗" },
  beef_bourguignon: { name: "Beef Bourguignon", calories: 310, protein: 28, carbs: 12, fat: 16, fiber: 2, serving: "1 serving (250g)", category: "prepared", emoji: "🍲" },
  ratatouille: { name: "Ratatouille", calories: 97, protein: 2, carbs: 12, fat: 5, fiber: 3.5, serving: "1 cup (200g)", category: "prepared", emoji: "🍲" },
  quiche_lorraine: { name: "Quiche Lorraine", calories: 343, protein: 13, carbs: 19, fat: 24, fiber: 0.5, serving: "1 slice (130g)", category: "prepared", emoji: "🥧" },
  croque_monsieur: { name: "Croque-Monsieur", calories: 393, protein: 20, carbs: 26, fat: 23, fiber: 1, serving: "1 sandwich", category: "prepared", emoji: "🥪" },
  french_onion_soup: { name: "French Onion Soup", calories: 230, protein: 9, carbs: 19, fat: 13, fiber: 2, serving: "1 bowl (300ml)", category: "prepared", emoji: "🍲" },
  crepe_nutella: { name: "Crêpe Nutella", calories: 310, protein: 6, carbs: 42, fat: 14, fiber: 1.5, serving: "1 crepe", category: "prepared", emoji: "🥞" },
  galette: { name: "Galette Complète (buckwheat)", calories: 320, protein: 16, carbs: 28, fat: 16, fiber: 2, serving: "1 galette", category: "prepared", emoji: "🥞" },
  escargot: { name: "Escargot (garlic butter)", calories: 170, protein: 14, carbs: 2, fat: 12, fiber: 0, serving: "6 pieces", category: "prepared", emoji: "🐌" },
  bouillabaisse: { name: "Bouillabaisse", calories: 215, protein: 22, carbs: 10, fat: 9, fiber: 2, serving: "1 bowl (300ml)", category: "prepared", emoji: "🍲" },
  pot_au_feu: { name: "Pot-au-Feu", calories: 250, protein: 24, carbs: 15, fat: 10, fiber: 3, serving: "1 serving (300g)", category: "prepared", emoji: "🍲" },
  cassoulet: { name: "Cassoulet", calories: 380, protein: 22, carbs: 30, fat: 19, fiber: 8, serving: "1 serving (300g)", category: "prepared", emoji: "🍲" },
  tartiflette: { name: "Tartiflette", calories: 350, protein: 14, carbs: 22, fat: 23, fiber: 1, serving: "1 serving (250g)", category: "prepared", emoji: "🧀" },
  moussaka: { name: "Moussaka", calories: 280, protein: 15, carbs: 18, fat: 17, fiber: 3, serving: "1 serving (250g)", category: "prepared", emoji: "🍲" },
  spanakopita: { name: "Spanakopita (spinach pie)", calories: 180, protein: 6, carbs: 14, fat: 12, fiber: 1.5, serving: "1 piece (80g)", category: "prepared", emoji: "🥧" },
  gyro: { name: "Gyro (lamb)", calories: 450, protein: 25, carbs: 40, fat: 22, fiber: 2, serving: "1 wrap", category: "prepared", emoji: "🌯" },
  dolma: { name: "Dolma (stuffed grape leaves)", calories: 45, protein: 1, carbs: 5, fat: 2.5, fiber: 1, serving: "1 piece (28g)", category: "prepared", emoji: "🥬" },
  bibimbap: { name: "Bibimbap", calories: 490, protein: 24, carbs: 60, fat: 16, fiber: 4, serving: "1 bowl", category: "prepared", emoji: "🍚" },
  bulgogi: { name: "Bulgogi (Korean BBQ beef)", calories: 259, protein: 22, carbs: 15, fat: 12, fiber: 1, serving: "1 serving (150g)", category: "prepared", emoji: "🥩" },
  kimchi: { name: "Kimchi", calories: 15, protein: 1, carbs: 2.4, fat: 0.5, fiber: 1.6, serving: "1/2 cup (75g)", category: "prepared", emoji: "🥬" },
  japchae: { name: "Japchae (glass noodles)", calories: 230, protein: 5, carbs: 38, fat: 7, fiber: 2, serving: "1 cup (200g)", category: "prepared", emoji: "🍜" },
  tonkatsu: { name: "Tonkatsu (pork cutlet)", calories: 340, protein: 22, carbs: 18, fat: 20, fiber: 1, serving: "1 cutlet (150g)", category: "prepared", emoji: "🍖" },
  tempura: { name: "Shrimp Tempura", calories: 230, protein: 11, carbs: 22, fat: 11, fiber: 1, serving: "4 pieces (100g)", category: "prepared", emoji: "🦐" },
  okonomiyaki: { name: "Okonomiyaki (Japanese pancake)", calories: 320, protein: 12, carbs: 35, fat: 14, fiber: 2, serving: "1 pancake (200g)", category: "prepared", emoji: "🥞" },
  takoyaki: { name: "Takoyaki (octopus balls)", calories: 60, protein: 3, carbs: 6, fat: 3, fiber: 0.2, serving: "1 ball (30g)", category: "prepared", emoji: "🐙" },
  edamame_steamed: { name: "Steamed Edamame", calories: 120, protein: 12, carbs: 9, fat: 5, fiber: 5, serving: "1 cup in pods", category: "prepared", emoji: "🫛" },
  katsu_curry: { name: "Chicken Katsu Curry", calories: 550, protein: 28, carbs: 60, fat: 22, fiber: 3, serving: "1 plate", category: "prepared", emoji: "🍛" },
  pho_chicken: { name: "Chicken Pho", calories: 300, protein: 20, carbs: 38, fat: 6, fiber: 1, serving: "1 bowl (500ml)", category: "prepared", emoji: "🍜" },
  banh_mi: { name: "Bánh Mì Sandwich", calories: 360, protein: 18, carbs: 42, fat: 13, fiber: 2, serving: "1 sandwich", category: "prepared", emoji: "🥖" },
  spring_roll_fresh: { name: "Fresh Spring Roll (rice paper)", calories: 60, protein: 3, carbs: 9, fat: 1.5, fiber: 0.5, serving: "1 roll (60g)", category: "prepared", emoji: "🥟" },
  thai_green_curry: { name: "Thai Green Curry", calories: 250, protein: 18, carbs: 12, fat: 15, fiber: 2, serving: "1 cup (200g)", category: "prepared", emoji: "🍛" },
  tom_yum: { name: "Tom Yum Soup", calories: 120, protein: 12, carbs: 8, fat: 4, fiber: 1, serving: "1 bowl (300ml)", category: "prepared", emoji: "🍲" },
  massaman_curry: { name: "Massaman Curry", calories: 310, protein: 18, carbs: 22, fat: 17, fiber: 3, serving: "1 cup (200g)", category: "prepared", emoji: "🍛" },
  som_tam: { name: "Som Tam (papaya salad)", calories: 100, protein: 3, carbs: 18, fat: 2, fiber: 3, serving: "1 serving (150g)", category: "prepared", emoji: "🥗" },
  nasi_goreng: { name: "Nasi Goreng", calories: 370, protein: 14, carbs: 48, fat: 14, fiber: 2, serving: "1 plate (250g)", category: "prepared", emoji: "🍚" },
  satay: { name: "Chicken Satay (2 skewers)", calories: 200, protein: 20, carbs: 6, fat: 11, fiber: 0.5, serving: "2 skewers", category: "prepared", emoji: "🍢" },
  rendang: { name: "Beef Rendang", calories: 320, protein: 26, carbs: 6, fat: 22, fiber: 1, serving: "1 serving (150g)", category: "prepared", emoji: "🍛" },
  biryani: { name: "Chicken Biryani", calories: 400, protein: 20, carbs: 50, fat: 14, fiber: 2, serving: "1 serving (300g)", category: "prepared", emoji: "🍚" },
  butter_chicken: { name: "Butter Chicken", calories: 260, protein: 20, carbs: 10, fat: 16, fiber: 2, serving: "1 cup (200g)", category: "prepared", emoji: "🍛" },
  palak_paneer: { name: "Palak Paneer", calories: 220, protein: 12, carbs: 8, fat: 16, fiber: 3, serving: "1 cup (200g)", category: "prepared", emoji: "🍛" },
  chana_masala: { name: "Chana Masala", calories: 210, protein: 9, carbs: 30, fat: 7, fiber: 8, serving: "1 cup (200g)", category: "prepared", emoji: "🍛" },
  tandoori_chicken: { name: "Tandoori Chicken", calories: 195, protein: 28, carbs: 5, fat: 7, fiber: 0.5, serving: "1 leg + thigh (150g)", category: "prepared", emoji: "🍗" },
  naan_garlic: { name: "Garlic Naan", calories: 300, protein: 10, carbs: 48, fat: 7, fiber: 2, serving: "1 piece (100g)", category: "grains", emoji: "🫓" },
  sambar: { name: "Sambar (lentil soup)", calories: 120, protein: 6, carbs: 18, fat: 3, fiber: 5, serving: "1 cup (200g)", category: "prepared", emoji: "🍲" },
  dosa: { name: "Dosa (plain)", calories: 133, protein: 3, carbs: 22, fat: 4, fiber: 1, serving: "1 dosa (80g)", category: "prepared", emoji: "🥞" },
  jollof_rice: { name: "Jollof Rice", calories: 260, protein: 4, carbs: 42, fat: 8, fiber: 2, serving: "1 cup (200g)", category: "prepared", emoji: "🍚" },
  injera: { name: "Injera (Ethiopian flatbread)", calories: 125, protein: 5, carbs: 25, fat: 0.7, fiber: 3, serving: "1 piece (100g)", category: "grains", emoji: "🫓" },
  tagine: { name: "Chicken Tagine", calories: 280, protein: 22, carbs: 20, fat: 13, fiber: 4, serving: "1 serving (250g)", category: "prepared", emoji: "🍲" },
  couscous_royal: { name: "Couscous Royal", calories: 380, protein: 22, carbs: 45, fat: 12, fiber: 5, serving: "1 plate (350g)", category: "prepared", emoji: "🍲" },
  shakshuka: { name: "Shakshuka", calories: 210, protein: 12, carbs: 14, fat: 13, fiber: 3, serving: "1 serving (200g)", category: "prepared", emoji: "🍳" },
  baba_ganoush: { name: "Baba Ganoush", calories: 72, protein: 2, carbs: 6, fat: 5, fiber: 2.5, serving: "1/4 cup (60g)", category: "prepared", emoji: "🍆" },
  tabbouleh: { name: "Tabbouleh", calories: 80, protein: 2, carbs: 10, fat: 4, fiber: 2, serving: "1/2 cup (80g)", category: "prepared", emoji: "🥗" },
  arepas: { name: "Arepa (corn)", calories: 150, protein: 3, carbs: 28, fat: 3, fiber: 2, serving: "1 arepa (80g)", category: "grains", emoji: "🫓" },
  pupusa: { name: "Pupusa (cheese)", calories: 230, protein: 9, carbs: 28, fat: 9, fiber: 2, serving: "1 pupusa (100g)", category: "prepared", emoji: "🫓" },
  ceviche: { name: "Ceviche", calories: 120, protein: 18, carbs: 6, fat: 3, fiber: 1, serving: "1 cup (150g)", category: "prepared", emoji: "🐟" },
  tamale: { name: "Tamale (pork)", calories: 285, protein: 10, carbs: 24, fat: 17, fiber: 3, serving: "1 tamale (120g)", category: "prepared", emoji: "🫔" },
  chimichanga: { name: "Chimichanga (beef)", calories: 443, protein: 18, carbs: 39, fat: 24, fiber: 3, serving: "1 piece", category: "prepared", emoji: "🌯" },
  enchilada: { name: "Chicken Enchilada", calories: 230, protein: 14, carbs: 20, fat: 11, fiber: 2, serving: "1 enchilada", category: "prepared", emoji: "🌯" },
  tostada: { name: "Tostada (beef)", calories: 210, protein: 11, carbs: 16, fat: 11, fiber: 3, serving: "1 tostada", category: "prepared", emoji: "🌮" },
  elote: { name: "Elote (Mexican street corn)", calories: 210, protein: 5, carbs: 28, fat: 10, fiber: 3, serving: "1 ear", category: "prepared", emoji: "🌽" },
  pierogi: { name: "Pierogi (potato/cheese)", calories: 60, protein: 2, carbs: 9, fat: 2, fiber: 0.5, serving: "1 pierogi (30g)", category: "prepared", emoji: "🥟" },
  borscht: { name: "Borscht (beet soup)", calories: 85, protein: 3, carbs: 12, fat: 3, fiber: 2, serving: "1 cup (240ml)", category: "prepared", emoji: "🍲" },
  stroganoff: { name: "Beef Stroganoff", calories: 310, protein: 22, carbs: 18, fat: 18, fiber: 1, serving: "1 cup (200g)", category: "prepared", emoji: "🍲" },
  goulash: { name: "Goulash", calories: 260, protein: 20, carbs: 18, fat: 12, fiber: 3, serving: "1 cup (250g)", category: "prepared", emoji: "🍲" },
  schnitzel: { name: "Wiener Schnitzel", calories: 310, protein: 24, carbs: 16, fat: 18, fiber: 0.5, serving: "1 piece (150g)", category: "prepared", emoji: "🍖" },
  currywurst: { name: "Currywurst", calories: 320, protein: 14, carbs: 20, fat: 20, fiber: 1, serving: "1 serving (200g)", category: "prepared", emoji: "🌭" },
  paella: { name: "Paella (seafood)", calories: 310, protein: 18, carbs: 38, fat: 10, fiber: 2, serving: "1 serving (250g)", category: "prepared", emoji: "🥘" },
  risotto: { name: "Mushroom Risotto", calories: 290, protein: 7, carbs: 42, fat: 10, fiber: 1.5, serving: "1 cup (220g)", category: "prepared", emoji: "🍚" },
  osso_buco: { name: "Osso Buco", calories: 350, protein: 32, carbs: 5, fat: 22, fiber: 1, serving: "1 shank (200g)", category: "prepared", emoji: "🍖" },
  carbonara: { name: "Pasta Carbonara", calories: 410, protein: 18, carbs: 44, fat: 18, fiber: 2, serving: "1 cup (220g)", category: "prepared", emoji: "🍝" },
  bolognese: { name: "Spaghetti Bolognese", calories: 370, protein: 20, carbs: 42, fat: 14, fiber: 3, serving: "1 plate (280g)", category: "prepared", emoji: "🍝" },
  pesto_pasta: { name: "Pesto Pasta", calories: 380, protein: 12, carbs: 42, fat: 18, fiber: 2, serving: "1 cup (220g)", category: "prepared", emoji: "🍝" },
  bruschetta: { name: "Bruschetta", calories: 120, protein: 3, carbs: 15, fat: 5, fiber: 1, serving: "2 pieces", category: "prepared", emoji: "🍞" },
  antipasto: { name: "Antipasto Plate", calories: 350, protein: 18, carbs: 8, fat: 28, fiber: 2, serving: "1 plate (150g)", category: "prepared", emoji: "🍖" },
  tiramisu: { name: "Tiramisu", calories: 283, protein: 5, carbs: 31, fat: 15, fiber: 0.5, serving: "1 piece (100g)", category: "snacks", emoji: "🍰" },
  panna_cotta: { name: "Panna Cotta", calories: 230, protein: 4, carbs: 22, fat: 14, fiber: 0, serving: "1 serving (120g)", category: "snacks", emoji: "🍮" },
  creme_brulee: { name: "Crème Brûlée", calories: 300, protein: 5, carbs: 32, fat: 17, fiber: 0, serving: "1 serving (130g)", category: "snacks", emoji: "🍮" },
  eclair: { name: "Chocolate Éclair", calories: 262, protein: 6, carbs: 24, fat: 16, fiber: 1, serving: "1 piece (100g)", category: "snacks", emoji: "🥐" },
  macaron: { name: "Macaron", calories: 97, protein: 1.5, carbs: 14, fat: 4, fiber: 0.5, serving: "1 macaron (20g)", category: "snacks", emoji: "🍪" },
  croissant_choc: { name: "Pain au Chocolat", calories: 275, protein: 5, carbs: 30, fat: 15, fiber: 1.5, serving: "1 piece (65g)", category: "snacks", emoji: "🥐" },
  baklava: { name: "Baklava", calories: 230, protein: 4, carbs: 26, fat: 13, fiber: 1.5, serving: "1 piece (60g)", category: "snacks", emoji: "🍯" },
  churro: { name: "Churro", calories: 116, protein: 1.5, carbs: 15, fat: 6, fiber: 0.5, serving: "1 churro (40g)", category: "snacks", emoji: "🍩" },
  mochi: { name: "Mochi Ice Cream", calories: 100, protein: 1, carbs: 17, fat: 3, fiber: 0, serving: "1 piece (44g)", category: "snacks", emoji: "🍡" },
  gelato: { name: "Gelato", calories: 180, protein: 3, carbs: 26, fat: 7, fiber: 0, serving: "1/2 cup (90g)", category: "snacks", emoji: "🍨" },
  sorbet: { name: "Fruit Sorbet", calories: 120, protein: 0, carbs: 30, fat: 0, fiber: 0.5, serving: "1/2 cup (90g)", category: "snacks", emoji: "🍨" },

  // ─────────────────── FAST FOOD CHAINS ───────────────────
  big_mac: { name: "Big Mac", calories: 563, protein: 26, carbs: 44, fat: 33, fiber: 3, serving: "1 burger (200g)", category: "prepared", emoji: "🍔" },
  quarter_pounder: { name: "Quarter Pounder w/ Cheese", calories: 520, protein: 30, carbs: 42, fat: 26, fiber: 2, serving: "1 burger (199g)", category: "prepared", emoji: "🍔" },
  mcnuggets_6: { name: "Chicken McNuggets (6pc)", calories: 250, protein: 15, carbs: 15, fat: 15, fiber: 0, serving: "6 pieces (100g)", category: "prepared", emoji: "🍗" },
  mcnuggets_10: { name: "Chicken McNuggets (10pc)", calories: 410, protein: 25, carbs: 25, fat: 24, fiber: 1, serving: "10 pieces (167g)", category: "prepared", emoji: "🍗" },
  whopper: { name: "Whopper", calories: 657, protein: 28, carbs: 49, fat: 40, fiber: 2, serving: "1 burger (270g)", category: "prepared", emoji: "🍔" },
  chicken_sandwich_fast: { name: "Crispy Chicken Sandwich", calories: 455, protein: 28, carbs: 40, fat: 20, fiber: 2, serving: "1 sandwich", category: "prepared", emoji: "🥪" },
  fish_sandwich: { name: "Filet-O-Fish", calories: 390, protein: 16, carbs: 39, fat: 19, fiber: 2, serving: "1 sandwich (142g)", category: "prepared", emoji: "🐟" },
  mcflurry: { name: "McFlurry (Oreo)", calories: 510, protein: 13, carbs: 80, fat: 17, fiber: 1, serving: "1 regular (283g)", category: "snacks", emoji: "🍨" },
  fries_small: { name: "Small Fries (fast food)", calories: 220, protein: 3, carbs: 29, fat: 11, fiber: 3, serving: "small (71g)", category: "prepared", emoji: "🍟" },
  fries_large: { name: "Large Fries (fast food)", calories: 490, protein: 7, carbs: 66, fat: 23, fiber: 6, serving: "large (154g)", category: "prepared", emoji: "🍟" },
  fried_chicken_piece: { name: "Fried Chicken (1 piece KFC-style)", calories: 320, protein: 19, carbs: 12, fat: 22, fiber: 0.5, serving: "1 thigh (130g)", category: "prepared", emoji: "🍗" },
  chicken_wrap_fast: { name: "Grilled Chicken Wrap", calories: 370, protein: 27, carbs: 32, fat: 14, fiber: 2, serving: "1 wrap", category: "prepared", emoji: "🌯" },
  breakfast_sandwich: { name: "Egg McMuffin", calories: 310, protein: 17, carbs: 30, fat: 13, fiber: 2, serving: "1 sandwich (137g)", category: "prepared", emoji: "🥪" },
  hash_brown: { name: "Hash Brown (fast food)", calories: 150, protein: 1, carbs: 15, fat: 9, fiber: 2, serving: "1 piece (57g)", category: "prepared", emoji: "🥔" },
  burrito_fast: { name: "Breakfast Burrito (fast food)", calories: 300, protein: 12, carbs: 26, fat: 16, fiber: 1, serving: "1 burrito (113g)", category: "prepared", emoji: "🌯" },
  footlong_sub: { name: "Footlong Sub (turkey)", calories: 560, protein: 36, carbs: 72, fat: 12, fiber: 5, serving: "1 sub (350g)", category: "prepared", emoji: "🥖" },
  sub_6inch: { name: "6-inch Sub (turkey)", calories: 280, protein: 18, carbs: 36, fat: 6, fiber: 3, serving: "1 sub (175g)", category: "prepared", emoji: "🥖" },
  chicken_bowl_chipotle: { name: "Chipotle Chicken Bowl", calories: 665, protein: 40, carbs: 72, fat: 22, fiber: 12, serving: "1 bowl", category: "prepared", emoji: "🌯" },
  poke_bowl: { name: "Poke Bowl (tuna)", calories: 450, protein: 28, carbs: 50, fat: 14, fiber: 4, serving: "1 bowl", category: "prepared", emoji: "🍣" },
  acai_bowl: { name: "Açaí Bowl", calories: 390, protein: 6, carbs: 62, fat: 14, fiber: 7, serving: "1 bowl (350g)", category: "prepared", emoji: "🫐" },

  // ─────────────────── BREAKFAST ITEMS (extra) ───────────────────
  eggs_benedict: { name: "Eggs Benedict", calories: 470, protein: 24, carbs: 28, fat: 30, fiber: 1, serving: "1 serving (2 eggs)", category: "prepared", emoji: "🍳" },
  frittata: { name: "Vegetable Frittata", calories: 180, protein: 12, carbs: 5, fat: 13, fiber: 1, serving: "1 slice (120g)", category: "prepared", emoji: "🍳" },
  breakfast_sausage_patty: { name: "Breakfast Sausage Patty", calories: 100, protein: 5, carbs: 0.5, fat: 9, fiber: 0, serving: "1 patty (28g)", category: "protein", emoji: "🥓" },
  grits: { name: "Grits (cooked)", calories: 143, protein: 3, carbs: 31, fat: 0.5, fiber: 1.6, serving: "1 cup (242g)", category: "grains", emoji: "🥣" },
  biscuit: { name: "Buttermilk Biscuit", calories: 166, protein: 3, carbs: 20, fat: 8, fiber: 0.5, serving: "1 biscuit (45g)", category: "grains", emoji: "🍞" },
  scone: { name: "Blueberry Scone", calories: 420, protein: 7, carbs: 55, fat: 19, fiber: 1.5, serving: "1 scone (110g)", category: "snacks", emoji: "🧁" },
  danish: { name: "Cheese Danish", calories: 266, protein: 6, carbs: 26, fat: 16, fiber: 0.5, serving: "1 pastry (71g)", category: "snacks", emoji: "🥐" },
  pop_tart: { name: "Pop-Tart (frosted)", calories: 200, protein: 2, carbs: 37, fat: 5, fiber: 0.5, serving: "1 pastry (50g)", category: "snacks", emoji: "🍰" },

  // ─────────────────── SNACKS & PROCESSED (extra) ───────────────────
  fruit_snacks: { name: "Fruit Snacks (gummy)", calories: 80, protein: 0, carbs: 19, fat: 0, fiber: 0, serving: "1 pouch (23g)", category: "snacks", emoji: "🍬" },
  rice_krispie_treat: { name: "Rice Krispie Treat", calories: 90, protein: 1, carbs: 17, fat: 2, fiber: 0, serving: "1 bar (22g)", category: "snacks", emoji: "🍬" },
  oreo: { name: "Oreo Cookies", calories: 160, protein: 1, carbs: 25, fat: 7, fiber: 0.5, serving: "3 cookies (34g)", category: "snacks", emoji: "🍪" },
  doritos: { name: "Doritos (Nacho Cheese)", calories: 140, protein: 2, carbs: 18, fat: 7, fiber: 1, serving: "1 oz (28g)", category: "snacks", emoji: "🥔" },
  cheetos: { name: "Cheetos (crunchy)", calories: 160, protein: 2, carbs: 15, fat: 10, fiber: 0, serving: "1 oz (28g)", category: "snacks", emoji: "🥔" },
  goldfish: { name: "Goldfish Crackers", calories: 140, protein: 3, carbs: 20, fat: 5, fiber: 1, serving: "55 pieces (30g)", category: "snacks", emoji: "🐟" },
  twizzlers: { name: "Twizzlers", calories: 120, protein: 1, carbs: 27, fat: 0.5, fiber: 0, serving: "4 pieces (45g)", category: "snacks", emoji: "🍬" },
  skittles: { name: "Skittles", calories: 170, protein: 0, carbs: 39, fat: 2, fiber: 0, serving: "1/4 cup (40g)", category: "snacks", emoji: "🌈" },
  m_and_m: { name: "M&M's (peanut)", calories: 220, protein: 4, carbs: 26, fat: 11, fiber: 1, serving: "1/4 cup (42g)", category: "snacks", emoji: "🍫" },
  reeses: { name: "Reese's Peanut Butter Cup", calories: 210, protein: 5, carbs: 24, fat: 12, fiber: 1, serving: "2 cups (42g)", category: "snacks", emoji: "🍫" },
  kit_kat: { name: "Kit Kat", calories: 218, protein: 3, carbs: 27, fat: 11, fiber: 0.5, serving: "1 bar (42g)", category: "snacks", emoji: "🍫" },
  twix: { name: "Twix", calories: 250, protein: 2, carbs: 34, fat: 12, fiber: 0.5, serving: "1 bar (50g)", category: "snacks", emoji: "🍫" },
  snickers_bar: { name: "Snickers", calories: 250, protein: 4, carbs: 33, fat: 12, fiber: 1, serving: "1 bar (52g)", category: "snacks", emoji: "🍫" },
  mars_bar: { name: "Mars Bar", calories: 228, protein: 2, carbs: 35, fat: 9, fiber: 0, serving: "1 bar (51g)", category: "snacks", emoji: "🍫" },
  ferrero_rocher: { name: "Ferrero Rocher", calories: 73, protein: 1, carbs: 6, fat: 5, fiber: 0.5, serving: "1 piece (12.5g)", category: "snacks", emoji: "🍫" },

  // ─────────────────── FROZEN MEALS ───────────────────
  frozen_pizza: { name: "Frozen Pizza (1/3 pie)", calories: 310, protein: 13, carbs: 36, fat: 13, fiber: 2, serving: "1/3 pizza (142g)", category: "prepared", emoji: "🍕" },
  hot_pocket: { name: "Hot Pocket (ham & cheese)", calories: 300, protein: 11, carbs: 35, fat: 13, fiber: 1, serving: "1 pocket (127g)", category: "prepared", emoji: "🥟" },
  frozen_burrito: { name: "Frozen Burrito (bean & cheese)", calories: 290, protein: 9, carbs: 43, fat: 9, fiber: 4, serving: "1 burrito (142g)", category: "prepared", emoji: "🌯" },
  tv_dinner: { name: "Frozen Dinner (chicken)", calories: 340, protein: 18, carbs: 42, fat: 12, fiber: 3, serving: "1 tray (283g)", category: "prepared", emoji: "🍽️" },
  frozen_waffles: { name: "Frozen Waffles (Eggo)", calories: 180, protein: 4, carbs: 30, fat: 6, fiber: 1, serving: "2 waffles (70g)", category: "grains", emoji: "🧇" },
  corn_dog: { name: "Corn Dog", calories: 230, protein: 7, carbs: 25, fat: 11, fiber: 1, serving: "1 corn dog (76g)", category: "prepared", emoji: "🌭" },
  tater_tots: { name: "Tater Tots", calories: 160, protein: 2, carbs: 20, fat: 8, fiber: 2, serving: "10 pieces (84g)", category: "prepared", emoji: "🥔" },
  fish_fingers: { name: "Fish Fingers (frozen)", calories: 224, protein: 12, carbs: 20, fat: 11, fiber: 0.5, serving: "4 sticks (112g)", category: "prepared", emoji: "🐟" },
  chicken_tenders: { name: "Chicken Tenders (frozen)", calories: 260, protein: 14, carbs: 16, fat: 16, fiber: 1, serving: "3 pieces (100g)", category: "prepared", emoji: "🍗" },
  pizza_roll: { name: "Pizza Rolls", calories: 210, protein: 6, carbs: 27, fat: 8, fiber: 1, serving: "6 rolls (85g)", category: "prepared", emoji: "🍕" },
  egg_roll: { name: "Egg Roll (frozen)", calories: 170, protein: 5, carbs: 22, fat: 7, fiber: 1, serving: "1 roll (85g)", category: "prepared", emoji: "🥟" },

  // ─────────────────── CANNED / PACKAGED ───────────────────
  canned_tuna_oil: { name: "Tuna (canned, in oil)", calories: 198, protein: 29, carbs: 0, fat: 8, fiber: 0, serving: "1 can drained (100g)", category: "protein", emoji: "🐟" },
  canned_salmon: { name: "Canned Salmon", calories: 208, protein: 28, carbs: 0, fat: 10, fiber: 0, serving: "1 can (100g)", category: "protein", emoji: "🐟" },
  canned_chicken: { name: "Canned Chicken Breast", calories: 120, protein: 26, carbs: 0, fat: 1.5, fiber: 0, serving: "100g drained", category: "protein", emoji: "🍗" },
  spam: { name: "SPAM", calories: 174, protein: 7, carbs: 2, fat: 15, fiber: 0, serving: "1 serving (56g)", category: "protein", emoji: "🍖" },
  vienna_sausage: { name: "Vienna Sausages", calories: 150, protein: 7, carbs: 1, fat: 13, fiber: 0, serving: "3 sausages (57g)", category: "protein", emoji: "🌭" },
  canned_soup_tomato: { name: "Canned Tomato Soup", calories: 100, protein: 2, carbs: 20, fat: 1, fiber: 2, serving: "1 cup prepared (248g)", category: "prepared", emoji: "🍲" },
  canned_chili: { name: "Canned Chili (with beans)", calories: 260, protein: 16, carbs: 25, fat: 10, fiber: 8, serving: "1 cup (253g)", category: "prepared", emoji: "🍲" },
  canned_ravioli: { name: "Canned Ravioli (Chef Boyardee)", calories: 230, protein: 8, carbs: 37, fat: 6, fiber: 2, serving: "1 cup (252g)", category: "prepared", emoji: "🍝" },
  instant_noodle: { name: "Cup Noodles (instant)", calories: 290, protein: 6, carbs: 38, fat: 12, fiber: 1, serving: "1 cup (64g dry)", category: "prepared", emoji: "🍜" },
  ramen_pack: { name: "Ramen Noodle Pack (Maruchan)", calories: 380, protein: 10, carbs: 52, fat: 14, fiber: 2, serving: "1 package (85g)", category: "prepared", emoji: "🍜" },
  mac_cheese_box: { name: "Mac & Cheese (box, prepared)", calories: 350, protein: 11, carbs: 48, fat: 14, fiber: 1, serving: "1 cup (200g)", category: "prepared", emoji: "🧀" },

  // ─────────────────── DELI / BAKERY ───────────────────
  bagel_cream_cheese: { name: "Bagel with Cream Cheese", calories: 380, protein: 12, carbs: 50, fat: 15, fiber: 2, serving: "1 bagel + 2 tbsp", category: "prepared", emoji: "🥯" },
  turkey_deli: { name: "Turkey Breast (deli sliced)", calories: 60, protein: 12, carbs: 1, fat: 0.5, fiber: 0, serving: "2 oz (56g)", category: "protein", emoji: "🦃" },
  ham_deli: { name: "Ham (deli sliced)", calories: 60, protein: 10, carbs: 2, fat: 1.5, fiber: 0, serving: "2 oz (56g)", category: "protein", emoji: "🍖" },
  roast_beef_deli: { name: "Roast Beef (deli sliced)", calories: 70, protein: 12, carbs: 0.5, fat: 2, fiber: 0, serving: "2 oz (56g)", category: "protein", emoji: "🥩" },
  pastrami: { name: "Pastrami", calories: 80, protein: 11, carbs: 1, fat: 3.5, fiber: 0, serving: "2 oz (56g)", category: "protein", emoji: "🥩" },
  smoked_turkey: { name: "Smoked Turkey Breast", calories: 50, protein: 10, carbs: 1, fat: 0.5, fiber: 0, serving: "2 oz (56g)", category: "protein", emoji: "🦃" },
  focaccia: { name: "Focaccia", calories: 135, protein: 4, carbs: 20, fat: 4, fiber: 1, serving: "1 piece (50g)", category: "grains", emoji: "🍞" },
  pretzel_soft: { name: "Soft Pretzel", calories: 389, protein: 10, carbs: 80, fat: 4, fiber: 2, serving: "1 large (135g)", category: "grains", emoji: "🥨" },
  corn_bread: { name: "Cornbread", calories: 173, protein: 4, carbs: 28, fat: 5, fiber: 1.5, serving: "1 piece (60g)", category: "grains", emoji: "🍞" },
  banana_bread: { name: "Banana Bread", calories: 196, protein: 3, carbs: 33, fat: 6, fiber: 1, serving: "1 slice (60g)", category: "snacks", emoji: "🍌" },
  coffee_cake: { name: "Coffee Cake", calories: 260, protein: 4, carbs: 38, fat: 11, fiber: 1, serving: "1 slice (80g)", category: "snacks", emoji: "🍰" },
  pound_cake: { name: "Pound Cake", calories: 293, protein: 4, carbs: 37, fat: 15, fiber: 0.3, serving: "1 slice (75g)", category: "snacks", emoji: "🍰" },
  carrot_cake: { name: "Carrot Cake (with frosting)", calories: 415, protein: 5, carbs: 52, fat: 22, fiber: 1, serving: "1 slice (110g)", category: "snacks", emoji: "🍰" },
  red_velvet_cake: { name: "Red Velvet Cake", calories: 370, protein: 4, carbs: 50, fat: 18, fiber: 1, serving: "1 slice (100g)", category: "snacks", emoji: "🍰" },

  // ─────────────────── SPREADS & EXTRAS ───────────────────
  cream_cheese_spread: { name: "Cream Cheese (spread)", calories: 50, protein: 1, carbs: 1, fat: 5, fiber: 0, serving: "1 tbsp (14g)", category: "dairy", emoji: "🧀" },
  hummus_roasted_garlic: { name: "Roasted Garlic Hummus", calories: 70, protein: 2, carbs: 5, fat: 5, fiber: 1, serving: "2 tbsp (28g)", category: "prepared", emoji: "🫘" },
  tzatziki: { name: "Tzatziki Sauce", calories: 35, protein: 2, carbs: 2, fat: 2, fiber: 0, serving: "2 tbsp (30g)", category: "condiments", emoji: "🥛" },
  chimichurri: { name: "Chimichurri", calories: 50, protein: 0, carbs: 1, fat: 5, fiber: 0.5, serving: "1 tbsp (15g)", category: "condiments", emoji: "🌿" },
  aioli: { name: "Aioli (garlic mayo)", calories: 100, protein: 0, carbs: 0.5, fat: 11, fiber: 0, serving: "1 tbsp (14g)", category: "condiments", emoji: "🧄" },
  harissa: { name: "Harissa Paste", calories: 15, protein: 0.5, carbs: 2, fat: 0.5, fiber: 0.5, serving: "1 tsp (5g)", category: "condiments", emoji: "🌶️" },
  chutney_mango: { name: "Mango Chutney", calories: 60, protein: 0, carbs: 15, fat: 0, fiber: 0.5, serving: "1 tbsp (20g)", category: "condiments", emoji: "🥭" },
  sauerkraut: { name: "Sauerkraut", calories: 14, protein: 0.6, carbs: 3, fat: 0.1, fiber: 1.8, serving: "1/2 cup (71g)", category: "vegetables", emoji: "🥬" },
  pickles: { name: "Dill Pickles", calories: 4, protein: 0.2, carbs: 1, fat: 0, fiber: 0.3, serving: "1 spear (35g)", category: "vegetables", emoji: "🥒" },
  olives_green: { name: "Green Olives", calories: 41, protein: 0.3, carbs: 1.1, fat: 4.3, fiber: 0.9, serving: "5 olives (25g)", category: "vegetables", emoji: "🫒" },
  olives_black: { name: "Black Olives", calories: 36, protein: 0.3, carbs: 2, fat: 3.2, fiber: 0.9, serving: "5 olives (25g)", category: "vegetables", emoji: "🫒" },
  capers: { name: "Capers", calories: 2, protein: 0.2, carbs: 0.4, fat: 0.1, fiber: 0.2, serving: "1 tbsp (9g)", category: "condiments", emoji: "🫒" },
  sun_dried_tomato: { name: "Sun-Dried Tomatoes", calories: 139, protein: 8, carbs: 30, fat: 1.5, fiber: 7, serving: "1/2 cup (54g)", category: "vegetables", emoji: "🍅" },
  roasted_peppers: { name: "Roasted Red Peppers (jarred)", calories: 10, protein: 0.4, carbs: 2, fat: 0, fiber: 0.5, serving: "2 tbsp (28g)", category: "vegetables", emoji: "🫑" },
  coconut_cream: { name: "Coconut Cream", calories: 200, protein: 2, carbs: 4, fat: 21, fiber: 0, serving: "1/4 cup (60g)", category: "dairy", emoji: "🥥" },
  condensed_milk: { name: "Sweetened Condensed Milk", calories: 130, protein: 3, carbs: 22, fat: 3, fiber: 0, serving: "2 tbsp (38g)", category: "dairy", emoji: "🥛" },
  evaporated_milk: { name: "Evaporated Milk", calories: 40, protein: 2, carbs: 3, fat: 2, fiber: 0, serving: "2 tbsp (30g)", category: "dairy", emoji: "🥛" },
};
