// Calorie calculation helpers

export function calculateBMR(weight: number, height: number, age: number, gender: string): number {
  // Mifflin-St Jeor Equation
  if (gender === "male") {
    return 10 * weight + 6.25 * height - 5 * age + 5;
  }
  return 10 * weight + 6.25 * height - 5 * age - 161;
}

export function calculateTDEE(bmr: number, activityLevel: string): number {
  const multipliers: Record<string, number> = {
    sedentary: 1.2,
    light: 1.375,
    moderate: 1.55,
    active: 1.725,
    very_active: 1.9,
  };
  return Math.round(bmr * (multipliers[activityLevel] || 1.55));
}

export function calculateDailyCalories(tdee: number, goal: string): number {
  switch (goal) {
    case "lose_weight":
      return Math.round(tdee - 500);
    case "gain_muscle":
      return Math.round(tdee + 300);
    default:
      return tdee;
  }
}

export function calculateBMI(weight: number, height: number): number {
  const heightM = height / 100;
  return Math.round((weight / (heightM * heightM)) * 10) / 10;
}

export function getMacroTargets(calories: number, goal: string) {
  switch (goal) {
    case "lose_weight":
      return {
        protein: Math.round((calories * 0.35) / 4),
        carbs: Math.round((calories * 0.35) / 4),
        fat: Math.round((calories * 0.30) / 9),
      };
    case "gain_muscle":
      return {
        protein: Math.round((calories * 0.30) / 4),
        carbs: Math.round((calories * 0.45) / 4),
        fat: Math.round((calories * 0.25) / 9),
      };
    default:
      return {
        protein: Math.round((calories * 0.25) / 4),
        carbs: Math.round((calories * 0.50) / 4),
        fat: Math.round((calories * 0.25) / 9),
      };
  }
}

// Re-export the food database from dedicated file
export { foodDatabase, type FoodItem } from "./food-db";

// Recipe database
export interface Recipe {
  id: string;
  name: string;
  category: "lose_weight" | "gain_muscle" | "balanced";
  mealType: "breakfast" | "lunch" | "dinner" | "snack";
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  prepTime: string;
  ingredients: string[];
  instructions: string[];
  imageUrl: string;
}

export const recipes: Recipe[] = [
  // ========== BREAKFAST RECIPES ==========
  {
    id: "b1",
    name: "Protein Pancakes",
    category: "gain_muscle",
    mealType: "breakfast",
    calories: 420,
    protein: 35,
    carbs: 45,
    fat: 12,
    prepTime: "15 min",
    ingredients: [
      "1 scoop protein powder",
      "1 banana",
      "2 eggs",
      "1/4 cup oats",
      "1 tsp baking powder",
      "Maple syrup (optional)",
    ],
    instructions: [
      "Blend banana, eggs, oats, protein powder, and baking powder",
      "Heat a non-stick pan over medium heat",
      "Pour batter to form pancakes",
      "Cook 2-3 min per side until golden",
      "Top with fresh berries or maple syrup",
    ],
    imageUrl: "https://images.pexels.com/photos/376464/pexels-photo-376464.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "b2",
    name: "Avocado Toast with Eggs",
    category: "balanced",
    mealType: "breakfast",
    calories: 380,
    protein: 18,
    carbs: 32,
    fat: 22,
    prepTime: "10 min",
    ingredients: [
      "2 slices whole wheat bread",
      "1 ripe avocado",
      "2 eggs",
      "Cherry tomatoes",
      "Salt, pepper, red pepper flakes",
      "Lemon juice",
    ],
    instructions: [
      "Toast bread until golden and crispy",
      "Mash avocado with lemon juice, salt, and pepper",
      "Poach or fry eggs to your preference",
      "Spread avocado on toast, top with eggs",
      "Garnish with tomatoes and red pepper flakes",
    ],
    imageUrl: "https://images.pexels.com/photos/1351238/pexels-photo-1351238.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "b3",
    name: "Greek Yogurt Parfait",
    category: "lose_weight",
    mealType: "breakfast",
    calories: 280,
    protein: 22,
    carbs: 35,
    fat: 6,
    prepTime: "5 min",
    ingredients: [
      "1 cup Greek yogurt (0% fat)",
      "1/2 cup mixed berries",
      "2 tbsp granola",
      "1 tbsp honey",
      "1 tbsp chia seeds",
    ],
    instructions: [
      "Layer half the yogurt in a glass or bowl",
      "Add half the berries and granola",
      "Repeat layers with remaining ingredients",
      "Drizzle with honey",
      "Top with chia seeds",
    ],
    imageUrl: "https://images.pexels.com/photos/1099680/pexels-photo-1099680.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "b4",
    name: "Overnight Protein Oats",
    category: "gain_muscle",
    mealType: "breakfast",
    calories: 480,
    protein: 30,
    carbs: 55,
    fat: 15,
    prepTime: "5 min + overnight",
    ingredients: [
      "1/2 cup rolled oats",
      "1 scoop protein powder",
      "1 cup Greek yogurt",
      "1 tbsp peanut butter",
      "Blueberries",
      "Chia seeds",
    ],
    instructions: [
      "Mix oats, protein powder, and yogurt in a jar",
      "Add a splash of milk to desired consistency",
      "Stir in chia seeds",
      "Refrigerate overnight",
      "Top with peanut butter and blueberries in the morning",
    ],
    imageUrl: "https://images.pexels.com/photos/6489713/pexels-photo-6489713.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "b5",
    name: "Veggie Egg White Omelette",
    category: "lose_weight",
    mealType: "breakfast",
    calories: 220,
    protein: 24,
    carbs: 12,
    fat: 8,
    prepTime: "12 min",
    ingredients: [
      "4 egg whites",
      "1/4 cup spinach",
      "1/4 cup mushrooms",
      "1/4 cup bell peppers",
      "2 tbsp feta cheese",
      "Fresh herbs",
    ],
    instructions: [
      "Whisk egg whites with salt and pepper",
      "Sauté vegetables in a non-stick pan",
      "Pour egg whites over vegetables",
      "Cook until set, fold in half",
      "Top with feta and fresh herbs",
    ],
    imageUrl: "https://images.pexels.com/photos/566566/pexels-photo-566566.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "b6",
    name: "Smoothie Bowl",
    category: "balanced",
    mealType: "breakfast",
    calories: 350,
    protein: 15,
    carbs: 55,
    fat: 10,
    prepTime: "8 min",
    ingredients: [
      "1 frozen banana",
      "1/2 cup frozen berries",
      "1/2 cup almond milk",
      "2 tbsp almond butter",
      "Toppings: granola, coconut, seeds",
    ],
    instructions: [
      "Blend frozen fruits with almond milk until thick",
      "Pour into a bowl",
      "Add almond butter",
      "Top with granola, coconut flakes, and seeds",
      "Serve immediately",
    ],
    imageUrl: "https://images.pexels.com/photos/1092730/pexels-photo-1092730.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "b7",
    name: "Breakfast Burrito",
    category: "gain_muscle",
    mealType: "breakfast",
    calories: 520,
    protein: 32,
    carbs: 45,
    fat: 24,
    prepTime: "15 min",
    ingredients: [
      "2 whole eggs + 2 egg whites",
      "1 large tortilla",
      "1/4 cup black beans",
      "2 tbsp cheese",
      "Salsa and avocado",
      "Turkey bacon (2 strips)",
    ],
    instructions: [
      "Cook turkey bacon until crispy",
      "Scramble eggs with salt and pepper",
      "Warm tortilla in a pan",
      "Layer eggs, beans, bacon, cheese",
      "Add salsa and avocado, roll up tight",
    ],
    imageUrl: "https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "b8",
    name: "Cottage Cheese Bowl",
    category: "lose_weight",
    mealType: "breakfast",
    calories: 250,
    protein: 28,
    carbs: 20,
    fat: 6,
    prepTime: "5 min",
    ingredients: [
      "1 cup low-fat cottage cheese",
      "1/2 cup pineapple chunks",
      "1 tbsp honey",
      "2 tbsp walnuts",
      "Cinnamon",
    ],
    instructions: [
      "Place cottage cheese in a bowl",
      "Add pineapple chunks on top",
      "Drizzle with honey",
      "Sprinkle walnuts and cinnamon",
      "Enjoy cold",
    ],
    imageUrl: "https://images.pexels.com/photos/1640773/pexels-photo-1640773.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "b9",
    name: "Banana Nut Oatmeal",
    category: "balanced",
    mealType: "breakfast",
    calories: 380,
    protein: 12,
    carbs: 58,
    fat: 14,
    prepTime: "10 min",
    ingredients: [
      "1/2 cup rolled oats",
      "1 cup milk",
      "1 banana, sliced",
      "2 tbsp walnuts",
      "1 tbsp honey",
      "Cinnamon",
    ],
    instructions: [
      "Cook oats with milk according to package",
      "Stir in half the banana while cooking",
      "Transfer to bowl",
      "Top with remaining banana, walnuts",
      "Drizzle honey and add cinnamon",
    ],
    imageUrl: "https://images.pexels.com/photos/1333746/pexels-photo-1333746.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "b10",
    name: "Shakshuka",
    category: "balanced",
    mealType: "breakfast",
    calories: 320,
    protein: 18,
    carbs: 25,
    fat: 18,
    prepTime: "25 min",
    ingredients: [
      "3 eggs",
      "1 can diced tomatoes",
      "1/2 onion, diced",
      "1 bell pepper",
      "Cumin, paprika, garlic",
      "Fresh parsley, feta",
    ],
    instructions: [
      "Sauté onion and pepper until soft",
      "Add spices and garlic, cook 1 min",
      "Pour in tomatoes, simmer 10 min",
      "Make wells, crack eggs into sauce",
      "Cover and cook until eggs set",
    ],
    imageUrl: "https://images.pexels.com/photos/6294361/pexels-photo-6294361.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },

  // ========== LUNCH RECIPES ==========
  {
    id: "l1",
    name: "Grilled Chicken Salad",
    category: "lose_weight",
    mealType: "lunch",
    calories: 350,
    protein: 35,
    carbs: 15,
    fat: 18,
    prepTime: "20 min",
    ingredients: [
      "150g chicken breast",
      "2 cups mixed greens",
      "1/2 avocado",
      "Cherry tomatoes",
      "Cucumber",
      "Olive oil & lemon dressing",
    ],
    instructions: [
      "Season chicken breast with salt, pepper, and herbs",
      "Grill chicken for 6-7 minutes each side",
      "Prepare salad base with greens, tomatoes, and cucumber",
      "Slice chicken and place on top",
      "Add avocado slices and drizzle with dressing",
    ],
    imageUrl: "https://images.pexels.com/photos/29138860/pexels-photo-29138860.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "l2",
    name: "Protein Power Bowl",
    category: "gain_muscle",
    mealType: "lunch",
    calories: 650,
    protein: 45,
    carbs: 60,
    fat: 22,
    prepTime: "25 min",
    ingredients: [
      "200g chicken breast",
      "1 cup brown rice",
      "1/2 cup black beans",
      "1/2 avocado",
      "Salsa",
      "Corn",
    ],
    instructions: [
      "Cook brown rice according to package directions",
      "Season and grill chicken breast",
      "Heat black beans with cumin and garlic",
      "Assemble bowl with rice base, sliced chicken",
      "Top with beans, avocado, corn, and salsa",
    ],
    imageUrl: "https://images.pexels.com/photos/7627437/pexels-photo-7627437.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "l3",
    name: "Mediterranean Quinoa Bowl",
    category: "balanced",
    mealType: "lunch",
    calories: 450,
    protein: 18,
    carbs: 52,
    fat: 20,
    prepTime: "25 min",
    ingredients: [
      "1 cup cooked quinoa",
      "1/2 cup chickpeas",
      "Cucumber, tomatoes, red onion",
      "Feta cheese",
      "Kalamata olives",
      "Tzatziki sauce",
    ],
    instructions: [
      "Cook quinoa and let cool slightly",
      "Dice cucumber, tomatoes, and red onion",
      "Combine quinoa with vegetables and chickpeas",
      "Top with feta and olives",
      "Drizzle with tzatziki",
    ],
    imageUrl: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "l4",
    name: "Turkey Lettuce Wraps",
    category: "lose_weight",
    mealType: "lunch",
    calories: 280,
    protein: 28,
    carbs: 12,
    fat: 14,
    prepTime: "15 min",
    ingredients: [
      "200g ground turkey",
      "Butter lettuce leaves",
      "Water chestnuts",
      "Soy sauce",
      "Ginger & garlic",
      "Green onions",
    ],
    instructions: [
      "Cook ground turkey with ginger and garlic",
      "Add diced water chestnuts and soy sauce",
      "Cook until turkey is browned and flavored",
      "Spoon mixture into lettuce cups",
      "Garnish with green onions",
    ],
    imageUrl: "https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "l5",
    name: "Tuna Poke Bowl",
    category: "balanced",
    mealType: "lunch",
    calories: 420,
    protein: 32,
    carbs: 45,
    fat: 14,
    prepTime: "20 min",
    ingredients: [
      "150g fresh tuna, cubed",
      "1 cup sushi rice",
      "Edamame",
      "Avocado",
      "Soy sauce, sesame oil",
      "Sesame seeds, nori",
    ],
    instructions: [
      "Cook sushi rice and let cool",
      "Marinate tuna in soy sauce and sesame oil",
      "Place rice in bowl",
      "Top with tuna, edamame, avocado",
      "Garnish with sesame seeds and nori strips",
    ],
    imageUrl: "https://images.pexels.com/photos/3763816/pexels-photo-3763816.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "l6",
    name: "Chicken Caesar Wrap",
    category: "balanced",
    mealType: "lunch",
    calories: 480,
    protein: 35,
    carbs: 38,
    fat: 22,
    prepTime: "15 min",
    ingredients: [
      "150g grilled chicken breast",
      "1 large tortilla",
      "Romaine lettuce",
      "Parmesan cheese",
      "Caesar dressing (light)",
      "Croutons",
    ],
    instructions: [
      "Slice grilled chicken into strips",
      "Chop romaine lettuce",
      "Toss lettuce with dressing and parmesan",
      "Place on tortilla with chicken",
      "Add croutons and roll tightly",
    ],
    imageUrl: "https://images.pexels.com/photos/2097090/pexels-photo-2097090.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "l7",
    name: "Asian Beef Salad",
    category: "gain_muscle",
    mealType: "lunch",
    calories: 420,
    protein: 38,
    carbs: 18,
    fat: 22,
    prepTime: "20 min",
    ingredients: [
      "150g flank steak",
      "Mixed Asian greens",
      "Carrot, cucumber ribbons",
      "Fresh mint, cilantro",
      "Lime-chili dressing",
      "Crushed peanuts",
    ],
    instructions: [
      "Grill steak to medium-rare, let rest",
      "Prepare vegetable ribbons with peeler",
      "Toss greens with herbs and vegetables",
      "Slice steak against the grain",
      "Top salad with steak, dressing, peanuts",
    ],
    imageUrl: "https://images.pexels.com/photos/1640776/pexels-photo-1640776.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "l8",
    name: "Lentil Soup",
    category: "lose_weight",
    mealType: "lunch",
    calories: 320,
    protein: 18,
    carbs: 45,
    fat: 8,
    prepTime: "35 min",
    ingredients: [
      "1 cup red lentils",
      "1 onion, carrots, celery",
      "4 cups vegetable broth",
      "Cumin, turmeric, garlic",
      "Lemon juice",
      "Fresh parsley",
    ],
    instructions: [
      "Sauté onion, carrots, celery until soft",
      "Add garlic and spices, cook 1 min",
      "Add lentils and broth, bring to boil",
      "Simmer 25 min until lentils are tender",
      "Blend partially, add lemon juice",
    ],
    imageUrl: "https://images.pexels.com/photos/539451/pexels-photo-539451.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },

  // ========== DINNER RECIPES ==========
  {
    id: "d1",
    name: "Salmon & Quinoa Bowl",
    category: "balanced",
    mealType: "dinner",
    calories: 520,
    protein: 35,
    carbs: 45,
    fat: 20,
    prepTime: "30 min",
    ingredients: [
      "150g salmon fillet",
      "1 cup quinoa",
      "Steamed broccoli",
      "Sweet potato cubes",
      "Soy sauce & ginger glaze",
    ],
    instructions: [
      "Cook quinoa and set aside",
      "Roast sweet potato cubes at 200°C for 20 min",
      "Pan-sear salmon for 4 min each side",
      "Steam broccoli until tender",
      "Assemble bowl and drizzle with glaze",
    ],
    imageUrl: "https://images.pexels.com/photos/6489563/pexels-photo-6489563.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "d2",
    name: "Grilled Steak & Vegetables",
    category: "gain_muscle",
    mealType: "dinner",
    calories: 580,
    protein: 45,
    carbs: 25,
    fat: 35,
    prepTime: "25 min",
    ingredients: [
      "200g ribeye steak",
      "Asparagus",
      "Cherry tomatoes",
      "Garlic butter",
      "Fresh rosemary",
      "Baked potato",
    ],
    instructions: [
      "Bring steak to room temperature",
      "Season with salt, pepper, rosemary",
      "Grill 4-5 min per side for medium",
      "Rest 5 minutes before slicing",
      "Serve with grilled vegetables and potato",
    ],
    imageUrl: "https://images.pexels.com/photos/3535383/pexels-photo-3535383.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "d3",
    name: "Chicken Stir-Fry",
    category: "lose_weight",
    mealType: "dinner",
    calories: 380,
    protein: 35,
    carbs: 30,
    fat: 14,
    prepTime: "20 min",
    ingredients: [
      "200g chicken breast, sliced",
      "Broccoli, snap peas, bell peppers",
      "Garlic, ginger",
      "Low-sodium soy sauce",
      "Sesame oil",
      "Brown rice (optional)",
    ],
    instructions: [
      "Heat wok or large pan over high heat",
      "Stir-fry chicken until cooked, set aside",
      "Stir-fry vegetables 3-4 minutes",
      "Add garlic, ginger, soy sauce",
      "Return chicken, toss together",
    ],
    imageUrl: "https://images.pexels.com/photos/262897/pexels-photo-262897.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "d4",
    name: "Baked Cod with Vegetables",
    category: "lose_weight",
    mealType: "dinner",
    calories: 320,
    protein: 35,
    carbs: 20,
    fat: 12,
    prepTime: "30 min",
    ingredients: [
      "200g cod fillet",
      "Zucchini, cherry tomatoes",
      "Lemon slices",
      "Fresh dill, capers",
      "Olive oil",
      "White wine (optional)",
    ],
    instructions: [
      "Preheat oven to 200°C",
      "Place cod on foil with vegetables",
      "Season and add lemon, dill, capers",
      "Drizzle olive oil, fold foil to seal",
      "Bake 18-20 minutes until fish flakes",
    ],
    imageUrl: "https://images.pexels.com/photos/3655916/pexels-photo-3655916.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "d5",
    name: "Turkey Meatballs & Zoodles",
    category: "lose_weight",
    mealType: "dinner",
    calories: 350,
    protein: 32,
    carbs: 18,
    fat: 18,
    prepTime: "30 min",
    ingredients: [
      "200g ground turkey",
      "2 zucchinis, spiralized",
      "Marinara sauce (low sugar)",
      "Italian herbs",
      "Parmesan cheese",
      "Fresh basil",
    ],
    instructions: [
      "Mix turkey with herbs, form meatballs",
      "Bake meatballs at 200°C for 20 min",
      "Heat marinara sauce in a pan",
      "Sauté zoodles 2-3 minutes",
      "Serve zoodles with meatballs and sauce",
    ],
    imageUrl: "https://images.pexels.com/photos/1373915/pexels-photo-1373915.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "d6",
    name: "Teriyaki Salmon Bowl",
    category: "balanced",
    mealType: "dinner",
    calories: 550,
    protein: 38,
    carbs: 52,
    fat: 22,
    prepTime: "25 min",
    ingredients: [
      "150g salmon fillet",
      "1 cup jasmine rice",
      "Teriyaki sauce",
      "Steamed bok choy",
      "Pickled ginger, sesame seeds",
      "Sliced avocado",
    ],
    instructions: [
      "Cook rice according to package",
      "Brush salmon with teriyaki, bake 12 min",
      "Steam bok choy until tender",
      "Assemble bowl with rice base",
      "Top with salmon, bok choy, avocado",
    ],
    imageUrl: "https://images.pexels.com/photos/1516415/pexels-photo-1516415.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "d7",
    name: "Lean Beef Tacos",
    category: "balanced",
    mealType: "dinner",
    calories: 450,
    protein: 30,
    carbs: 40,
    fat: 20,
    prepTime: "20 min",
    ingredients: [
      "150g lean ground beef",
      "Corn tortillas (3)",
      "Taco seasoning",
      "Lettuce, tomato, onion",
      "Greek yogurt (sour cream sub)",
      "Lime, cilantro",
    ],
    instructions: [
      "Brown beef with taco seasoning",
      "Warm tortillas in a dry pan",
      "Dice vegetables for toppings",
      "Assemble tacos with beef and veggies",
      "Top with yogurt, cilantro, lime squeeze",
    ],
    imageUrl: "https://images.pexels.com/photos/4958641/pexels-photo-4958641.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "d8",
    name: "Stuffed Bell Peppers",
    category: "balanced",
    mealType: "dinner",
    calories: 420,
    protein: 28,
    carbs: 35,
    fat: 18,
    prepTime: "45 min",
    ingredients: [
      "4 bell peppers",
      "150g ground turkey",
      "1/2 cup cooked rice",
      "Black beans",
      "Tomato sauce",
      "Cheese, cilantro",
    ],
    instructions: [
      "Cut tops off peppers, remove seeds",
      "Brown turkey with onion and garlic",
      "Mix with rice, beans, half the sauce",
      "Stuff peppers, top with remaining sauce",
      "Bake at 180°C for 30 min, add cheese",
    ],
    imageUrl: "https://images.pexels.com/photos/5907618/pexels-photo-5907618.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "d9",
    name: "Shrimp Pasta",
    category: "gain_muscle",
    mealType: "dinner",
    calories: 580,
    protein: 35,
    carbs: 60,
    fat: 22,
    prepTime: "25 min",
    ingredients: [
      "200g shrimp",
      "200g whole wheat pasta",
      "Cherry tomatoes",
      "Garlic, white wine",
      "Fresh basil",
      "Parmesan, olive oil",
    ],
    instructions: [
      "Cook pasta al dente",
      "Sauté garlic in olive oil",
      "Add shrimp, cook until pink",
      "Add tomatoes, wine, simmer 3 min",
      "Toss with pasta, basil, parmesan",
    ],
    imageUrl: "https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "d10",
    name: "Chicken Curry",
    category: "balanced",
    mealType: "dinner",
    calories: 480,
    protein: 35,
    carbs: 45,
    fat: 18,
    prepTime: "35 min",
    ingredients: [
      "200g chicken thigh, cubed",
      "1 can coconut milk (light)",
      "Curry paste",
      "Bell peppers, onion",
      "Basmati rice",
      "Fresh cilantro",
    ],
    instructions: [
      "Sauté onion and peppers",
      "Add curry paste, cook 1 min",
      "Add chicken, cook until browned",
      "Pour in coconut milk, simmer 20 min",
      "Serve over rice with cilantro",
    ],
    imageUrl: "https://images.pexels.com/photos/2474661/pexels-photo-2474661.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "d11",
    name: "Herb Roasted Chicken",
    category: "gain_muscle",
    mealType: "dinner",
    calories: 520,
    protein: 48,
    carbs: 20,
    fat: 28,
    prepTime: "50 min",
    ingredients: [
      "2 chicken thighs (bone-in)",
      "Potatoes, quartered",
      "Lemon, rosemary, thyme",
      "Garlic cloves",
      "Olive oil",
      "Green beans",
    ],
    instructions: [
      "Preheat oven to 200°C",
      "Season chicken with herbs, lemon zest",
      "Arrange with potatoes and garlic",
      "Roast 40 min until golden",
      "Add steamed green beans to serve",
    ],
    imageUrl: "https://images.pexels.com/photos/2338407/pexels-photo-2338407.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "d12",
    name: "Vegetable Tofu Stir-Fry",
    category: "lose_weight",
    mealType: "dinner",
    calories: 320,
    protein: 22,
    carbs: 28,
    fat: 16,
    prepTime: "20 min",
    ingredients: [
      "200g firm tofu, cubed",
      "Mixed vegetables",
      "Garlic, ginger",
      "Low-sodium soy sauce",
      "Sesame oil",
      "Brown rice (optional)",
    ],
    instructions: [
      "Press tofu and cube",
      "Fry tofu until golden, set aside",
      "Stir-fry vegetables with garlic, ginger",
      "Add tofu and sauce",
      "Serve over brown rice",
    ],
    imageUrl: "https://images.pexels.com/photos/1438672/pexels-photo-1438672.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },

  // ========== SNACK RECIPES ==========
  {
    id: "s1",
    name: "Protein Energy Balls",
    category: "gain_muscle",
    mealType: "snack",
    calories: 180,
    protein: 12,
    carbs: 18,
    fat: 8,
    prepTime: "15 min",
    ingredients: [
      "1 cup oats",
      "1/2 cup peanut butter",
      "1 scoop protein powder",
      "2 tbsp honey",
      "Dark chocolate chips",
    ],
    instructions: [
      "Mix all ingredients in a bowl",
      "Refrigerate 30 min to firm up",
      "Roll into 12 balls",
      "Store in refrigerator",
      "Grab and go!",
    ],
    imageUrl: "https://images.pexels.com/photos/3622643/pexels-photo-3622643.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "s2",
    name: "Apple & Almond Butter",
    category: "balanced",
    mealType: "snack",
    calories: 200,
    protein: 5,
    carbs: 28,
    fat: 10,
    prepTime: "5 min",
    ingredients: [
      "1 medium apple",
      "2 tbsp almond butter",
      "Cinnamon",
      "Hemp seeds (optional)",
    ],
    instructions: [
      "Core and slice apple",
      "Arrange on plate",
      "Add almond butter for dipping",
      "Sprinkle with cinnamon and hemp seeds",
    ],
    imageUrl: "https://images.pexels.com/photos/4110258/pexels-photo-4110258.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "s3",
    name: "Greek Yogurt & Berries",
    category: "lose_weight",
    mealType: "snack",
    calories: 150,
    protein: 15,
    carbs: 18,
    fat: 2,
    prepTime: "3 min",
    ingredients: [
      "150g Greek yogurt (0%)",
      "1/2 cup mixed berries",
      "1 tsp honey",
      "Mint leaves",
    ],
    instructions: [
      "Place yogurt in a bowl",
      "Top with fresh berries",
      "Drizzle with honey",
      "Garnish with mint",
    ],
    imageUrl: "https://images.pexels.com/photos/1153369/pexels-photo-1153369.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "s4",
    name: "Veggie Sticks & Hummus",
    category: "lose_weight",
    mealType: "snack",
    calories: 160,
    protein: 6,
    carbs: 18,
    fat: 8,
    prepTime: "5 min",
    ingredients: [
      "Carrots, celery, cucumber",
      "Bell pepper strips",
      "1/4 cup hummus",
      "Paprika for garnish",
    ],
    instructions: [
      "Cut vegetables into sticks",
      "Arrange around hummus",
      "Sprinkle paprika on hummus",
      "Dip and enjoy!",
    ],
    imageUrl: "https://images.pexels.com/photos/1640771/pexels-photo-1640771.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "s5",
    name: "Cottage Cheese & Pineapple",
    category: "gain_muscle",
    mealType: "snack",
    calories: 180,
    protein: 20,
    carbs: 15,
    fat: 4,
    prepTime: "3 min",
    ingredients: [
      "1 cup cottage cheese",
      "1/2 cup pineapple chunks",
      "Coconut flakes",
      "Macadamia nuts (optional)",
    ],
    instructions: [
      "Place cottage cheese in bowl",
      "Add pineapple chunks",
      "Top with coconut flakes",
      "Add nuts for crunch",
    ],
    imageUrl: "https://images.pexels.com/photos/1092730/pexels-photo-1092730.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "s6",
    name: "Trail Mix",
    category: "gain_muscle",
    mealType: "snack",
    calories: 220,
    protein: 8,
    carbs: 20,
    fat: 14,
    prepTime: "2 min",
    ingredients: [
      "Almonds",
      "Walnuts",
      "Dark chocolate chips",
      "Dried cranberries",
      "Pumpkin seeds",
    ],
    instructions: [
      "Mix all ingredients together",
      "Portion into 1/4 cup servings",
      "Store in airtight container",
      "Perfect for on-the-go",
    ],
    imageUrl: "https://images.pexels.com/photos/1295572/pexels-photo-1295572.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "s7",
    name: "Rice Cakes with Avocado",
    category: "balanced",
    mealType: "snack",
    calories: 170,
    protein: 4,
    carbs: 20,
    fat: 10,
    prepTime: "5 min",
    ingredients: [
      "2 rice cakes",
      "1/2 avocado",
      "Everything bagel seasoning",
      "Lime juice",
      "Cherry tomatoes",
    ],
    instructions: [
      "Mash avocado with lime juice",
      "Spread on rice cakes",
      "Add sliced tomatoes",
      "Sprinkle with seasoning",
    ],
    imageUrl: "https://images.pexels.com/photos/1351238/pexels-photo-1351238.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "s8",
    name: "Edamame",
    category: "lose_weight",
    mealType: "snack",
    calories: 120,
    protein: 12,
    carbs: 10,
    fat: 5,
    prepTime: "5 min",
    ingredients: [
      "1 cup edamame in pods",
      "Sea salt",
      "Chili flakes (optional)",
      "Lime zest",
    ],
    instructions: [
      "Steam or microwave edamame",
      "Drain excess water",
      "Season with salt and chili",
      "Add lime zest and enjoy",
    ],
    imageUrl: "https://images.pexels.com/photos/3872434/pexels-photo-3872434.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "s9",
    name: "Protein Smoothie",
    category: "gain_muscle",
    mealType: "snack",
    calories: 280,
    protein: 30,
    carbs: 25,
    fat: 8,
    prepTime: "5 min",
    ingredients: [
      "1 scoop whey protein",
      "1 banana",
      "1 cup almond milk",
      "1 tbsp peanut butter",
      "Ice cubes",
    ],
    instructions: [
      "Add all ingredients to blender",
      "Blend until smooth",
      "Add more milk if too thick",
      "Pour and enjoy immediately",
    ],
    imageUrl: "https://images.pexels.com/photos/3625372/pexels-photo-3625372.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "s10",
    name: "Dark Chocolate & Almonds",
    category: "balanced",
    mealType: "snack",
    calories: 200,
    protein: 5,
    carbs: 15,
    fat: 15,
    prepTime: "1 min",
    ingredients: [
      "1 oz dark chocolate (70%+)",
      "15 almonds",
    ],
    instructions: [
      "Break chocolate into squares",
      "Pair with almonds",
      "Savor slowly",
      "Rich in antioxidants!",
    ],
    imageUrl: "https://images.pexels.com/photos/918327/pexels-photo-918327.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "s11",
    name: "Cucumber Tuna Bites",
    category: "lose_weight",
    mealType: "snack",
    calories: 140,
    protein: 18,
    carbs: 5,
    fat: 6,
    prepTime: "10 min",
    ingredients: [
      "1 cucumber",
      "1 can tuna (in water)",
      "Greek yogurt",
      "Dill, lemon juice",
      "Everything seasoning",
    ],
    instructions: [
      "Slice cucumber into thick rounds",
      "Mix tuna with yogurt, dill, lemon",
      "Spoon mixture onto cucumber",
      "Top with seasoning",
    ],
    imageUrl: "https://images.pexels.com/photos/1656663/pexels-photo-1656663.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "s12",
    name: "Frozen Banana Bites",
    category: "balanced",
    mealType: "snack",
    calories: 160,
    protein: 4,
    carbs: 22,
    fat: 8,
    prepTime: "10 min + freeze",
    ingredients: [
      "2 bananas",
      "Dark chocolate, melted",
      "Crushed peanuts",
      "Coconut flakes",
    ],
    instructions: [
      "Slice bananas into coins",
      "Dip in melted chocolate",
      "Sprinkle with toppings",
      "Freeze for 1 hour",
    ],
    imageUrl: "https://images.pexels.com/photos/2373520/pexels-photo-2373520.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "s13",
    name: "Caprese Skewers",
    category: "balanced",
    mealType: "snack",
    calories: 150,
    protein: 8,
    carbs: 6,
    fat: 12,
    prepTime: "10 min",
    ingredients: [
      "Cherry tomatoes",
      "Fresh mozzarella balls",
      "Fresh basil leaves",
      "Balsamic glaze",
      "Olive oil",
    ],
    instructions: [
      "Thread tomato, basil, mozzarella on picks",
      "Arrange on plate",
      "Drizzle with olive oil",
      "Finish with balsamic glaze",
    ],
    imageUrl: "https://images.pexels.com/photos/2087748/pexels-photo-2087748.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "s14",
    name: "Roasted Chickpeas",
    category: "lose_weight",
    mealType: "snack",
    calories: 130,
    protein: 7,
    carbs: 20,
    fat: 3,
    prepTime: "35 min",
    ingredients: [
      "1 can chickpeas, drained",
      "Olive oil spray",
      "Cumin, paprika, garlic",
      "Salt",
    ],
    instructions: [
      "Dry chickpeas thoroughly",
      "Toss with oil and spices",
      "Spread on baking sheet",
      "Roast at 200°C for 30 min",
      "Shake pan halfway through",
    ],
    imageUrl: "https://images.pexels.com/photos/6824476/pexels-photo-6824476.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "q1",
    name: "Bowl Thon-Riz Express",
    category: "lose_weight",
    mealType: "lunch",
    calories: 380,
    protein: 34,
    carbs: 42,
    fat: 8,
    prepTime: "8 min",
    ingredients: ["1 boîte de thon au naturel", "150g riz cuit (ou reste de la veille)", "1/2 concombre", "1 c.à.s sauce soja", "Graines de sésame"],
    instructions: [
      "Égoutter le thon",
      "Mélanger avec le riz chaud ou froid",
      "Couper le concombre en dés, ajouter",
      "Assaisonner avec la sauce soja et les graines de sésame",
    ],
    imageUrl: "",
  },
  {
    id: "q2",
    name: "Omelette Express aux Épinards",
    category: "gain_muscle",
    mealType: "breakfast",
    calories: 420,
    protein: 30,
    carbs: 6,
    fat: 30,
    prepTime: "6 min",
    ingredients: ["3 œufs", "Poignée d'épinards frais", "30g fromage râpé", "Sel, poivre", "1 c.à.c huile d'olive"],
    instructions: [
      "Battre les œufs, saler, poivrer",
      "Faire revenir les épinards 1 min dans l'huile",
      "Verser les œufs, ajouter le fromage",
      "Cuire 3-4 min à feu moyen, plier en deux",
    ],
    imageUrl: "",
  },
  {
    id: "q3",
    name: "Skyr Fruits & Granola (Petit Budget)",
    category: "balanced",
    mealType: "breakfast",
    calories: 320,
    protein: 22,
    carbs: 40,
    fat: 6,
    prepTime: "3 min",
    ingredients: ["1 pot de skyr ou fromage blanc 0%", "1 banane ou fruits de saison", "3 c.à.s granola ou flocons d'avoine", "1 c.à.c miel (optionnel)"],
    instructions: [
      "Verser le skyr dans un bol",
      "Couper les fruits par-dessus",
      "Ajouter le granola et le miel",
    ],
    imageUrl: "",
  },
  {
    id: "q4",
    name: "Wrap Poulet-Crudités (À emporter)",
    category: "lose_weight",
    mealType: "lunch",
    calories: 410,
    protein: 32,
    carbs: 38,
    fat: 12,
    prepTime: "10 min",
    ingredients: ["1 galette de blé complet", "120g blanc de poulet cuit (ou rôtisserie)", "Salade, tomate, carotte râpée", "1 c.à.s sauce yaourt-citron"],
    instructions: [
      "Étaler la sauce sur la galette",
      "Garnir de poulet et crudités",
      "Rouler serré et couper en deux",
    ],
    imageUrl: "",
  },
  {
    id: "q5",
    name: "Pâtes Lentilles Corail (Végé, riche en protéines)",
    category: "gain_muscle",
    mealType: "dinner",
    calories: 520,
    protein: 26,
    carbs: 78,
    fat: 10,
    prepTime: "20 min",
    ingredients: ["100g lentilles corail", "80g pâtes complètes", "1 oignon", "1 boîte tomates concassées", "Épices (cumin, paprika)"],
    instructions: [
      "Faire revenir l'oignon",
      "Ajouter les tomates et les lentilles, couvrir d'eau",
      "Mijoter 15 min",
      "Cuire les pâtes à part, mélanger, épicer",
    ],
    imageUrl: "",
  },
  {
    id: "q6",
    name: "Toast Avocat-Œuf Poché",
    category: "balanced",
    mealType: "breakfast",
    calories: 380,
    protein: 18,
    carbs: 30,
    fat: 22,
    prepTime: "10 min",
    ingredients: ["2 tranches pain complet", "1/2 avocat", "1 œuf", "Jus de citron, sel, poivre, piment"],
    instructions: [
      "Toaster le pain",
      "Écraser l'avocat avec citron/sel, étaler",
      "Pocher l'œuf 3 min dans l'eau frémissante",
      "Déposer sur le toast, poivrer",
    ],
    imageUrl: "",
  },
  {
    id: "q7",
    name: "Smoothie Post-Training",
    category: "gain_muscle",
    mealType: "snack",
    calories: 340,
    protein: 28,
    carbs: 40,
    fat: 6,
    prepTime: "4 min",
    ingredients: ["1 banane", "250ml lait (ou végétal)", "1 dose whey ou 2 c.à.s poudre de protéine", "1 c.à.s beurre de cacahuète"],
    instructions: [
      "Mettre tous les ingrédients dans un blender",
      "Mixer 30-45 sec jusqu'à texture lisse",
    ],
    imageUrl: "",
  },
  {
    id: "q8",
    name: "Soupe Miso Tofu-Légumes",
    category: "lose_weight",
    mealType: "dinner",
    calories: 250,
    protein: 16,
    carbs: 18,
    fat: 10,
    prepTime: "12 min",
    ingredients: ["500ml bouillon", "1 c.à.s pâte miso", "100g tofu ferme en dés", "Champignons, algues wakame, oignon vert"],
    instructions: [
      "Chauffer le bouillon sans bouillir",
      "Délayer le miso à part avec un peu de bouillon chaud",
      "Ajouter tofu et légumes, réincorporer le miso",
      "Servir avec oignon vert",
    ],
    imageUrl: "",
  },
];

// Exercise database with SVG animation paths
export interface Exercise {
  id: string;
  name: string;
  category: "lose_weight" | "gain_muscle" | "flexibility" | "cardio";
  muscleGroup: string;
  difficulty: "beginner" | "intermediate" | "advanced";
  caloriesBurned: number;
  duration: string;
  sets?: string;
  reps?: string;
  description: string;
  instructions: string[];
  emoji: string;
  animationType: "squat" | "pushup" | "plank" | "lunge" | "crunch" | "jumping" | "running" | "cycling" | "yoga" | "pullup" | "deadlift" | "burpee";
}

export const exercises: Exercise[] = [
  {
    id: "1",
    name: "Running / Jogging",
    category: "cardio",
    muscleGroup: "Full Body",
    difficulty: "beginner",
    caloriesBurned: 300,
    duration: "30 min",
    description: "Classic cardio exercise that burns significant calories and improves cardiovascular health.",
    instructions: [
      "Start with a 5-minute warm-up walk",
      "Gradually increase pace to a comfortable jog",
      "Maintain steady breathing rhythm",
      "Cool down with 5-minute walk",
    ],
    emoji: "🏃",
    animationType: "running",
  },
  {
    id: "2",
    name: "Push-Ups",
    category: "gain_muscle",
    muscleGroup: "Chest, Shoulders, Triceps",
    difficulty: "beginner",
    caloriesBurned: 100,
    duration: "15 min",
    sets: "4",
    reps: "12-15",
    description: "Fundamental upper body exercise targeting chest, shoulders, and triceps.",
    instructions: [
      "Start in plank position with hands shoulder-width apart",
      "Lower body until chest nearly touches the floor",
      "Push back up to starting position",
      "Keep core tight throughout the movement",
    ],
    emoji: "💪",
    animationType: "pushup",
  },
  {
    id: "3",
    name: "Squats",
    category: "gain_muscle",
    muscleGroup: "Quadriceps, Glutes, Hamstrings",
    difficulty: "beginner",
    caloriesBurned: 150,
    duration: "20 min",
    sets: "4",
    reps: "12-15",
    description: "Essential lower body compound movement for building leg and glute strength.",
    instructions: [
      "Stand with feet shoulder-width apart",
      "Lower hips back and down as if sitting in a chair",
      "Keep chest up and knees tracking over toes",
      "Push through heels to stand back up",
    ],
    emoji: "🦵",
    animationType: "squat",
  },
  {
    id: "4",
    name: "HIIT Burpees",
    category: "lose_weight",
    muscleGroup: "Full Body",
    difficulty: "intermediate",
    caloriesBurned: 400,
    duration: "25 min",
    description: "High-intensity interval training alternating between intense bursts and rest periods.",
    instructions: [
      "Start standing, drop into a squat position",
      "Kick feet back into plank position",
      "Do a push-up, jump feet back to squat",
      "Explosively jump up with arms overhead",
      "Repeat for 30 seconds, rest 15 seconds",
    ],
    emoji: "🔥",
    animationType: "burpee",
  },
  {
    id: "5",
    name: "Deadlifts",
    category: "gain_muscle",
    muscleGroup: "Back, Hamstrings, Glutes",
    difficulty: "intermediate",
    caloriesBurned: 180,
    duration: "20 min",
    sets: "4",
    reps: "8-10",
    description: "Powerful compound exercise that strengthens the posterior chain.",
    instructions: [
      "Stand with feet hip-width apart, barbell over mid-foot",
      "Hinge at hips, grip bar just outside knees",
      "Brace core and lift by driving through legs",
      "Lock out hips at top, reverse slowly",
    ],
    emoji: "🏋️",
    animationType: "deadlift",
  },
  {
    id: "6",
    name: "Plank Hold",
    category: "gain_muscle",
    muscleGroup: "Core",
    difficulty: "beginner",
    caloriesBurned: 60,
    duration: "10 min",
    sets: "4",
    reps: "30-60 sec hold",
    description: "Isometric core exercise that builds stability and endurance.",
    instructions: [
      "Start in forearm plank position",
      "Keep body in a straight line from head to heels",
      "Engage core and squeeze glutes",
      "Hold position for the target duration",
    ],
    emoji: "🧘",
    animationType: "plank",
  },
  {
    id: "7",
    name: "Cycling",
    category: "cardio",
    muscleGroup: "Legs, Cardiovascular",
    difficulty: "beginner",
    caloriesBurned: 250,
    duration: "30 min",
    description: "Low-impact cardio that's great for burning fat while being easy on joints.",
    instructions: [
      "Adjust seat to proper height",
      "Start with moderate resistance",
      "Alternate between seated and standing intervals",
      "Maintain cadence of 80-100 RPM",
    ],
    emoji: "🚴",
    animationType: "cycling",
  },
  {
    id: "8",
    name: "Pull-Ups",
    category: "gain_muscle",
    muscleGroup: "Back, Biceps",
    difficulty: "advanced",
    caloriesBurned: 120,
    duration: "15 min",
    sets: "4",
    reps: "6-10",
    description: "Upper body pulling exercise that builds a strong back and arms.",
    instructions: [
      "Grip bar with hands slightly wider than shoulders",
      "Hang with arms fully extended",
      "Pull body up until chin clears the bar",
      "Lower slowly to starting position",
    ],
    emoji: "🤸",
    animationType: "pullup",
  },
  {
    id: "9",
    name: "Yoga Flow",
    category: "flexibility",
    muscleGroup: "Full Body",
    difficulty: "beginner",
    caloriesBurned: 80,
    duration: "30 min",
    description: "Gentle flowing movements that improve flexibility, balance, and mindfulness.",
    instructions: [
      "Start in mountain pose, focus on breathing",
      "Flow through sun salutation sequence",
      "Hold warrior poses for 30 seconds each",
      "End with 5 minutes of savasana",
    ],
    emoji: "🧘‍♀️",
    animationType: "yoga",
  },
  {
    id: "10",
    name: "Lunges",
    category: "lose_weight",
    muscleGroup: "Legs, Glutes",
    difficulty: "beginner",
    caloriesBurned: 200,
    duration: "20 min",
    sets: "3",
    reps: "12 each leg",
    description: "Unilateral leg exercise that improves balance and builds lower body strength.",
    instructions: [
      "Stand tall with feet hip-width apart",
      "Step forward with one leg, lowering hips",
      "Lower until both knees are at 90 degrees",
      "Push back to starting position, alternate legs",
    ],
    emoji: "🦿",
    animationType: "lunge",
  },
  {
    id: "11",
    name: "Crunches",
    category: "gain_muscle",
    muscleGroup: "Abs",
    difficulty: "beginner",
    caloriesBurned: 50,
    duration: "10 min",
    sets: "3",
    reps: "20-25",
    description: "Targeted ab exercise to build core strength and definition.",
    instructions: [
      "Lie on back with knees bent, feet flat",
      "Place hands behind head, elbows wide",
      "Curl shoulders off the floor toward knees",
      "Lower slowly with control",
    ],
    emoji: "💫",
    animationType: "crunch",
  },
  {
    id: "12",
    name: "Jumping Jacks",
    category: "cardio",
    muscleGroup: "Full Body",
    difficulty: "beginner",
    caloriesBurned: 280,
    duration: "15 min",
    description: "Classic cardio movement that elevates heart rate and burns calories quickly.",
    instructions: [
      "Stand with feet together, arms at sides",
      "Jump feet out wide while raising arms overhead",
      "Jump back to starting position",
      "Repeat at a steady, quick pace",
    ],
    emoji: "⭐",
    animationType: "jumping",
  },
];
