// Calorie calculation helpers

export function calculateBMR(weight: number, height: number, age: number, gender: string): number {
  // Mifflin-St Jeor Equation
  if (gender === "male") {
    return 10 * weight + 6.25 * height - 5 * age + 5;
  }
  return 10 * weight + 6.25 * height - 5 * age - 161;
}

export function calculateTDEE(bmr: number, activityLevel: string): number {
  const multipliers: Record<string, number> = {
    sedentary: 1.2,
    light: 1.375,
    moderate: 1.55,
    active: 1.725,
    very_active: 1.9,
  };
  return Math.round(bmr * (multipliers[activityLevel] || 1.55));
}

export function calculateDailyCalories(tdee: number, goal: string): number {
  switch (goal) {
    case "lose_weight":
      return Math.round(tdee - 500);
    case "gain_muscle":
      return Math.round(tdee + 300);
    default:
      return tdee;
  }
}

export function calculateBMI(weight: number, height: number): number {
  const heightM = height / 100;
  return Math.round((weight / (heightM * heightM)) * 10) / 10;
}

export function getMacroTargets(calories: number, goal: string) {
  switch (goal) {
    case "lose_weight":
      return {
        protein: Math.round((calories * 0.35) / 4),
        carbs: Math.round((calories * 0.35) / 4),
        fat: Math.round((calories * 0.30) / 9),
      };
    case "gain_muscle":
      return {
        protein: Math.round((calories * 0.30) / 4),
        carbs: Math.round((calories * 0.45) / 4),
        fat: Math.round((calories * 0.25) / 9),
      };
    default:
      return {
        protein: Math.round((calories * 0.25) / 4),
        carbs: Math.round((calories * 0.50) / 4),
        fat: Math.round((calories * 0.25) / 9),
      };
  }
}

// Re-export the food database from dedicated file
export { foodDatabase, type FoodItem } from "./food-db";

// Recipe database
export interface Recipe {
  id: string;
  name: string;
  category: "lose_weight" | "gain_muscle" | "balanced";
  mealType: "breakfast" | "lunch" | "dinner" | "snack";
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  prepTime: string;
  ingredients: string[];
  instructions: string[];
  imageUrl: string;
}

export const recipes: Recipe[] = [
  // ========== BREAKFAST RECIPES ==========
  {
    id: "b1",
    name: "Protein Pancakes",
    category: "gain_muscle",
    mealType: "breakfast",
    calories: 420,
    protein: 35,
    carbs: 45,
    fat: 12,
    prepTime: "15 min",
    ingredients: [
      "1 scoop protein powder",
      "1 banana",
      "2 eggs",
      "1/4 cup oats",
      "1 tsp baking powder",
      "Maple syrup (optional)",
    ],
    instructions: [
      "Blend banana, eggs, oats, protein powder, and baking powder",
      "Heat a non-stick pan over medium heat",
      "Pour batter to form pancakes",
      "Cook 2-3 min per side until golden",
      "Top with fresh berries or maple syrup",
    ],
    imageUrl: "https://images.pexels.com/photos/376464/pexels-photo-376464.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "b2",
    name: "Avocado Toast with Eggs",
    category: "balanced",
    mealType: "breakfast",
    calories: 380,
    protein: 18,
    carbs: 32,
    fat: 22,
    prepTime: "10 min",
    ingredients: [
      "2 slices whole wheat bread",
      "1 ripe avocado",
      "2 eggs",
      "Cherry tomatoes",
      "Salt, pepper, red pepper flakes",
      "Lemon juice",
    ],
    instructions: [
      "Toast bread until golden and crispy",
      "Mash avocado with lemon juice, salt, and pepper",
      "Poach or fry eggs to your preference",
      "Spread avocado on toast, top with eggs",
      "Garnish with tomatoes and red pepper flakes",
    ],
    imageUrl: "https://images.pexels.com/photos/1351238/pexels-photo-1351238.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "b3",
    name: "Greek Yogurt Parfait",
    category: "lose_weight",
    mealType: "breakfast",
    calories: 280,
    protein: 22,
    carbs: 35,
    fat: 6,
    prepTime: "5 min",
    ingredients: [
      "1 cup Greek yogurt (0% fat)",
      "1/2 cup mixed berries",
      "2 tbsp granola",
      "1 tbsp honey",
      "1 tbsp chia seeds",
    ],
    instructions: [
      "Layer half the yogurt in a glass or bowl",
      "Add half the berries and granola",
      "Repeat layers with remaining ingredients",
      "Drizzle with honey",
      "Top with chia seeds",
    ],
    imageUrl: "https://images.pexels.com/photos/1099680/pexels-photo-1099680.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "b4",
    name: "Overnight Protein Oats",
    category: "gain_muscle",
    mealType: "breakfast",
    calories: 480,
    protein: 30,
    carbs: 55,
    fat: 15,
    prepTime: "5 min + overnight",
    ingredients: [
      "1/2 cup rolled oats",
      "1 scoop protein powder",
      "1 cup Greek yogurt",
      "1 tbsp peanut butter",
      "Blueberries",
      "Chia seeds",
    ],
    instructions: [
      "Mix oats, protein powder, and yogurt in a jar",
      "Add a splash of milk to desired consistency",
      "Stir in chia seeds",
      "Refrigerate overnight",
      "Top with peanut butter and blueberries in the morning",
    ],
    imageUrl: "https://images.pexels.com/photos/6489713/pexels-photo-6489713.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "b5",
    name: "Veggie Egg White Omelette",
    category: "lose_weight",
    mealType: "breakfast",
    calories: 220,
    protein: 24,
    carbs: 12,
    fat: 8,
    prepTime: "12 min",
    ingredients: [
      "4 egg whites",
      "1/4 cup spinach",
      "1/4 cup mushrooms",
      "1/4 cup bell peppers",
      "2 tbsp feta cheese",
      "Fresh herbs",
    ],
    instructions: [
      "Whisk egg whites with salt and pepper",
      "Sauté vegetables in a non-stick pan",
      "Pour egg whites over vegetables",
      "Cook until set, fold in half",
      "Top with feta and fresh herbs",
    ],
    imageUrl: "https://images.pexels.com/photos/566566/pexels-photo-566566.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "b6",
    name: "Smoothie Bowl",
    category: "balanced",
    mealType: "breakfast",
    calories: 350,
    protein: 15,
    carbs: 55,
    fat: 10,
    prepTime: "8 min",
    ingredients: [
      "1 frozen banana",
      "1/2 cup frozen berries",
      "1/2 cup almond milk",
      "2 tbsp almond butter",
      "Toppings: granola, coconut, seeds",
    ],
    instructions: [
      "Blend frozen fruits with almond milk until thick",
      "Pour into a bowl",
      "Add almond butter",
      "Top with granola, coconut flakes, and seeds",
      "Serve immediately",
    ],
    imageUrl: "https://images.pexels.com/photos/1092730/pexels-photo-1092730.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "b7",
    name: "Breakfast Burrito",
    category: "gain_muscle",
    mealType: "breakfast",
    calories: 520,
    protein: 32,
    carbs: 45,
    fat: 24,
    prepTime: "15 min",
    ingredients: [
      "2 whole eggs + 2 egg whites",
      "1 large tortilla",
      "1/4 cup black beans",
      "2 tbsp cheese",
      "Salsa and avocado",
      "Turkey bacon (2 strips)",
    ],
    instructions: [
      "Cook turkey bacon until crispy",
      "Scramble eggs with salt and pepper",
      "Warm tortilla in a pan",
      "Layer eggs, beans, bacon, cheese",
      "Add salsa and avocado, roll up tight",
    ],
    imageUrl: "https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "b8",
    name: "Cottage Cheese Bowl",
    category: "lose_weight",
    mealType: "breakfast",
    calories: 250,
    protein: 28,
    carbs: 20,
    fat: 6,
    prepTime: "5 min",
    ingredients: [
      "1 cup low-fat cottage cheese",
      "1/2 cup pineapple chunks",
      "1 tbsp honey",
      "2 tbsp walnuts",
      "Cinnamon",
    ],
    instructions: [
      "Place cottage cheese in a bowl",
      "Add pineapple chunks on top",
      "Drizzle with honey",
      "Sprinkle walnuts and cinnamon",
      "Enjoy cold",
    ],
    imageUrl: "https://images.pexels.com/photos/1640773/pexels-photo-1640773.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "b9",
    name: "Banana Nut Oatmeal",
    category: "balanced",
    mealType: "breakfast",
    calories: 380,
    protein: 12,
    carbs: 58,
    fat: 14,
    prepTime: "10 min",
    ingredients: [
      "1/2 cup rolled oats",
      "1 cup milk",
      "1 banana, sliced",
      "2 tbsp walnuts",
      "1 tbsp honey",
      "Cinnamon",
    ],
    instructions: [
      "Cook oats with milk according to package",
      "Stir in half the banana while cooking",
      "Transfer to bowl",
      "Top with remaining banana, walnuts",
      "Drizzle honey and add cinnamon",
    ],
    imageUrl: "https://images.pexels.com/photos/1333746/pexels-photo-1333746.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "b10",
    name: "Shakshuka",
    category: "balanced",
    mealType: "breakfast",
    calories: 320,
    protein: 18,
    carbs: 25,
    fat: 18,
    prepTime: "25 min",
    ingredients: [
      "3 eggs",
      "1 can diced tomatoes",
      "1/2 onion, diced",
      "1 bell pepper",
      "Cumin, paprika, garlic",
      "Fresh parsley, feta",
    ],
    instructions: [
      "Sauté onion and pepper until soft",
      "Add spices and garlic, cook 1 min",
      "Pour in tomatoes, simmer 10 min",
      "Make wells, crack eggs into sauce",
      "Cover and cook until eggs set",
    ],
    imageUrl: "https://images.pexels.com/photos/6294361/pexels-photo-6294361.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },

  // ========== LUNCH RECIPES ==========
  {
    id: "l1",
    name: "Grilled Chicken Salad",
    category: "lose_weight",
    mealType: "lunch",
    calories: 350,
    protein: 35,
    carbs: 15,
    fat: 18,
    prepTime: "20 min",
    ingredients: [
      "150g chicken breast",
      "2 cups mixed greens",
      "1/2 avocado",
      "Cherry tomatoes",
      "Cucumber",
      "Olive oil & lemon dressing",
    ],
    instructions: [
      "Season chicken breast with salt, pepper, and herbs",
      "Grill chicken for 6-7 minutes each side",
      "Prepare salad base with greens, tomatoes, and cucumber",
      "Slice chicken and place on top",
      "Add avocado slices and drizzle with dressing",
    ],
    imageUrl: "https://images.pexels.com/photos/29138860/pexels-photo-29138860.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "l2",
    name: "Protein Power Bowl",
    category: "gain_muscle",
    mealType: "lunch",
    calories: 650,
    protein: 45,
    carbs: 60,
    fat: 22,
    prepTime: "25 min",
    ingredients: [
      "200g chicken breast",
      "1 cup brown rice",
      "1/2 cup black beans",
      "1/2 avocado",
      "Salsa",
      "Corn",
    ],
    instructions: [
      "Cook brown rice according to package directions",
      "Season and grill chicken breast",
      "Heat black beans with cumin and garlic",
      "Assemble bowl with rice base, sliced chicken",
      "Top with beans, avocado, corn, and salsa",
    ],
    imageUrl: "https://images.pexels.com/photos/7627437/pexels-photo-7627437.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "l3",
    name: "Mediterranean Quinoa Bowl",
    category: "balanced",
    mealType: "lunch",
    calories: 450,
    protein: 18,
    carbs: 52,
    fat: 20,
    prepTime: "25 min",
    ingredients: [
      "1 cup cooked quinoa",
      "1/2 cup chickpeas",
      "Cucumber, tomatoes, red onion",
      "Feta cheese",
      "Kalamata olives",
      "Tzatziki sauce",
    ],
    instructions: [
      "Cook quinoa and let cool slightly",
      "Dice cucumber, tomatoes, and red onion",
      "Combine quinoa with vegetables and chickpeas",
      "Top with feta and olives",
      "Drizzle with tzatziki",
    ],
    imageUrl: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "l4",
    name: "Turkey Lettuce Wraps",
    category: "lose_weight",
    mealType: "lunch",
    calories: 280,
    protein: 28,
    carbs: 12,
    fat: 14,
    prepTime: "15 min",
    ingredients: [
      "200g ground turkey",
      "Butter lettuce leaves",
      "Water chestnuts",
      "Soy sauce",
      "Ginger & garlic",
      "Green onions",
    ],
    instructions: [
      "Cook ground turkey with ginger and garlic",
      "Add diced water chestnuts and soy sauce",
      "Cook until turkey is browned and flavored",
      "Spoon mixture into lettuce cups",
      "Garnish with green onions",
    ],
    imageUrl: "https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "l5",
    name: "Tuna Poke Bowl",
    category: "balanced",
    mealType: "lunch",
    calories: 420,
    protein: 32,
    carbs: 45,
    fat: 14,
    prepTime: "20 min",
    ingredients: [
      "150g fresh tuna, cubed",
      "1 cup sushi rice",
      "Edamame",
      "Avocado",
      "Soy sauce, sesame oil",
      "Sesame seeds, nori",
    ],
    instructions: [
      "Cook sushi rice and let cool",
      "Marinate tuna in soy sauce and sesame oil",
      "Place rice in bowl",
      "Top with tuna, edamame, avocado",
      "Garnish with sesame seeds and nori strips",
    ],
    imageUrl: "https://images.pexels.com/photos/3763816/pexels-photo-3763816.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "l6",
    name: "Chicken Caesar Wrap",
    category: "balanced",
    mealType: "lunch",
    calories: 480,
    protein: 35,
    carbs: 38,
    fat: 22,
    prepTime: "15 min",
    ingredients: [
      "150g grilled chicken breast",
      "1 large tortilla",
      "Romaine lettuce",
      "Parmesan cheese",
      "Caesar dressing (light)",
      "Croutons",
    ],
    instructions: [
      "Slice grilled chicken into strips",
      "Chop romaine lettuce",
      "Toss lettuce with dressing and parmesan",
      "Place on tortilla with chicken",
      "Add croutons and roll tightly",
    ],
    imageUrl: "https://images.pexels.com/photos/2097090/pexels-photo-2097090.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "l7",
    name: "Asian Beef Salad",
    category: "gain_muscle",
    mealType: "lunch",
    calories: 420,
    protein: 38,
    carbs: 18,
    fat: 22,
    prepTime: "20 min",
    ingredients: [
      "150g flank steak",
      "Mixed Asian greens",
      "Carrot, cucumber ribbons",
      "Fresh mint, cilantro",
      "Lime-chili dressing",
      "Crushed peanuts",
    ],
    instructions: [
      "Grill steak to medium-rare, let rest",
      "Prepare vegetable ribbons with peeler",
      "Toss greens with herbs and vegetables",
      "Slice steak against the grain",
      "Top salad with steak, dressing, peanuts",
    ],
    imageUrl: "https://images.pexels.com/photos/1640776/pexels-photo-1640776.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "l8",
    name: "Lentil Soup",
    category: "lose_weight",
    mealType: "lunch",
    calories: 320,
    protein: 18,
    carbs: 45,
    fat: 8,
    prepTime: "35 min",
    ingredients: [
      "1 cup red lentils",
      "1 onion, carrots, celery",
      "4 cups vegetable broth",
      "Cumin, turmeric, garlic",
      "Lemon juice",
      "Fresh parsley",
    ],
    instructions: [
      "Sauté onion, carrots, celery until soft",
      "Add garlic and spices, cook 1 min",
      "Add lentils and broth, bring to boil",
      "Simmer 25 min until lentils are tender",
      "Blend partially, add lemon juice",
    ],
    imageUrl: "https://images.pexels.com/photos/539451/pexels-photo-539451.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },

  // ========== DINNER RECIPES ==========
  {
    id: "d1",
    name: "Salmon & Quinoa Bowl",
    category: "balanced",
    mealType: "dinner",
    calories: 520,
    protein: 35,
    carbs: 45,
    fat: 20,
    prepTime: "30 min",
    ingredients: [
      "150g salmon fillet",
      "1 cup quinoa",
      "Steamed broccoli",
      "Sweet potato cubes",
      "Soy sauce & ginger glaze",
    ],
    instructions: [
      "Cook quinoa and set aside",
      "Roast sweet potato cubes at 200°C for 20 min",
      "Pan-sear salmon for 4 min each side",
      "Steam broccoli until tender",
      "Assemble bowl and drizzle with glaze",
    ],
    imageUrl: "https://images.pexels.com/photos/6489563/pexels-photo-6489563.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "d2",
    name: "Grilled Steak & Vegetables",
    category: "gain_muscle",
    mealType: "dinner",
    calories: 580,
    protein: 45,
    carbs: 25,
    fat: 35,
    prepTime: "25 min",
    ingredients: [
      "200g ribeye steak",
      "Asparagus",
      "Cherry tomatoes",
      "Garlic butter",
      "Fresh rosemary",
      "Baked potato",
    ],
    instructions: [
      "Bring steak to room temperature",
      "Season with salt, pepper, rosemary",
      "Grill 4-5 min per side for medium",
      "Rest 5 minutes before slicing",
      "Serve with grilled vegetables and potato",
    ],
    imageUrl: "https://images.pexels.com/photos/3535383/pexels-photo-3535383.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "d3",
    name: "Chicken Stir-Fry",
    category: "lose_weight",
    mealType: "dinner",
    calories: 380,
    protein: 35,
    carbs: 30,
    fat: 14,
    prepTime: "20 min",
    ingredients: [
      "200g chicken breast, sliced",
      "Broccoli, snap peas, bell peppers",
      "Garlic, ginger",
      "Low-sodium soy sauce",
      "Sesame oil",
      "Brown rice (optional)",
    ],
    instructions: [
      "Heat wok or large pan over high heat",
      "Stir-fry chicken until cooked, set aside",
      "Stir-fry vegetables 3-4 minutes",
      "Add garlic, ginger, soy sauce",
      "Return chicken, toss together",
    ],
    imageUrl: "https://images.pexels.com/photos/262897/pexels-photo-262897.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "d4",
    name: "Baked Cod with Vegetables",
    category: "lose_weight",
    mealType: "dinner",
    calories: 320,
    protein: 35,
    carbs: 20,
    fat: 12,
    prepTime: "30 min",
    ingredients: [
      "200g cod fillet",
      "Zucchini, cherry tomatoes",
      "Lemon slices",
      "Fresh dill, capers",
      "Olive oil",
      "White wine (optional)",
    ],
    instructions: [
      "Preheat oven to 200°C",
      "Place cod on foil with vegetables",
      "Season and add lemon, dill, capers",
      "Drizzle olive oil, fold foil to seal",
      "Bake 18-20 minutes until fish flakes",
    ],
    imageUrl: "https://images.pexels.com/photos/3655916/pexels-photo-3655916.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "d5",
    name: "Turkey Meatballs & Zoodles",
    category: "lose_weight",
    mealType: "dinner",
    calories: 350,
    protein: 32,
    carbs: 18,
    fat: 18,
    prepTime: "30 min",
    ingredients: [
      "200g ground turkey",
      "2 zucchinis, spiralized",
      "Marinara sauce (low sugar)",
      "Italian herbs",
      "Parmesan cheese",
      "Fresh basil",
    ],
    instructions: [
      "Mix turkey with herbs, form meatballs",
      "Bake meatballs at 200°C for 20 min",
      "Heat marinara sauce in a pan",
      "Sauté zoodles 2-3 minutes",
      "Serve zoodles with meatballs and sauce",
    ],
    imageUrl: "https://images.pexels.com/photos/1373915/pexels-photo-1373915.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "d6",
    name: "Teriyaki Salmon Bowl",
    category: "balanced",
    mealType: "dinner",
    calories: 550,
    protein: 38,
    carbs: 52,
    fat: 22,
    prepTime: "25 min",
    ingredients: [
      "150g salmon fillet",
      "1 cup jasmine rice",
      "Teriyaki sauce",
      "Steamed bok choy",
      "Pickled ginger, sesame seeds",
      "Sliced avocado",
    ],
    instructions: [
      "Cook rice according to package",
      "Brush salmon with teriyaki, bake 12 min",
      "Steam bok choy until tender",
      "Assemble bowl with rice base",
      "Top with salmon, bok choy, avocado",
    ],
    imageUrl: "https://images.pexels.com/photos/1516415/pexels-photo-1516415.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "d7",
    name: "Lean Beef Tacos",
    category: "balanced",
    mealType: "dinner",
    calories: 450,
    protein: 30,
    carbs: 40,
    fat: 20,
    prepTime: "20 min",
    ingredients: [
      "150g lean ground beef",
      "Corn tortillas (3)",
      "Taco seasoning",
      "Lettuce, tomato, onion",
      "Greek yogurt (sour cream sub)",
      "Lime, cilantro",
    ],
    instructions: [
      "Brown beef with taco seasoning",
      "Warm tortillas in a dry pan",
      "Dice vegetables for toppings",
      "Assemble tacos with beef and veggies",
      "Top with yogurt, cilantro, lime squeeze",
    ],
    imageUrl: "https://images.pexels.com/photos/4958641/pexels-photo-4958641.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "d8",
    name: "Stuffed Bell Peppers",
    category: "balanced",
    mealType: "dinner",
    calories: 420,
    protein: 28,
    carbs: 35,
    fat: 18,
    prepTime: "45 min",
    ingredients: [
      "4 bell peppers",
      "150g ground turkey",
      "1/2 cup cooked rice",
      "Black beans",
      "Tomato sauce",
      "Cheese, cilantro",
    ],
    instructions: [
      "Cut tops off peppers, remove seeds",
      "Brown turkey with onion and garlic",
      "Mix with rice, beans, half the sauce",
      "Stuff peppers, top with remaining sauce",
      "Bake at 180°C for 30 min, add cheese",
    ],
    imageUrl: "https://images.pexels.com/photos/5907618/pexels-photo-5907618.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "d9",
    name: "Shrimp Pasta",
    category: "gain_muscle",
    mealType: "dinner",
    calories: 580,
    protein: 35,
    carbs: 60,
    fat: 22,
    prepTime: "25 min",
    ingredients: [
      "200g shrimp",
      "200g whole wheat pasta",
      "Cherry tomatoes",
      "Garlic, white wine",
      "Fresh basil",
      "Parmesan, olive oil",
    ],
    instructions: [
      "Cook pasta al dente",
      "Sauté garlic in olive oil",
      "Add shrimp, cook until pink",
      "Add tomatoes, wine, simmer 3 min",
      "Toss with pasta, basil, parmesan",
    ],
    imageUrl: "https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "d10",
    name: "Chicken Curry",
    category: "balanced",
    mealType: "dinner",
    calories: 480,
    protein: 35,
    carbs: 45,
    fat: 18,
    prepTime: "35 min",
    ingredients: [
      "200g chicken thigh, cubed",
      "1 can coconut milk (light)",
      "Curry paste",
      "Bell peppers, onion",
      "Basmati rice",
      "Fresh cilantro",
    ],
    instructions: [
      "Sauté onion and peppers",
      "Add curry paste, cook 1 min",
      "Add chicken, cook until browned",
      "Pour in coconut milk, simmer 20 min",
      "Serve over rice with cilantro",
    ],
    imageUrl: "https://images.pexels.com/photos/2474661/pexels-photo-2474661.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "d11",
    name: "Herb Roasted Chicken",
    category: "gain_muscle",
    mealType: "dinner",
    calories: 520,
    protein: 48,
    carbs: 20,
    fat: 28,
    prepTime: "50 min",
    ingredients: [
      "2 chicken thighs (bone-in)",
      "Potatoes, quartered",
      "Lemon, rosemary, thyme",
      "Garlic cloves",
      "Olive oil",
      "Green beans",
    ],
    instructions: [
      "Preheat oven to 200°C",
      "Season chicken with herbs, lemon zest",
      "Arrange with potatoes and garlic",
      "Roast 40 min until golden",
      "Add steamed green beans to serve",
    ],
    imageUrl: "https://images.pexels.com/photos/2338407/pexels-photo-2338407.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "d12",
    name: "Vegetable Tofu Stir-Fry",
    category: "lose_weight",
    mealType: "dinner",
    calories: 320,
    protein: 22,
    carbs: 28,
    fat: 16,
    prepTime: "20 min",
    ingredients: [
      "200g firm tofu, cubed",
      "Mixed vegetables",
      "Garlic, ginger",
      "Low-sodium soy sauce",
      "Sesame oil",
      "Brown rice (optional)",
    ],
    instructions: [
      "Press tofu and cube",
      "Fry tofu until golden, set aside",
      "Stir-fry vegetables with garlic, ginger",
      "Add tofu and sauce",
      "Serve over brown rice",
    ],
    imageUrl: "https://images.pexels.com/photos/1438672/pexels-photo-1438672.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },

  // ========== SNACK RECIPES ==========
  {
    id: "s1",
    name: "Protein Energy Balls",
    category: "gain_muscle",
    mealType: "snack",
    calories: 180,
    protein: 12,
    carbs: 18,
    fat: 8,
    prepTime: "15 min",
    ingredients: [
      "1 cup oats",
      "1/2 cup peanut butter",
      "1 scoop protein powder",
      "2 tbsp honey",
      "Dark chocolate chips",
    ],
    instructions: [
      "Mix all ingredients in a bowl",
      "Refrigerate 30 min to firm up",
      "Roll into 12 balls",
      "Store in refrigerator",
      "Grab and go!",
    ],
    imageUrl: "https://images.pexels.com/photos/3622643/pexels-photo-3622643.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "s2",
    name: "Apple & Almond Butter",
    category: "balanced",
    mealType: "snack",
    calories: 200,
    protein: 5,
    carbs: 28,
    fat: 10,
    prepTime: "5 min",
    ingredients: [
      "1 medium apple",
      "2 tbsp almond butter",
      "Cinnamon",
      "Hemp seeds (optional)",
    ],
    instructions: [
      "Core and slice apple",
      "Arrange on plate",
      "Add almond butter for dipping",
      "Sprinkle with cinnamon and hemp seeds",
    ],
    imageUrl: "https://images.pexels.com/photos/4110258/pexels-photo-4110258.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "s3",
    name: "Greek Yogurt & Berries",
    category: "lose_weight",
    mealType: "snack",
    calories: 150,
    protein: 15,
    carbs: 18,
    fat: 2,
    prepTime: "3 min",
    ingredients: [
      "150g Greek yogurt (0%)",
      "1/2 cup mixed berries",
      "1 tsp honey",
      "Mint leaves",
    ],
    instructions: [
      "Place yogurt in a bowl",
      "Top with fresh berries",
      "Drizzle with honey",
      "Garnish with mint",
    ],
    imageUrl: "https://images.pexels.com/photos/1153369/pexels-photo-1153369.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "s4",
    name: "Veggie Sticks & Hummus",
    category: "lose_weight",
    mealType: "snack",
    calories: 160,
    protein: 6,
    carbs: 18,
    fat: 8,
    prepTime: "5 min",
    ingredients: [
      "Carrots, celery, cucumber",
      "Bell pepper strips",
      "1/4 cup hummus",
      "Paprika for garnish",
    ],
    instructions: [
      "Cut vegetables into sticks",
      "Arrange around hummus",
      "Sprinkle paprika on hummus",
      "Dip and enjoy!",
    ],
    imageUrl: "https://images.pexels.com/photos/1640771/pexels-photo-1640771.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "s5",
    name: "Cottage Cheese & Pineapple",
    category: "gain_muscle",
    mealType: "snack",
    calories: 180,
    protein: 20,
    carbs: 15,
    fat: 4,
    prepTime: "3 min",
    ingredients: [
      "1 cup cottage cheese",
      "1/2 cup pineapple chunks",
      "Coconut flakes",
      "Macadamia nuts (optional)",
    ],
    instructions: [
      "Place cottage cheese in bowl",
      "Add pineapple chunks",
      "Top with coconut flakes",
      "Add nuts for crunch",
    ],
    imageUrl: "https://images.pexels.com/photos/1092730/pexels-photo-1092730.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "s6",
    name: "Trail Mix",
    category: "gain_muscle",
    mealType: "snack",
    calories: 220,
    protein: 8,
    carbs: 20,
    fat: 14,
    prepTime: "2 min",
    ingredients: [
      "Almonds",
      "Walnuts",
      "Dark chocolate chips",
      "Dried cranberries",
      "Pumpkin seeds",
    ],
    instructions: [
      "Mix all ingredients together",
      "Portion into 1/4 cup servings",
      "Store in airtight container",
      "Perfect for on-the-go",
    ],
    imageUrl: "https://images.pexels.com/photos/1295572/pexels-photo-1295572.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "s7",
    name: "Rice Cakes with Avocado",
    category: "balanced",
    mealType: "snack",
    calories: 170,
    protein: 4,
    carbs: 20,
    fat: 10,
    prepTime: "5 min",
    ingredients: [
      "2 rice cakes",
      "1/2 avocado",
      "Everything bagel seasoning",
      "Lime juice",
      "Cherry tomatoes",
    ],
    instructions: [
      "Mash avocado with lime juice",
      "Spread on rice cakes",
      "Add sliced tomatoes",
      "Sprinkle with seasoning",
    ],
    imageUrl: "https://images.pexels.com/photos/1351238/pexels-photo-1351238.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "s8",
    name: "Edamame",
    category: "lose_weight",
    mealType: "snack",
    calories: 120,
    protein: 12,
    carbs: 10,
    fat: 5,
    prepTime: "5 min",
    ingredients: [
      "1 cup edamame in pods",
      "Sea salt",
      "Chili flakes (optional)",
      "Lime zest",
    ],
    instructions: [
      "Steam or microwave edamame",
      "Drain excess water",
      "Season with salt and chili",
      "Add lime zest and enjoy",
    ],
    imageUrl: "https://images.pexels.com/photos/3872434/pexels-photo-3872434.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "s9",
    name: "Protein Smoothie",
    category: "gain_muscle",
    mealType: "snack",
    calories: 280,
    protein: 30,
    carbs: 25,
    fat: 8,
    prepTime: "5 min",
    ingredients: [
      "1 scoop whey protein",
      "1 banana",
      "1 cup almond milk",
      "1 tbsp peanut butter",
      "Ice cubes",
    ],
    instructions: [
      "Add all ingredients to blender",
      "Blend until smooth",
      "Add more milk if too thick",
      "Pour and enjoy immediately",
    ],
    imageUrl: "https://images.pexels.com/photos/3625372/pexels-photo-3625372.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "s10",
    name: "Dark Chocolate & Almonds",
    category: "balanced",
    mealType: "snack",
    calories: 200,
    protein: 5,
    carbs: 15,
    fat: 15,
    prepTime: "1 min",
    ingredients: [
      "1 oz dark chocolate (70%+)",
      "15 almonds",
    ],
    instructions: [
      "Break chocolate into squares",
      "Pair with almonds",
      "Savor slowly",
      "Rich in antioxidants!",
    ],
    imageUrl: "https://images.pexels.com/photos/918327/pexels-photo-918327.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "s11",
    name: "Cucumber Tuna Bites",
    category: "lose_weight",
    mealType: "snack",
    calories: 140,
    protein: 18,
    carbs: 5,
    fat: 6,
    prepTime: "10 min",
    ingredients: [
      "1 cucumber",
      "1 can tuna (in water)",
      "Greek yogurt",
      "Dill, lemon juice",
      "Everything seasoning",
    ],
    instructions: [
      "Slice cucumber into thick rounds",
      "Mix tuna with yogurt, dill, lemon",
      "Spoon mixture onto cucumber",
      "Top with seasoning",
    ],
    imageUrl: "https://images.pexels.com/photos/1656663/pexels-photo-1656663.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "s12",
    name: "Frozen Banana Bites",
    category: "balanced",
    mealType: "snack",
    calories: 160,
    protein: 4,
    carbs: 22,
    fat: 8,
    prepTime: "10 min + freeze",
    ingredients: [
      "2 bananas",
      "Dark chocolate, melted",
      "Crushed peanuts",
      "Coconut flakes",
    ],
    instructions: [
      "Slice bananas into coins",
      "Dip in melted chocolate",
      "Sprinkle with toppings",
      "Freeze for 1 hour",
    ],
    imageUrl: "https://images.pexels.com/photos/2373520/pexels-photo-2373520.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "s13",
    name: "Caprese Skewers",
    category: "balanced",
    mealType: "snack",
    calories: 150,
    protein: 8,
    carbs: 6,
    fat: 12,
    prepTime: "10 min",
    ingredients: [
      "Cherry tomatoes",
      "Fresh mozzarella balls",
      "Fresh basil leaves",
      "Balsamic glaze",
      "Olive oil",
    ],
    instructions: [
      "Thread tomato, basil, mozzarella on picks",
      "Arrange on plate",
      "Drizzle with olive oil",
      "Finish with balsamic glaze",
    ],
    imageUrl: "https://images.pexels.com/photos/2087748/pexels-photo-2087748.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "s14",
    name: "Roasted Chickpeas",
    category: "lose_weight",
    mealType: "snack",
    calories: 130,
    protein: 7,
    carbs: 20,
    fat: 3,
    prepTime: "35 min",
    ingredients: [
      "1 can chickpeas, drained",
      "Olive oil spray",
      "Cumin, paprika, garlic",
      "Salt",
    ],
    instructions: [
      "Dry chickpeas thoroughly",
      "Toss with oil and spices",
      "Spread on baking sheet",
      "Roast at 200°C for 30 min",
      "Shake pan halfway through",
    ],
    imageUrl: "https://images.pexels.com/photos/6824476/pexels-photo-6824476.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  },
  {
    id: "q1",
    name: "Bowl Thon-Riz Express",
    category: "lose_weight",
    mealType: "lunch",
    calories: 380,
    protein: 34,
    carbs: 42,
    fat: 8,
    prepTime: "8 min",
    ingredients: ["1 boîte de thon au naturel", "150g riz cuit (ou reste de la veille)", "1/2 concombre", "1 c.à.s sauce soja", "Graines de sésame"],
    instructions: [
      "Égoutter le thon",
      "Mélanger avec le riz chaud ou froid",
      "Couper le concombre en dés, ajouter",
      "Assaisonner avec la sauce soja et les graines de sésame",
    ],
    imageUrl: "",
  },
  {
    id: "q2",
    name: "Omelette Express aux Épinards",
    category: "gain_muscle",
    mealType: "breakfast",
    calories: 420,
    protein: 30,
    carbs: 6,
    fat: 30,
    prepTime: "6 min",
    ingredients: ["3 œufs", "Poignée d'épinards frais", "30g fromage râpé", "Sel, poivre", "1 c.à.c huile d'olive"],
    instructions: [
      "Battre les œufs, saler, poivrer",
      "Faire revenir les épinards 1 min dans l'huile",
      "Verser les œufs, ajouter le fromage",
      "Cuire 3-4 min à feu moyen, plier en deux",
    ],
    imageUrl: "",
  },
  {
    id: "q3",
    name: "Skyr Fruits & Granola (Petit Budget)",
    category: "balanced",
    mealType: "breakfast",
    calories: 320,
    protein: 22,
    carbs: 40,
    fat: 6,
    prepTime: "3 min",
    ingredients: ["1 pot de skyr ou fromage blanc 0%", "1 banane ou fruits de saison", "3 c.à.s granola ou flocons d'avoine", "1 c.à.c miel (optionnel)"],
    instructions: [
      "Verser le skyr dans un bol",
      "Couper les fruits par-dessus",
      "Ajouter le granola et le miel",
    ],
    imageUrl: "",
  },
  {
    id: "q4",
    name: "Wrap Poulet-Crudités (À emporter)",
    category: "lose_weight",
    mealType: "lunch",
    calories: 410,
    protein: 32,
    carbs: 38,
    fat: 12,
    prepTime: "10 min",
    ingredients: ["1 galette de blé complet", "120g blanc de poulet cuit (ou rôtisserie)", "Salade, tomate, carotte râpée", "1 c.à.s sauce yaourt-citron"],
    instructions: [
      "Étaler la sauce sur la galette",
      "Garnir de poulet et crudités",
      "Rouler serré et couper en deux",
    ],
    imageUrl: "",
  },
  {
    id: "q5",
    name: "Pâtes Lentilles Corail (Végé, riche en protéines)",
    category: "gain_muscle",
    mealType: "dinner",
    calories: 520,
    protein: 26,
    carbs: 78,
    fat: 10,
    prepTime: "20 min",
    ingredients: ["100g lentilles corail", "80g pâtes complètes", "1 oignon", "1 boîte tomates concassées", "Épices (cumin, paprika)"],
    instructions: [
      "Faire revenir l'oignon",
      "Ajouter les tomates et les lentilles, couvrir d'eau",
      "Mijoter 15 min",
      "Cuire les pâtes à part, mélanger, épicer",
    ],
    imageUrl: "",
  },
  {
    id: "q6",
    name: "Toast Avocat-Œuf Poché",
    category: "balanced",
    mealType: "breakfast",
    calories: 380,
    protein: 18,
    carbs: 30,
    fat: 22,
    prepTime: "10 min",
    ingredients: ["2 tranches pain complet", "1/2 avocat", "1 œuf", "Jus de citron, sel, poivre, piment"],
    instructions: [
      "Toaster le pain",
      "Écraser l'avocat avec citron/sel, étaler",
      "Pocher l'œuf 3 min dans l'eau frémissante",
      "Déposer sur le toast, poivrer",
    ],
    imageUrl: "",
  },
  {
    id: "q7",
    name: "Smoothie Post-Training",
    category: "gain_muscle",
    mealType: "snack",
    calories: 340,
    protein: 28,
    carbs: 40,
    fat: 6,
    prepTime: "4 min",
    ingredients: ["1 banane", "250ml lait (ou végétal)", "1 dose whey ou 2 c.à.s poudre de protéine", "1 c.à.s beurre de cacahuète"],
    instructions: [
      "Mettre tous les ingrédients dans un blender",
      "Mixer 30-45 sec jusqu'à texture lisse",
    ],
    imageUrl: "",
  },
  {
    id: "q8",
    name: "Soupe Miso Tofu-Légumes",
    category: "lose_weight",
    mealType: "dinner",
    calories: 250,
    protein: 16,
    carbs: 18,
    fat: 10,
    prepTime: "12 min",
    ingredients: ["500ml bouillon", "1 c.à.s pâte miso", "100g tofu ferme en dés", "Champignons, algues wakame, oignon vert"],
    instructions: [
      "Chauffer le bouillon sans bouillir",
      "Délayer le miso à part avec un peu de bouillon chaud",
      "Ajouter tofu et légumes, réincorporer le miso",
      "Servir avec oignon vert",
    ],
    imageUrl: "",
  },
  {
    id: "g1",
    name: "Bowl Avoine Protéiné aux Fruits Rouges",
    category: "balanced",
    mealType: "breakfast",
    calories: 398,
    protein: 32,
    carbs: 55,
    fat: 6,
    prepTime: "8 min",
    ingredients: ["60g flocons d'avoine", "1 dose whey vanille", "1/2 banane", "150ml lait", "Fruits rouges"],
    instructions: ["Cuire l'avoine avec le lait 3-4 min", "Incorporer la whey hors du feu", "Garnir de banane et fruits rouges"],
    imageUrl: "",
  },
  {
    id: "g2",
    name: "Omelette 3 Œufs Fromage & Épinards",
    category: "gain_muscle",
    mealType: "breakfast",
    calories: 344,
    protein: 27,
    carbs: 3,
    fat: 25,
    prepTime: "10 min",
    ingredients: ["3 œufs", "30g fromage râpé", "Poignée d'épinards", "Sel, poivre"],
    instructions: ["Faire revenir les épinards", "Battre les œufs, verser", "Ajouter le fromage, plier, cuire 3 min"],
    imageUrl: "",
  },
  {
    id: "g3",
    name: "Skyr Granola Banane",
    category: "balanced",
    mealType: "breakfast",
    calories: 413,
    protein: 27,
    carbs: 57,
    fat: 9,
    prepTime: "3 min",
    ingredients: ["200g skyr", "40g granola", "1 banane"],
    instructions: ["Verser le skyr dans un bol", "Ajouter le granola et la banane tranchée"],
    imageUrl: "",
  },
  {
    id: "g4",
    name: "Pancakes Protéinés (3 pièces)",
    category: "gain_muscle",
    mealType: "breakfast",
    calories: 551,
    protein: 44,
    carbs: 60,
    fat: 15,
    prepTime: "15 min",
    ingredients: ["50g flocons d'avoine mixés", "2 œufs", "1 dose whey", "1 banane écrasée"],
    instructions: ["Mixer tous les ingrédients", "Cuire en petites crêpes 2 min de chaque côté", "Servir chaud"],
    imageUrl: "",
  },
  {
    id: "g5",
    name: "Toast Avocat & Œuf",
    category: "balanced",
    mealType: "breakfast",
    calories: 393,
    protein: 16,
    carbs: 33,
    fat: 22,
    prepTime: "10 min",
    ingredients: ["2 tranches pain complet", "1 avocat", "1 œuf poché", "Citron, sel, poivre"],
    instructions: ["Toaster le pain", "Écraser l'avocat dessus", "Ajouter l'œuf poché, assaisonner"],
    imageUrl: "",
  },
  {
    id: "g6",
    name: "Porridge Beurre de Cacahuète",
    category: "gain_muscle",
    mealType: "breakfast",
    calories: 490,
    protein: 15,
    carbs: 74,
    fat: 15,
    prepTime: "8 min",
    ingredients: ["70g flocons d'avoine", "200ml lait", "1 c.à.s beurre de cacahuète", "1 banane"],
    instructions: ["Cuire l'avoine dans le lait", "Incorporer le beurre de cacahuète", "Garnir de banane"],
    imageUrl: "",
  },
  {
    id: "g7",
    name: "Fromage Blanc Amandes & Miel",
    category: "lose_weight",
    mealType: "breakfast",
    calories: 286,
    protein: 25,
    carbs: 10,
    fat: 16,
    prepTime: "3 min",
    ingredients: ["200g fromage blanc 0%", "15g amandes effilées", "1 c.à.c miel"],
    instructions: ["Verser le fromage blanc dans un bol", "Ajouter amandes et un filet de miel"],
    imageUrl: "",
  },
  {
    id: "g8",
    name: "Omelette Blancs d'Œufs Légumes",
    category: "lose_weight",
    mealType: "breakfast",
    calories: 130,
    protein: 24,
    carbs: 8,
    fat: 0,
    prepTime: "10 min",
    ingredients: ["6 blancs d'œufs", "Poivrons, oignons, champignons", "Épices"],
    instructions: ["Faire revenir les légumes", "Verser les blancs d'œufs", "Cuire 4-5 min, plier"],
    imageUrl: "",
  },
  {
    id: "g9",
    name: "Smoothie Bowl Protéiné",
    category: "gain_muscle",
    mealType: "breakfast",
    calories: 374,
    protein: 37,
    carbs: 42,
    fat: 6,
    prepTime: "6 min",
    ingredients: ["1 dose whey", "1 banane congelée", "100g yaourt grec", "20g granola"],
    instructions: ["Mixer whey, banane et yaourt", "Verser dans un bol", "Garnir de granola"],
    imageUrl: "",
  },
  {
    id: "g10",
    name: "Wrap Petit-Déj Œuf & Avocat",
    category: "balanced",
    mealType: "breakfast",
    calories: 441,
    protein: 19,
    carbs: 41,
    fat: 22,
    prepTime: "10 min",
    ingredients: ["1 tortilla complète", "2 œufs brouillés", "1/2 avocat", "Sel, piment"],
    instructions: ["Brouiller les œufs", "Garnir la tortilla d'œufs et avocat écrasé", "Rouler"],
    imageUrl: "",
  },
  {
    id: "g11",
    name: "Bowl Poulet Riz Brocoli",
    category: "gain_muscle",
    mealType: "lunch",
    calories: 615,
    protein: 64,
    carbs: 59,
    fat: 14,
    prepTime: "20 min",
    ingredients: ["180g blanc de poulet", "200g riz complet cuit", "100g brocoli vapeur", "1 c.à.c huile d'olive"],
    instructions: ["Cuire le poulet à la poêle", "Cuire le riz et le brocoli à la vapeur", "Assembler, assaisonner"],
    imageUrl: "",
  },
  {
    id: "g12",
    name: "Salade Poulet Grillé Vinaigrette Légère",
    category: "lose_weight",
    mealType: "lunch",
    calories: 384,
    protein: 50,
    carbs: 14,
    fat: 14,
    prepTime: "15 min",
    ingredients: ["150g blanc de poulet grillé", "Mélange de salades, tomates, concombre", "1 c.à.s huile d'olive", "Vinaigre balsamique"],
    instructions: ["Griller le poulet, trancher", "Dresser la salade", "Assaisonner avec l'huile et le vinaigre"],
    imageUrl: "",
  },
  {
    id: "g13",
    name: "Saumon Quinoa & Légumes Rôtis",
    category: "balanced",
    mealType: "lunch",
    calories: 612,
    protein: 41,
    carbs: 48,
    fat: 28,
    prepTime: "25 min",
    ingredients: ["150g pavé de saumon", "180g quinoa cuit", "Légumes de saison rôtis", "Huile d'olive"],
    instructions: ["Cuire le saumon au four 15 min", "Rôtir les légumes en parallèle", "Servir sur le quinoa"],
    imageUrl: "",
  },
  {
    id: "g14",
    name: "Bowl Bœuf Patate Douce",
    category: "gain_muscle",
    mealType: "lunch",
    calories: 639,
    protein: 53,
    carbs: 57,
    fat: 22,
    prepTime: "25 min",
    ingredients: ["180g bœuf haché 5%", "250g patate douce", "Légumes verts"],
    instructions: ["Cuire le bœuf à la poêle", "Cuire la patate douce au four ou vapeur", "Assembler"],
    imageUrl: "",
  },
  {
    id: "g15",
    name: "Wrap Thon Avocat",
    category: "lose_weight",
    mealType: "lunch",
    calories: 467,
    protein: 40,
    carbs: 46,
    fat: 14,
    prepTime: "10 min",
    ingredients: ["1 tortilla", "1 boîte de thon au naturel", "1/2 avocat", "Crudités"],
    instructions: ["Égoutter le thon, l'écraser avec l'avocat", "Garnir la tortilla", "Rouler serré"],
    imageUrl: "",
  },
  {
    id: "g16",
    name: "Pâtes Complètes Poulet Parmesan",
    category: "gain_muscle",
    mealType: "lunch",
    calories: 720,
    protein: 67,
    carbs: 63,
    fat: 22,
    prepTime: "20 min",
    ingredients: ["250g pâtes complètes cuites", "150g poulet émincé", "20g parmesan", "Huile d'olive, ail"],
    instructions: ["Cuire les pâtes", "Poêler le poulet à l'ail", "Mélanger avec l'huile et le parmesan"],
    imageUrl: "",
  },
  {
    id: "g17",
    name: "Salade Pois Chiches Feta-Style",
    category: "balanced",
    mealType: "lunch",
    calories: 644,
    protein: 31,
    carbs: 65,
    fat: 29,
    prepTime: "10 min",
    ingredients: ["200g pois chiches cuits", "40g fromage type feta", "Tomates, concombre, oignon rouge", "Huile d'olive, citron"],
    instructions: ["Mélanger tous les ingrédients", "Assaisonner avec huile d'olive et citron"],
    imageUrl: "",
  },
  {
    id: "g18",
    name: "Poke Bowl Saumon",
    category: "balanced",
    mealType: "lunch",
    calories: 588,
    protein: 32,
    carbs: 62,
    fat: 24,
    prepTime: "15 min",
    ingredients: ["120g saumon cru ou cuit", "180g riz vinaigré", "1/2 avocat", "Edamame, carotte, concombre"],
    instructions: ["Préparer le riz vinaigré", "Couper le saumon en cubes", "Dresser en bowl avec les garnitures"],
    imageUrl: "",
  },
  {
    id: "g19",
    name: "Bœuf Sauté Légumes Sauce Soja",
    category: "gain_muscle",
    mealType: "lunch",
    calories: 797,
    protein: 53,
    carbs: 66,
    fat: 35,
    prepTime: "20 min",
    ingredients: ["180g bœuf en lamelles", "200g riz", "Poivrons, oignons, brocoli", "Sauce soja, gingembre"],
    instructions: ["Saisir le bœuf à feu vif", "Ajouter les légumes, sauce soja", "Servir sur riz"],
    imageUrl: "",
  },
  {
    id: "g20",
    name: "Salade de Lentilles Tiède",
    category: "lose_weight",
    mealType: "lunch",
    calories: 429,
    protein: 26,
    carbs: 60,
    fat: 9,
    prepTime: "15 min",
    ingredients: ["250g lentilles cuites", "Carottes, oignon rouge, persil", "Vinaigrette moutarde"],
    instructions: ["Mélanger les lentilles tièdes avec les légumes", "Assaisonner"],
    imageUrl: "",
  },
  {
    id: "g21",
    name: "Crevettes Sautées Riz Complet",
    category: "lose_weight",
    mealType: "lunch",
    calories: 422,
    protein: 54,
    carbs: 46,
    fat: 2,
    prepTime: "15 min",
    ingredients: ["200g crevettes", "150g riz complet", "Légumes sautés", "Ail, citron"],
    instructions: ["Sauter les crevettes à l'ail", "Ajouter les légumes", "Servir sur riz complet"],
    imageUrl: "",
  },
  {
    id: "g22",
    name: "Cabillaud Vapeur Purée Patate Douce",
    category: "lose_weight",
    mealType: "dinner",
    calories: 356,
    protein: 45,
    carbs: 40,
    fat: 2,
    prepTime: "25 min",
    ingredients: ["180g filet de cabillaud", "200g patate douce", "Herbes fraîches"],
    instructions: ["Cuire le cabillaud à la vapeur", "Écraser la patate douce en purée", "Servir avec herbes"],
    imageUrl: "",
  },
  {
    id: "g23",
    name: "Poulet Rôti Légumes du Four",
    category: "balanced",
    mealType: "dinner",
    calories: 468,
    protein: 61,
    carbs: 18,
    fat: 17,
    prepTime: "35 min",
    ingredients: ["180g blanc de poulet", "Courgettes, carottes, poivrons", "Huile d'olive, thym"],
    instructions: ["Rôtir poulet et légumes au four 25-30 min à 200°C"],
    imageUrl: "",
  },
  {
    id: "g24",
    name: "Tofu Sauté Curry Coco Léger",
    category: "balanced",
    mealType: "dinner",
    calories: 412,
    protein: 23,
    carbs: 56,
    fat: 10,
    prepTime: "20 min",
    ingredients: ["200g tofu ferme", "Lait de coco léger, curry", "Légumes de saison", "150g riz"],
    instructions: ["Saisir le tofu", "Ajouter légumes et sauce curry-coco", "Mijoter 10 min, servir sur riz"],
    imageUrl: "",
  },
  {
    id: "g25",
    name: "Steak Haché Maigre & Haricots Verts",
    category: "gain_muscle",
    mealType: "dinner",
    calories: 655,
    protein: 60,
    carbs: 48,
    fat: 25,
    prepTime: "15 min",
    ingredients: ["200g steak haché 5%", "Haricots verts", "200g pommes de terre vapeur"],
    instructions: ["Cuire le steak à la poêle", "Vapeur pour les légumes et pommes de terre"],
    imageUrl: "",
  },
  {
    id: "g26",
    name: "Saumon Teriyaki Riz Complet",
    category: "gain_muscle",
    mealType: "dinner",
    calories: 641,
    protein: 43,
    carbs: 59,
    fat: 26,
    prepTime: "20 min",
    ingredients: ["180g saumon", "Sauce teriyaki maison (soja, miel, gingembre)", "200g riz complet", "Brocoli vapeur"],
    instructions: ["Mariner puis cuire le saumon", "Servir sur riz avec brocoli"],
    imageUrl: "",
  },
  {
    id: "g27",
    name: "Curry de Lentilles Corail",
    category: "balanced",
    mealType: "dinner",
    calories: 487,
    protein: 27,
    carbs: 92,
    fat: 1,
    prepTime: "25 min",
    ingredients: ["250g lentilles corail cuites", "Lait de coco, curry, tomates", "150g riz basmati"],
    instructions: ["Mijoter les lentilles avec épices et tomates 15 min", "Servir sur riz"],
    imageUrl: "",
  },
  {
    id: "g28",
    name: "Blanc de Dinde Poêlée Légumes Verts",
    category: "lose_weight",
    mealType: "dinner",
    calories: 399,
    protein: 57,
    carbs: 18,
    fat: 11,
    prepTime: "20 min",
    ingredients: ["180g blanc de dinde", "Haricots verts, courgettes", "Herbes de Provence"],
    instructions: ["Poêler la dinde", "Cuire les légumes verts à la vapeur", "Assaisonner légèrement"],
    imageUrl: "",
  },
  {
    id: "g29",
    name: "Chili Bœuf & Haricots Noirs",
    category: "gain_muscle",
    mealType: "dinner",
    calories: 842,
    protein: 69,
    carbs: 90,
    fat: 23,
    prepTime: "30 min",
    ingredients: ["180g bœuf haché", "200g haricots noirs", "Tomates concassées, épices", "150g riz"],
    instructions: ["Faire revenir le bœuf", "Ajouter haricots, tomates, épices", "Mijoter 20 min, servir sur riz"],
    imageUrl: "",
  },
  {
    id: "g30",
    name: "Crevettes Courgettes Sautées à l'Ail",
    category: "lose_weight",
    mealType: "dinner",
    calories: 347,
    protein: 52,
    carbs: 14,
    fat: 9,
    prepTime: "15 min",
    ingredients: ["200g crevettes", "Courgettes en tagliatelles", "Ail, citron, persil"],
    instructions: ["Sauter l'ail et les courgettes", "Ajouter les crevettes 3-4 min", "Citronner et servir"],
    imageUrl: "",
  },
  {
    id: "g31",
    name: "Tempeh Sauté Légumes Asiatiques",
    category: "balanced",
    mealType: "dinner",
    calories: 664,
    protein: 42,
    carbs: 77,
    fat: 21,
    prepTime: "20 min",
    ingredients: ["180g tempeh", "Pak-choï, carottes, champignons", "Sauce soja, gingembre", "180g riz"],
    instructions: ["Saisir le tempeh mariné", "Sauter les légumes", "Servir sur riz avec sauce"],
    imageUrl: "",
  },
  {
    id: "g32",
    name: "Shaker Whey Post-Training",
    category: "gain_muscle",
    mealType: "snack",
    calories: 122,
    protein: 24,
    carbs: 3,
    fat: 2,
    prepTime: "2 min",
    ingredients: ["1 dose whey", "300ml eau ou lait"],
    instructions: ["Mélanger au shaker", "Boire dans les 30 min après l'entraînement"],
    imageUrl: "",
  },
  {
    id: "g33",
    name: "Pomme & Beurre de Cacahuète",
    category: "balanced",
    mealType: "snack",
    calories: 94,
    protein: 4,
    carbs: 3,
    fat: 8,
    prepTime: "2 min",
    ingredients: ["1 pomme", "15g beurre de cacahuète"],
    instructions: ["Trancher la pomme", "Tremper dans le beurre de cacahuète"],
    imageUrl: "",
  },
  {
    id: "g34",
    name: "Skyr Nature",
    category: "lose_weight",
    mealType: "snack",
    calories: 93,
    protein: 16,
    carbs: 6,
    fat: 0,
    prepTime: "1 min",
    ingredients: ["150g skyr nature"],
    instructions: ["Servir tel quel, éventuellement avec cannelle"],
    imageUrl: "",
  },
  {
    id: "g35",
    name: "Poignée d'Amandes",
    category: "balanced",
    mealType: "snack",
    calories: 156,
    protein: 5,
    carbs: 6,
    fat: 12,
    prepTime: "1 min",
    ingredients: ["25g amandes"],
    instructions: ["Portion à consommer telle quelle"],
    imageUrl: "",
  },
  {
    id: "g36",
    name: "Cottage Cheese & Fruits Rouges",
    category: "lose_weight",
    mealType: "snack",
    calories: 144,
    protein: 16,
    carbs: 5,
    fat: 6,
    prepTime: "3 min",
    ingredients: ["150g cottage cheese", "Fruits rouges frais"],
    instructions: ["Mélanger dans un bol"],
    imageUrl: "",
  },
  {
    id: "g37",
    name: "Œufs Durs (2)",
    category: "gain_muscle",
    mealType: "snack",
    calories: 141,
    protein: 12,
    carbs: 1,
    fat: 10,
    prepTime: "10 min",
    ingredients: ["2 œufs"],
    instructions: ["Cuire 9-10 min dans l'eau bouillante", "Refroidir, écaler"],
    imageUrl: "",
  },
  {
    id: "g38",
    name: "Toast Fromage Blanc & Concombre",
    category: "lose_weight",
    mealType: "snack",
    calories: 160,
    protein: 13,
    carbs: 17,
    fat: 5,
    prepTime: "5 min",
    ingredients: ["1 tranche pain complet", "80g cottage cheese", "Concombre en rondelles"],
    instructions: ["Tartiner le pain", "Ajouter le concombre"],
    imageUrl: "",
  },
  {
    id: "g39",
    name: "Smoothie Protéiné Banane-Avoine",
    category: "gain_muscle",
    mealType: "snack",
    calories: 334,
    protein: 29,
    carbs: 46,
    fat: 4,
    prepTime: "5 min",
    ingredients: ["1 dose whey", "1 banane", "30g flocons d'avoine", "250ml lait"],
    instructions: ["Mixer tous les ingrédients 30-45 sec"],
    imageUrl: "",
  },
  {
    id: "g40",
    name: "Bowl Skyr Myrtilles & Granola Maison",
    category: "gain_muscle",
    mealType: "breakfast",
    calories: 320,
    protein: 24,
    carbs: 42,
    fat: 6,
    prepTime: "5 min",
    ingredients: ["200g skyr nature", "100g myrtilles", "30g granola", "1 c.à.c de miel"],
    instructions: ["Verser le skyr dans un bol", "Ajouter les myrtilles et le granola", "Terminer par un filet de miel"],
    imageUrl: "",
  },
  {
    id: "g41",
    name: "Œufs Brouillés & Saumon Fumé",
    category: "balanced",
    mealType: "breakfast",
    calories: 360,
    protein: 32,
    carbs: 16,
    fat: 19,
    prepTime: "10 min",
    ingredients: ["3 œufs", "50g saumon fumé", "1 tranche de pain de seigle", "Ciboulette"],
    instructions: ["Battre les œufs et les cuire doucement à la poêle en remuant", "Servir avec le saumon fumé et le pain grillé", "Parsemer de ciboulette"],
    imageUrl: "",
  },
  {
    id: "g42",
    name: "Porridge Banane-Cannelle",
    category: "lose_weight",
    mealType: "breakfast",
    calories: 340,
    protein: 14,
    carbs: 66,
    fat: 3,
    prepTime: "8 min",
    ingredients: ["40g flocons d'avoine", "250ml lait écrémé", "1 banane", "Cannelle"],
    instructions: ["Faire chauffer le lait et les flocons d'avoine à feu doux 5 min", "Ajouter la banane écrasée et la cannelle", "Servir chaud"],
    imageUrl: "",
  },
  {
    id: "g43",
    name: "Tartine Ricotta-Miel-Noix",
    category: "balanced",
    mealType: "breakfast",
    calories: 260,
    protein: 11,
    carbs: 25,
    fat: 14,
    prepTime: "5 min",
    ingredients: ["1 tranche de pain complet", "60g ricotta", "1 c.à.c de miel", "10g noix concassées"],
    instructions: ["Toaster le pain", "Étaler la ricotta", "Ajouter les noix et le miel"],
    imageUrl: "",
  },
  {
    id: "g44",
    name: "Shakshuka",
    category: "balanced",
    mealType: "dinner",
    calories: 330,
    protein: 18,
    carbs: 20,
    fat: 20,
    prepTime: "25 min",
    ingredients: ["2 œufs", "150g sauce tomate", "1/2 poivron", "1/2 oignon", "20g feta", "1 c.à.c d'huile d'olive"],
    instructions: ["Faire revenir l'oignon et le poivron dans l'huile", "Ajouter la sauce tomate et laisser mijoter 10 min", "Creuser deux puits et y casser les œufs", "Couvrir et cuire jusqu'à ce que les blancs soient pris", "Émietter la feta par-dessus"],
    imageUrl: "",
  },
  {
    id: "g45",
    name: "Muffins Protéinés à l'Avoine",
    category: "gain_muscle",
    mealType: "breakfast",
    calories: 460,
    protein: 27,
    carbs: 70,
    fat: 10,
    prepTime: "25 min",
    ingredients: ["60g flocons d'avoine", "1 œuf", "1/2 dose whey", "1 banane écrasée", "1 c.à.c de levure"],
    instructions: ["Mélanger tous les ingrédients", "Répartir dans des moules à muffins", "Cuire 18-20 min à 180°C"],
    imageUrl: "",
  },
  {
    id: "g46",
    name: "Buddha Bowl Quinoa-Pois Chiches",
    category: "balanced",
    mealType: "lunch",
    calories: 550,
    protein: 20,
    carbs: 68,
    fat: 21,
    prepTime: "20 min",
    ingredients: ["150g quinoa cuit", "100g pois chiches", "50g avocat", "Crudités de saison", "1 c.à.s de tahini"],
    instructions: ["Disposer le quinoa au fond du bol", "Ajouter les pois chiches, l'avocat et les crudités", "Napper de tahini"],
    imageUrl: "",
  },
  {
    id: "g47",
    name: "Wrap Poulet-Crudités",
    category: "balanced",
    mealType: "lunch",
    calories: 365,
    protein: 37,
    carbs: 30,
    fat: 10,
    prepTime: "10 min",
    ingredients: ["1 tortilla de blé", "100g poulet grillé", "Crudités (laitue, tomate, carotte)", "1 c.à.s de sauce yaourt"],
    instructions: ["Garnir la tortilla de poulet et de crudités", "Ajouter la sauce", "Rouler fermement et couper en deux"],
    imageUrl: "",
  },
  {
    id: "g48",
    name: "Salade César Poulet Grillé",
    category: "lose_weight",
    mealType: "lunch",
    calories: 380,
    protein: 44,
    carbs: 13,
    fat: 14,
    prepTime: "15 min",
    ingredients: ["120g poulet grillé", "Laitue romaine", "15g parmesan", "15g croûtons", "1 c.à.s de sauce césar allégée"],
    instructions: ["Griller le poulet et le trancher", "Mélanger la laitue avec la sauce", "Ajouter le poulet, le parmesan et les croûtons"],
    imageUrl: "",
  },
  {
    id: "g49",
    name: "Poke Bowl Thon-Riz",
    category: "balanced",
    mealType: "lunch",
    calories: 500,
    protein: 35,
    carbs: 54,
    fat: 17,
    prepTime: "15 min",
    ingredients: ["150g riz cuit", "100g thon frais", "50g edamame", "40g avocat", "Sauce soja-sésame"],
    instructions: ["Répartir le riz dans un bol", "Ajouter le thon coupé en cubes, l'edamame et l'avocat", "Arroser de sauce soja-sésame"],
    imageUrl: "",
  },
  {
    id: "g50",
    name: "Soupe Miso-Tofu-Nouilles",
    category: "lose_weight",
    mealType: "lunch",
    calories: 260,
    protein: 16,
    carbs: 32,
    fat: 7,
    prepTime: "15 min",
    ingredients: ["1 c.à.s de pâte miso", "100g tofu ferme", "60g nouilles soba", "Légumes verts"],
    instructions: ["Diluer la pâte miso dans un bouillon chaud", "Ajouter le tofu en cubes et les nouilles", "Laisser mijoter 5 min avec les légumes"],
    imageUrl: "",
  },
  {
    id: "g51",
    name: "Salade Lentilles-Feta",
    category: "balanced",
    mealType: "lunch",
    calories: 350,
    protein: 20,
    carbs: 33,
    fat: 14,
    prepTime: "10 min",
    ingredients: ["150g lentilles cuites", "40g feta", "Tomates et concombre", "1 c.à.c d'huile d'olive"],
    instructions: ["Mélanger les lentilles avec les légumes coupés", "Émietter la feta par-dessus", "Assaisonner avec l'huile d'olive"],
    imageUrl: "",
  },
  {
    id: "g52",
    name: "Saumon Grillé & Brocolis Vapeur",
    category: "gain_muscle",
    mealType: "dinner",
    calories: 490,
    protein: 41,
    carbs: 38,
    fat: 21,
    prepTime: "20 min",
    ingredients: ["150g filet de saumon", "200g brocolis", "100g riz complet cuit"],
    instructions: ["Cuire le saumon à la poêle 4 min de chaque côté", "Cuire les brocolis à la vapeur 8 min", "Servir avec le riz complet"],
    imageUrl: "",
  },
  {
    id: "g53",
    name: "Poulet Rôti aux Herbes & Patates Douces",
    category: "gain_muscle",
    mealType: "dinner",
    calories: 500,
    protein: 53,
    carbs: 49,
    fat: 11,
    prepTime: "35 min",
    ingredients: ["150g blanc de poulet", "200g patate douce", "100g haricots verts", "Herbes de Provence", "1 c.à.c d'huile d'olive"],
    instructions: ["Rôtir la patate douce coupée en cubes 25 min à 200°C", "Faire cuire le poulet aux herbes à la poêle", "Cuire les haricots verts à la vapeur"],
    imageUrl: "",
  },
  {
    id: "g54",
    name: "Curry de Pois Chiches & Riz Basmati",
    category: "balanced",
    mealType: "dinner",
    calories: 550,
    protein: 19,
    carbs: 90,
    fat: 12,
    prepTime: "25 min",
    ingredients: ["150g pois chiches cuits", "100ml lait de coco léger", "150g riz basmati cuit", "Oignon, tomate, épices à curry"],
    instructions: ["Faire revenir l'oignon avec les épices", "Ajouter les pois chiches, la tomate et le lait de coco", "Laisser mijoter 12 min et servir avec le riz"],
    imageUrl: "",
  },
  {
    id: "g55",
    name: "Steak Haché & Haricots Verts",
    category: "lose_weight",
    mealType: "dinner",
    calories: 380,
    protein: 39,
    carbs: 40,
    fat: 7,
    prepTime: "15 min",
    ingredients: ["150g steak haché 5% MG", "150g haricots verts", "150g pommes de terre vapeur"],
    instructions: ["Cuire le steak haché à la poêle selon la cuisson désirée", "Cuire les haricots verts et les pommes de terre à la vapeur"],
    imageUrl: "",
  },
  {
    id: "g56",
    name: "Cabillaud en Papillote & Légumes",
    category: "lose_weight",
    mealType: "dinner",
    calories: 250,
    protein: 36,
    carbs: 13,
    fat: 6,
    prepTime: "25 min",
    ingredients: ["180g filet de cabillaud", "Courgette, poivron, tomate", "1 c.à.c d'huile d'olive", "Citron"],
    instructions: ["Disposer le poisson et les légumes sur du papier cuisson", "Arroser d'huile d'olive et de jus de citron", "Fermer en papillote et cuire 18 min à 200°C"],
    imageUrl: "",
  },
  {
    id: "g57",
    name: "Chili Con Carne Allégé",
    category: "balanced",
    mealType: "dinner",
    calories: 370,
    protein: 38,
    carbs: 38,
    fat: 7,
    prepTime: "30 min",
    ingredients: ["120g bœuf haché 5% MG", "150g haricots rouges", "150g tomates concassées", "Oignon, épices"],
    instructions: ["Faire revenir le bœuf et l'oignon", "Ajouter les tomates, les haricots rouges et les épices", "Laisser mijoter 20 min"],
    imageUrl: "",
  },
  {
    id: "g58",
    name: "Barre Maison Amandes-Dattes",
    category: "gain_muscle",
    mealType: "snack",
    calories: 180,
    protein: 5,
    carbs: 24,
    fat: 8,
    prepTime: "10 min",
    ingredients: ["20g dattes", "15g amandes", "10g flocons d'avoine"],
    instructions: ["Mixer les dattes et les amandes", "Incorporer les flocons d'avoine", "Former une barre et laisser prendre au frais"],
    imageUrl: "",
  },
  {
    id: "g59",
    name: "Pomme & Beurre de Cacahuète",
    category: "lose_weight",
    mealType: "snack",
    calories: 190,
    protein: 4,
    carbs: 29,
    fat: 8,
    prepTime: "2 min",
    ingredients: ["1 pomme", "1 c.à.s de beurre de cacahuète"],
    instructions: ["Couper la pomme en tranches", "Tremper dans le beurre de cacahuète"],
    imageUrl: "",
  },
  {
    id: "g60",
    name: "Yaourt Grec & Noix",
    category: "balanced",
    mealType: "snack",
    calories: 210,
    protein: 17,
    carbs: 12,
    fat: 10,
    prepTime: "3 min",
    ingredients: ["150g yaourt grec", "15g noix", "1 c.à.c de miel"],
    instructions: ["Verser le yaourt dans un bol", "Ajouter les noix concassées et le miel"],
    imageUrl: "",
  },
  {
    id: "g61",
    name: "Edamame Salés",
    category: "lose_weight",
    mealType: "snack",
    calories: 190,
    protein: 17,
    carbs: 16,
    fat: 8,
    prepTime: "5 min",
    ingredients: ["155g edamame surgelés", "Fleur de sel"],
    instructions: ["Cuire les edamame à l'eau bouillante salée 5 min", "Égoutter et saler légèrement"],
    imageUrl: "",
  },
  {
    id: "g62",
    name: "Fromage Blanc & Fruits Rouges",
    category: "lose_weight",
    mealType: "snack",
    calories: 120,
    protein: 13,
    carbs: 15,
    fat: 1,
    prepTime: "3 min",
    ingredients: ["150g fromage blanc 0%", "80g fruits rouges"],
    instructions: ["Verser le fromage blanc dans un bol", "Ajouter les fruits rouges"],
    imageUrl: "",
  },
  {
    id: "g63",
    name: "Mix de Noix & Fruits Secs",
    category: "gain_muscle",
    mealType: "snack",
    calories: 145,
    protein: 4,
    carbs: 13,
    fat: 9,
    prepTime: "1 min",
    ingredients: ["10g amandes", "10g noix de cajou", "10g raisins secs"],
    instructions: ["Mélanger tous les ingrédients dans un petit bol"],
    imageUrl: "",
  },
];

// Exercise database with SVG animation paths
export interface Exercise {
  id: string;
  name: string;
  category: "lose_weight" | "gain_muscle" | "flexibility" | "cardio";
  muscleGroup: string;
  difficulty: "beginner" | "intermediate" | "advanced";
  caloriesBurned: number;
  duration: string;
  sets?: string;
  reps?: string;
  description: string;
  instructions: string[];
  emoji: string;
  animationType: "squat" | "pushup" | "plank" | "lunge" | "crunch" | "jumping" | "running" | "cycling" | "yoga" | "pullup" | "deadlift" | "burpee";
}

export const exercises: Exercise[] = [
  {
    id: "1",
    name: "Running / Jogging",
    category: "cardio",
    muscleGroup: "Full Body",
    difficulty: "beginner",
    caloriesBurned: 300,
    duration: "30 min",
    description: "Classic cardio exercise that burns significant calories and improves cardiovascular health.",
    instructions: [
      "Start with a 5-minute warm-up walk",
      "Gradually increase pace to a comfortable jog",
      "Maintain steady breathing rhythm",
      "Cool down with 5-minute walk",
    ],
    emoji: "🏃",
    animationType: "running",
  },
  {
    id: "2",
    name: "Push-Ups",
    category: "gain_muscle",
    muscleGroup: "Chest, Shoulders, Triceps",
    difficulty: "beginner",
    caloriesBurned: 100,
    duration: "15 min",
    sets: "4",
    reps: "12-15",
    description: "Fundamental upper body exercise targeting chest, shoulders, and triceps.",
    instructions: [
      "Start in plank position with hands shoulder-width apart",
      "Lower body until chest nearly touches the floor",
      "Push back up to starting position",
      "Keep core tight throughout the movement",
    ],
    emoji: "💪",
    animationType: "pushup",
  },
  {
    id: "3",
    name: "Squats",
    category: "gain_muscle",
    muscleGroup: "Quadriceps, Glutes, Hamstrings",
    difficulty: "beginner",
    caloriesBurned: 150,
    duration: "20 min",
    sets: "4",
    reps: "12-15",
    description: "Essential lower body compound movement for building leg and glute strength.",
    instructions: [
      "Stand with feet shoulder-width apart",
      "Lower hips back and down as if sitting in a chair",
      "Keep chest up and knees tracking over toes",
      "Push through heels to stand back up",
    ],
    emoji: "🦵",
    animationType: "squat",
  },
  {
    id: "4",
    name: "HIIT Burpees",
    category: "lose_weight",
    muscleGroup: "Full Body",
    difficulty: "intermediate",
    caloriesBurned: 400,
    duration: "25 min",
    description: "High-intensity interval training alternating between intense bursts and rest periods.",
    instructions: [
      "Start standing, drop into a squat position",
      "Kick feet back into plank position",
      "Do a push-up, jump feet back to squat",
      "Explosively jump up with arms overhead",
      "Repeat for 30 seconds, rest 15 seconds",
    ],
    emoji: "🔥",
    animationType: "burpee",
  },
  {
    id: "5",
    name: "Deadlifts",
    category: "gain_muscle",
    muscleGroup: "Back, Hamstrings, Glutes",
    difficulty: "intermediate",
    caloriesBurned: 180,
    duration: "20 min",
    sets: "4",
    reps: "8-10",
    description: "Powerful compound exercise that strengthens the posterior chain.",
    instructions: [
      "Stand with feet hip-width apart, barbell over mid-foot",
      "Hinge at hips, grip bar just outside knees",
      "Brace core and lift by driving through legs",
      "Lock out hips at top, reverse slowly",
    ],
    emoji: "🏋️",
    animationType: "deadlift",
  },
  {
    id: "6",
    name: "Plank Hold",
    category: "gain_muscle",
    muscleGroup: "Core",
    difficulty: "beginner",
    caloriesBurned: 60,
    duration: "10 min",
    sets: "4",
    reps: "30-60 sec hold",
    description: "Isometric core exercise that builds stability and endurance.",
    instructions: [
      "Start in forearm plank position",
      "Keep body in a straight line from head to heels",
      "Engage core and squeeze glutes",
      "Hold position for the target duration",
    ],
    emoji: "🧘",
    animationType: "plank",
  },
  {
    id: "7",
    name: "Cycling",
    category: "cardio",
    muscleGroup: "Legs, Cardiovascular",
    difficulty: "beginner",
    caloriesBurned: 250,
    duration: "30 min",
    description: "Low-impact cardio that's great for burning fat while being easy on joints.",
    instructions: [
      "Adjust seat to proper height",
      "Start with moderate resistance",
      "Alternate between seated and standing intervals",
      "Maintain cadence of 80-100 RPM",
    ],
    emoji: "🚴",
    animationType: "cycling",
  },
  {
    id: "8",
    name: "Pull-Ups",
    category: "gain_muscle",
    muscleGroup: "Back, Biceps",
    difficulty: "advanced",
    caloriesBurned: 120,
    duration: "15 min",
    sets: "4",
    reps: "6-10",
    description: "Upper body pulling exercise that builds a strong back and arms.",
    instructions: [
      "Grip bar with hands slightly wider than shoulders",
      "Hang with arms fully extended",
      "Pull body up until chin clears the bar",
      "Lower slowly to starting position",
    ],
    emoji: "🤸",
    animationType: "pullup",
  },
  {
    id: "9",
    name: "Yoga Flow",
    category: "flexibility",
    muscleGroup: "Full Body",
    difficulty: "beginner",
    caloriesBurned: 80,
    duration: "30 min",
    description: "Gentle flowing movements that improve flexibility, balance, and mindfulness.",
    instructions: [
      "Start in mountain pose, focus on breathing",
      "Flow through sun salutation sequence",
      "Hold warrior poses for 30 seconds each",
      "End with 5 minutes of savasana",
    ],
    emoji: "🧘‍♀️",
    animationType: "yoga",
  },
  {
    id: "10",
    name: "Lunges",
    category: "lose_weight",
    muscleGroup: "Legs, Glutes",
    difficulty: "beginner",
    caloriesBurned: 200,
    duration: "20 min",
    sets: "3",
    reps: "12 each leg",
    description: "Unilateral leg exercise that improves balance and builds lower body strength.",
    instructions: [
      "Stand tall with feet hip-width apart",
      "Step forward with one leg, lowering hips",
      "Lower until both knees are at 90 degrees",
      "Push back to starting position, alternate legs",
    ],
    emoji: "🦿",
    animationType: "lunge",
  },
  {
    id: "11",
    name: "Crunches",
    category: "gain_muscle",
    muscleGroup: "Abs",
    difficulty: "beginner",
    caloriesBurned: 50,
    duration: "10 min",
    sets: "3",
    reps: "20-25",
    description: "Targeted ab exercise to build core strength and definition.",
    instructions: [
      "Lie on back with knees bent, feet flat",
      "Place hands behind head, elbows wide",
      "Curl shoulders off the floor toward knees",
      "Lower slowly with control",
    ],
    emoji: "💫",
    animationType: "crunch",
  },
  {
    id: "12",
    name: "Jumping Jacks",
    category: "cardio",
    muscleGroup: "Full Body",
    difficulty: "beginner",
    caloriesBurned: 280,
    duration: "15 min",
    description: "Classic cardio movement that elevates heart rate and burns calories quickly.",
    instructions: [
      "Stand with feet together, arms at sides",
      "Jump feet out wide while raising arms overhead",
      "Jump back to starting position",
      "Repeat at a steady, quick pace",
    ],
    emoji: "⭐",
    animationType: "jumping",
  },
];
