import type { Recipe } from "./nutrition";
import type { Lang } from "./i18n";

interface RecipeTranslation {
  name: string;
  prepTime: string;
  ingredients: string[];
  instructions: string[];
}

export const RECIPE_FR: Record<string, RecipeTranslation> = {
  b1: { name: "Pancakes Protéinés", prepTime: "15 min", ingredients: ["1 dose de whey", "1 banane", "2 œufs", "60g de flocons d'avoine", "1 c.à.c de levure chimique", "Sirop d'érable (optionnel)"], instructions: ["Mixer la banane, les œufs, l'avoine, la whey et la levure", "Chauffer une poêle antiadhésive à feu moyen", "Verser la pâte pour former des pancakes", "Cuire 2-3 min de chaque côté jusqu'à coloration dorée", "Garnir de fruits rouges ou de sirop d'érable"] },
  b2: { name: "Toast Avocat & Œufs", prepTime: "10 min", ingredients: ["2 tranches de pain complet", "1 avocat mûr", "2 œufs", "Tomates cerises", "Sel, poivre, piment en flocons", "Jus de citron"], instructions: ["Faire griller le pain jusqu'à ce qu'il soit doré et croustillant", "Écraser l'avocat avec le jus de citron, sel et poivre", "Pocher ou frire les œufs selon ta préférence", "Étaler l'avocat sur le pain, ajouter les œufs", "Garnir de tomates et de piment en flocons"] },
  b3: { name: "Parfait au Yaourt Grec", prepTime: "5 min", ingredients: ["250g de yaourt grec (0%)", "80g de fruits rouges mélangés", "2 c.à.s de granola", "1 c.à.s de miel", "1 c.à.s de graines de chia"], instructions: ["Verser la moitié du yaourt dans un verre ou un bol", "Ajouter la moitié des fruits rouges et du granola", "Répéter les couches avec le reste des ingrédients", "Arroser de miel", "Terminer avec les graines de chia"] },
  b4: { name: "Avoine Protéinée Overnight", prepTime: "5 min + une nuit", ingredients: ["50g de flocons d'avoine", "1 dose de whey", "250g de yaourt grec", "1 c.à.s de beurre de cacahuète", "Myrtilles", "Graines de chia"], instructions: ["Mélanger l'avoine, la whey et le yaourt dans un bocal", "Ajouter un peu de lait pour la consistance souhaitée", "Incorporer les graines de chia", "Réfrigérer toute la nuit", "Garnir de beurre de cacahuète et de myrtilles le matin"] },
  b5: { name: "Omelette Blancs d'Œufs & Légumes", prepTime: "12 min", ingredients: ["4 blancs d'œufs", "30g d'épinards", "30g de champignons", "30g de poivrons", "2 c.à.s de feta", "Herbes fraîches"], instructions: ["Battre les blancs d'œufs avec sel et poivre", "Faire revenir les légumes dans une poêle antiadhésive", "Verser les blancs d'œufs sur les légumes", "Cuire jusqu'à ce que ce soit pris, plier en deux", "Garnir de feta et d'herbes fraîches"] },
  b6: { name: "Smoothie Bowl", prepTime: "8 min", ingredients: ["1 banane congelée", "80g de fruits rouges congelés", "125ml de lait d'amande", "2 c.à.s de purée d'amande", "Toppings : granola, noix de coco, graines"], instructions: ["Mixer les fruits congelés avec le lait d'amande jusqu'à consistance épaisse", "Verser dans un bol", "Ajouter la purée d'amande", "Garnir de granola, noix de coco râpée et graines", "Servir immédiatement"] },
  b7: { name: "Burrito Petit-Déjeuner", prepTime: "15 min", ingredients: ["2 œufs entiers + 2 blancs", "1 grande tortilla", "40g de haricots noirs", "2 c.à.s de fromage", "Salsa et avocat", "Bacon de dinde (2 tranches)"], instructions: ["Cuire le bacon de dinde jusqu'à ce qu'il soit croustillant", "Brouiller les œufs avec sel et poivre", "Réchauffer la tortilla à la poêle", "Superposer œufs, haricots, bacon, fromage", "Ajouter salsa et avocat, rouler fermement"] },
  b8: { name: "Bowl de Fromage Blanc", prepTime: "5 min", ingredients: ["250g de fromage blanc allégé", "80g d'ananas en morceaux", "1 c.à.s de miel", "2 c.à.s de noix", "Cannelle"], instructions: ["Verser le fromage blanc dans un bol", "Ajouter les morceaux d'ananas par-dessus", "Arroser de miel", "Saupoudrer de noix et de cannelle", "Déguster froid"] },
  b9: { name: "Porridge Banane-Noix", prepTime: "10 min", ingredients: ["50g de flocons d'avoine", "250ml de lait", "1 banane en tranches", "2 c.à.s de noix", "1 c.à.s de miel", "Cannelle"], instructions: ["Cuire l'avoine avec le lait selon les instructions", "Incorporer la moitié de la banane en cours de cuisson", "Verser dans un bol", "Garnir avec le reste de banane et les noix", "Arroser de miel et ajouter la cannelle"] },
  b10: { name: "Shakshuka", prepTime: "25 min", ingredients: ["3 œufs", "1 boîte de tomates concassées", "1/2 oignon émincé", "1 poivron", "Cumin, paprika, ail", "Persil frais, feta"], instructions: ["Faire revenir l'oignon et le poivron jusqu'à tendreté", "Ajouter les épices et l'ail, cuire 1 min", "Verser les tomates, laisser mijoter 10 min", "Creuser des puits et y casser les œufs", "Couvrir et cuire jusqu'à ce que les œufs soient pris"] },
  l1: { name: "Salade de Poulet Grillé", prepTime: "20 min", ingredients: ["150g de blanc de poulet", "2 tasses de mesclun", "1/2 avocat", "Tomates cerises", "Concombre", "Vinaigrette huile d'olive & citron"], instructions: ["Assaisonner le poulet avec sel, poivre et herbes", "Griller le poulet 6-7 min de chaque côté", "Préparer la base de salade avec mesclun, tomates et concombre", "Trancher le poulet et le disposer par-dessus", "Ajouter l'avocat en tranches et arroser de vinaigrette"] },
  l2: { name: "Bowl Protéiné", prepTime: "25 min", ingredients: ["200g de blanc de poulet", "185g de riz complet", "80g de haricots noirs", "1/2 avocat", "Salsa", "Maïs"], instructions: ["Cuire le riz complet selon les instructions", "Assaisonner et griller le poulet", "Réchauffer les haricots noirs avec cumin et ail", "Assembler le bowl avec le riz en base, le poulet tranché", "Garnir de haricots, avocat, maïs et salsa"] },
  l3: { name: "Bowl Quinoa Méditerranéen", prepTime: "25 min", ingredients: ["185g de quinoa cuit", "80g de pois chiches", "Concombre, tomates, oignon rouge", "Feta", "Olives Kalamata", "Sauce tzatziki"], instructions: ["Cuire le quinoa et laisser tiédir", "Couper en dés le concombre, les tomates et l'oignon rouge", "Mélanger le quinoa avec les légumes et les pois chiches", "Garnir de feta et d'olives", "Arroser de tzatziki"] },
  l4: { name: "Wraps de Laitue à la Dinde", prepTime: "15 min", ingredients: ["200g de dinde hachée", "Feuilles de laitue beurre", "Châtaignes d'eau", "Sauce soja", "Gingembre & ail", "Oignons verts"], instructions: ["Cuire la dinde hachée avec le gingembre et l'ail", "Ajouter les châtaignes d'eau en dés et la sauce soja", "Cuire jusqu'à ce que la dinde soit dorée et parfumée", "Répartir la préparation dans les feuilles de laitue", "Garnir d'oignons verts"] },
  l5: { name: "Poke Bowl au Thon", prepTime: "20 min", ingredients: ["150g de thon frais en cubes", "185g de riz à sushi", "Edamame", "Avocat", "Sauce soja, huile de sésame", "Graines de sésame, nori"], instructions: ["Cuire le riz à sushi et laisser refroidir", "Faire mariner le thon dans la sauce soja et l'huile de sésame", "Disposer le riz dans un bol", "Garnir de thon, edamame et avocat", "Parsemer de graines de sésame et de lanières de nori"] },
  l6: { name: "Wrap César au Poulet", prepTime: "15 min", ingredients: ["150g de blanc de poulet grillé", "1 grande tortilla", "Laitue romaine", "Parmesan", "Sauce César allégée", "Croûtons"], instructions: ["Couper le poulet grillé en lanières", "Émincer la laitue romaine", "Mélanger la laitue avec la sauce et le parmesan", "Disposer sur la tortilla avec le poulet", "Ajouter les croûtons et rouler fermement"] },
  l7: { name: "Salade de Bœuf à l'Asiatique", prepTime: "20 min", ingredients: ["150g de bavette", "Salade asiatique mélangée", "Rubans de carotte et concombre", "Menthe et coriandre fraîches", "Vinaigrette citron vert-piment", "Cacahuètes concassées"], instructions: ["Griller le bœuf à point, laisser reposer", "Préparer des rubans de légumes à l'économe", "Mélanger la salade avec les herbes et les légumes", "Trancher le bœuf dans le sens contraire des fibres", "Garnir la salade de bœuf, vinaigrette et cacahuètes"] },
  l8: { name: "Soupe de Lentilles", prepTime: "35 min", ingredients: ["200g de lentilles corail", "Oignon, carottes, céleri", "1L de bouillon de légumes", "Cumin, curcuma, ail", "Jus de citron", "Persil frais"], instructions: ["Faire revenir l'oignon, les carottes et le céleri jusqu'à tendreté", "Ajouter l'ail et les épices, cuire 1 min", "Ajouter les lentilles et le bouillon, porter à ébullition", "Laisser mijoter 25 min jusqu'à ce que les lentilles soient tendres", "Mixer partiellement, ajouter le jus de citron"] },
  d1: { name: "Bowl Saumon & Quinoa", prepTime: "30 min", ingredients: ["150g de filet de saumon", "185g de quinoa", "Brocolis vapeur", "Patate douce en cubes", "Glaçage soja & gingembre"], instructions: ["Cuire le quinoa et réserver", "Rôtir la patate douce en cubes 20 min à 200°C", "Saisir le saumon 4 min de chaque côté", "Cuire les brocolis à la vapeur jusqu'à tendreté", "Assembler le bowl et arroser du glaçage"] },
  d2: { name: "Steak Grillé & Légumes", prepTime: "25 min", ingredients: ["200g de faux-filet", "Asperges", "Tomates cerises", "Beurre à l'ail", "Romarin frais", "Pomme de terre au four"], instructions: ["Sortir le steak à température ambiante", "Assaisonner avec sel, poivre, romarin", "Griller 4-5 min de chaque côté pour une cuisson à point", "Laisser reposer 5 minutes avant de trancher", "Servir avec les légumes grillés et la pomme de terre"] },
  d3: { name: "Poulet Sauté au Wok", prepTime: "20 min", ingredients: ["200g de blanc de poulet en lamelles", "Brocolis, pois gourmands, poivrons", "Ail, gingembre", "Sauce soja allégée en sel", "Huile de sésame", "Riz complet (optionnel)"], instructions: ["Chauffer un wok ou une grande poêle à feu vif", "Faire sauter le poulet jusqu'à cuisson, réserver", "Faire sauter les légumes 3-4 minutes", "Ajouter ail, gingembre, sauce soja", "Remettre le poulet, mélanger le tout"] },
  d4: { name: "Cabillaud au Four & Légumes", prepTime: "30 min", ingredients: ["200g de filet de cabillaud", "Courgette, tomates cerises", "Tranches de citron", "Aneth frais, câpres", "Huile d'olive", "Vin blanc (optionnel)"], instructions: ["Préchauffer le four à 200°C", "Disposer le cabillaud sur papier alu avec les légumes", "Assaisonner, ajouter citron, aneth, câpres", "Arroser d'huile d'olive, refermer la papillote", "Cuire 18-20 minutes jusqu'à ce que le poisson s'effeuille"] },
  d5: { name: "Boulettes de Dinde & Zoodles", prepTime: "30 min", ingredients: ["200g de dinde hachée", "2 courgettes en spirales", "Sauce marinara (peu sucrée)", "Herbes italiennes", "Parmesan", "Basilic frais"], instructions: ["Mélanger la dinde avec les herbes, former des boulettes", "Cuire les boulettes au four 20 min à 200°C", "Réchauffer la sauce marinara à la poêle", "Faire sauter les zoodles 2-3 minutes", "Servir les zoodles avec les boulettes et la sauce"] },
  d6: { name: "Bowl Saumon Teriyaki", prepTime: "25 min", ingredients: ["150g de filet de saumon", "185g de riz jasmin", "Sauce teriyaki", "Pak-choï vapeur", "Gingembre mariné, graines de sésame", "Avocat en tranches"], instructions: ["Cuire le riz selon les instructions", "Badigeonner le saumon de teriyaki, cuire au four 12 min", "Cuire le pak-choï à la vapeur jusqu'à tendreté", "Assembler le bowl avec le riz en base", "Garnir de saumon, pak-choï et avocat"] },
  d7: { name: "Tacos de Bœuf Maigre", prepTime: "20 min", ingredients: ["150g de bœuf haché maigre", "3 tortillas de maïs", "Assaisonnement pour tacos", "Laitue, tomate, oignon", "Yaourt grec (substitut crème)", "Citron vert, coriandre"], instructions: ["Faire dorer le bœuf avec l'assaisonnement", "Réchauffer les tortillas à sec dans une poêle", "Couper les légumes en dés pour la garniture", "Assembler les tacos avec le bœuf et les légumes", "Garnir de yaourt, coriandre et jus de citron vert"] },
  d8: { name: "Poivrons Farcis", prepTime: "45 min", ingredients: ["4 poivrons", "150g de dinde hachée", "80g de riz cuit", "Haricots noirs", "Sauce tomate", "Fromage, coriandre"], instructions: ["Couper le haut des poivrons, retirer les graines", "Faire dorer la dinde avec oignon et ail", "Mélanger avec le riz, les haricots et la moitié de la sauce", "Farcir les poivrons, napper du reste de sauce", "Cuire au four à 180°C pendant 30 min, ajouter le fromage"] },
  d9: { name: "Pâtes aux Crevettes", prepTime: "25 min", ingredients: ["200g de crevettes", "200g de pâtes complètes", "Tomates cerises", "Ail, vin blanc", "Basilic frais", "Parmesan, huile d'olive"], instructions: ["Cuire les pâtes al dente", "Faire revenir l'ail dans l'huile d'olive", "Ajouter les crevettes, cuire jusqu'à ce qu'elles rosissent", "Ajouter les tomates et le vin, laisser mijoter 3 min", "Mélanger avec les pâtes, le basilic et le parmesan"] },
  d10: { name: "Curry de Poulet", prepTime: "35 min", ingredients: ["200g de haut de cuisse de poulet en cubes", "1 boîte de lait de coco léger", "Pâte de curry", "Poivrons, oignon", "Riz basmati", "Coriandre fraîche"], instructions: ["Faire revenir l'oignon et les poivrons", "Ajouter la pâte de curry, cuire 1 min", "Ajouter le poulet, cuire jusqu'à coloration", "Verser le lait de coco, laisser mijoter 20 min", "Servir sur riz avec la coriandre"] },
  d11: { name: "Poulet Rôti aux Herbes", prepTime: "50 min", ingredients: ["2 hauts de cuisse de poulet (avec os)", "Pommes de terre en quartiers", "Citron, romarin, thym", "Gousses d'ail", "Huile d'olive", "Haricots verts"], instructions: ["Préchauffer le four à 200°C", "Assaisonner le poulet avec herbes et zeste de citron", "Disposer avec les pommes de terre et l'ail", "Rôtir 40 min jusqu'à coloration dorée", "Servir avec des haricots verts vapeur"] },
  d12: { name: "Sauté de Tofu aux Légumes", prepTime: "20 min", ingredients: ["200g de tofu ferme en cubes", "Légumes mélangés", "Ail, gingembre", "Sauce soja allégée en sel", "Huile de sésame", "Riz complet (optionnel)"], instructions: ["Presser le tofu et le couper en cubes", "Faire frire le tofu jusqu'à coloration dorée, réserver", "Faire sauter les légumes avec ail et gingembre", "Ajouter le tofu et la sauce", "Servir sur riz complet"] },
  s1: { name: "Boules d'Énergie Protéinées", prepTime: "15 min", ingredients: ["100g de flocons d'avoine", "125g de beurre de cacahuète", "1 dose de whey", "2 c.à.s de miel", "Pépites de chocolat noir"], instructions: ["Mélanger tous les ingrédients dans un bol", "Réfrigérer 30 min pour que ça raffermisse", "Former 12 boules", "Conserver au réfrigérateur", "À emporter facilement !"] },
  s2: { name: "Pomme & Purée d'Amande", prepTime: "5 min", ingredients: ["1 pomme moyenne", "2 c.à.s de purée d'amande", "Cannelle", "Graines de chanvre (optionnel)"], instructions: ["Évider et couper la pomme en tranches", "Disposer sur une assiette", "Ajouter la purée d'amande pour tremper", "Saupoudrer de cannelle et de graines de chanvre"] },
  s3: { name: "Yaourt Grec & Fruits Rouges", prepTime: "3 min", ingredients: ["150g de yaourt grec (0%)", "80g de fruits rouges mélangés", "1 c.à.c de miel", "Feuilles de menthe"], instructions: ["Verser le yaourt dans un bol", "Garnir de fruits rouges frais", "Arroser de miel", "Décorer de menthe"] },
  s4: { name: "Bâtonnets de Légumes & Houmous", prepTime: "5 min", ingredients: ["Carottes, céleri, concombre", "Lanières de poivron", "60g de houmous", "Paprika pour la garniture"], instructions: ["Couper les légumes en bâtonnets", "Les disposer autour du houmous", "Saupoudrer le houmous de paprika", "Tremper et déguster !"] },
  s5: { name: "Fromage Blanc & Ananas", prepTime: "3 min", ingredients: ["250g de fromage blanc", "80g d'ananas en morceaux", "Noix de coco râpée", "Noix de macadamia (optionnel)"], instructions: ["Verser le fromage blanc dans un bol", "Ajouter les morceaux d'ananas", "Garnir de noix de coco râpée", "Ajouter des noix pour le croquant"] },
  s6: { name: "Mélange du Randonneur", prepTime: "2 min", ingredients: ["Amandes", "Noix", "Pépites de chocolat noir", "Canneberges séchées", "Graines de courge"], instructions: ["Mélanger tous les ingrédients ensemble", "Répartir en portions de 60g", "Conserver dans un contenant hermétique", "Parfait pour un encas nomade"] },
  s7: { name: "Galettes de Riz à l'Avocat", prepTime: "5 min", ingredients: ["2 galettes de riz", "1/2 avocat", "Assaisonnement everything bagel", "Jus de citron vert", "Tomates cerises"], instructions: ["Écraser l'avocat avec le jus de citron vert", "Étaler sur les galettes de riz", "Ajouter les tomates en tranches", "Saupoudrer d'assaisonnement"] },
  s8: { name: "Edamame", prepTime: "5 min", ingredients: ["150g d'edamame en cosses", "Fleur de sel", "Piment en flocons (optionnel)", "Zeste de citron vert"], instructions: ["Cuire l'edamame à la vapeur ou au micro-ondes", "Égoutter l'excès d'eau", "Assaisonner avec sel et piment", "Ajouter le zeste de citron vert et déguster"] },
  s9: { name: "Smoothie Protéiné", prepTime: "5 min", ingredients: ["1 dose de whey", "1 banane", "250ml de lait d'amande", "1 c.à.s de beurre de cacahuète", "Glaçons"], instructions: ["Mettre tous les ingrédients dans un blender", "Mixer jusqu'à consistance lisse", "Ajouter du lait si trop épais", "Verser et déguster immédiatement"] },
  s10: { name: "Chocolat Noir & Amandes", prepTime: "1 min", ingredients: ["30g de chocolat noir (70%+)", "15 amandes"], instructions: ["Casser le chocolat en carrés", "Accompagner d'amandes", "Savourer lentement", "Riche en antioxydants !"] },
  s11: { name: "Bouchées Concombre-Thon", prepTime: "10 min", ingredients: ["1 concombre", "1 boîte de thon (au naturel)", "Yaourt grec", "Aneth, jus de citron", "Assaisonnement everything"], instructions: ["Couper le concombre en rondelles épaisses", "Mélanger le thon avec yaourt, aneth, citron", "Répartir la préparation sur le concombre", "Saupoudrer d'assaisonnement"] },
  s12: { name: "Bouchées de Banane Congelée", prepTime: "10 min + congélation", ingredients: ["2 bananes", "Chocolat noir fondu", "Cacahuètes concassées", "Noix de coco râpée"], instructions: ["Couper les bananes en rondelles", "Tremper dans le chocolat fondu", "Saupoudrer des toppings", "Congeler pendant 1 heure"] },
  s13: { name: "Brochettes Caprese", prepTime: "10 min", ingredients: ["Tomates cerises", "Billes de mozzarella fraîche", "Feuilles de basilic frais", "Glaçage balsamique", "Huile d'olive"], instructions: ["Enfiler tomate, basilic, mozzarella sur des piques", "Disposer sur une assiette", "Arroser d'huile d'olive", "Terminer avec le glaçage balsamique"] },
  s14: { name: "Pois Chiches Rôtis", prepTime: "35 min", ingredients: ["1 boîte de pois chiches, égouttés", "Spray d'huile d'olive", "Cumin, paprika, ail", "Sel"], instructions: ["Bien sécher les pois chiches", "Mélanger avec l'huile et les épices", "Répartir sur une plaque de cuisson", "Rôtir à 200°C pendant 30 min", "Secouer la plaque à mi-cuisson"] },
};

export function translateRecipe(recipe: Recipe, lang: Lang): Recipe {
  if (lang !== "fr") return recipe;
  const tr = RECIPE_FR[recipe.id];
  if (!tr) return recipe;
  return { ...recipe, name: tr.name, prepTime: tr.prepTime, ingredients: tr.ingredients, instructions: tr.instructions };
}
